### ISSUE TITLE
Support for Whitespace Control

### ISSUE THREAD

**Issue by stephanbuys** [Keats/tera#10]
Support the functionality depicted here: http://jinja.pocoo.org/docs/dev/templates/#whitespace-control

**Comment by Keats** [comment]
it's on the TODO list but will probably be the default, not an option

**Comment by Keats** [comment]
Next on the todo, hopefully won't take too much time

**Comment by Keats** [comment]
I merged #13 which has some sort of whitespace cleaning, let me know if that's enough

**Comment by Keats** [comment]
@stephanbuys let's continue here

The goal of Tera is not to be a carbon copy port of jinja, it would actually be closer to django in spirit.
Tera strips all blocks whitespace by default so the `-` in tags should not be needed, if you see some rendering that is not what you expected we can have a look

**Comment by stephanbuys** [comment]
@Keats I feel like such a pain 😨 Apologies, upon closer inspection I see what you mean, I think it will work nicely, if I stumble across scenarios where anything breaks due to it I'll re-open.

**Comment by elibroftw** [comment]
I'm using Tera engine in Rocket and when the following is in my template, a blank line shows up. Is there anyway to make it so that if the variable is false the engine does not generate the extra new line?

```jinja
<div>
{% if next_page %}
    <input name="next_page" hidden value="/test" />
{% endif %}
<p>test</p>
</div>
```

I have

**Comment by elibroftw** [comment]
Nvm, I had placeed the minus in the wrong spot.
