### ISSUE TITLE
New feature request:Templates optimization.

### ISSUE THREAD

**Issue by zoumi** [Keats/tera#101]
The title may not be suitable.
What I want to convey is:
if tera automaticly removes comment tags and all unnecessary blank chars, the data tansports to client will be reduced.

**Comment by Keats** [comment]
Which comment tags are you referring to? The `{# #}` are already removed.

By removing all unnecessary blank chars, do you mean minifying HTML?

**Comment by zoumi** [comment]
1,I mean a html comment: 

    
2,Yes.

**Comment by Keats** [comment]
Something like that should be its own crate (`minify_html` or similar) so it can be used with html coming from any sources (tera, handlebars, maud etc)

**Comment by Keats** [comment]
Closing this as I don't think it should be part of Tera itself as mentioned
