### ISSUE TITLE
Support Global Functions

### ISSUE THREAD

**Issue by SergioBenitez** [Keats/tera#102]
Tera doesn't appear to support [filter sections](http://jinja.pocoo.org/docs/dev/templates/#id11) at the moment. It's an important feature, especially for things like form helpers. Consider supporting them.

**Comment by SergioBenitez** [comment]
An alternative is to support global macros (in the global namespace) that can be added via a call to `Tera`.

**Comment by Keats** [comment]
Do you have examples for form helpers? I don't think I've used those before. 
The one linked should be fairly simple to implement but those filters only apply to strings right?

**Comment by SergioBenitez** [comment]
See the `form_tag` helper in [Rails](http://guides.rubyonrails.org/form_helpers.html).

**Comment by Keats** [comment]
That looks like macros calls rather than filter sections indeed. I don't think I want to allow global macros as magically loading macros is too implicit for my tastes, I want to know where the macros are coming from

**Comment by SergioBenitez** [comment]
In _every_ language there is a global namespace of some sort. There's no reason not have a global namespace for macros here, too. If the macro doesn't have a namespace, then it's coming from the global or local namespace. I don't think there's much magic in that reasoning.

**Comment by Keats** [comment]
I agree with some kind of global namespace, like the one for filters. 
I'm not planning to make anything of the sort for macros though, I'll keep the issue open as actual filter sections might be a wanted feature

**Comment by SergioBenitez** [comment]
That seems arbitrary and inconsistent. Why do filters get a global namespace but not macros? What's the fundamental difference between them that justifies this?

**Comment by Keats** [comment]
I don't want macros to be global since that would be terrible in terms of UX in my opinion. 

You're extending something like `flask-admin` and create a macro called `input` for your own code. What happens if the `admin` template were also defining an `input` macro that was used everywhere, which one gets used? You'd still need some kind of namespace to resolve that.
The same could happen with filters but it's much less likely that a filter like `length` gets redefined vs creating a `input`, `button` macro.

Overall, macros are about being DRY and explicit (vs what other template engine would do and just `include` another template) and making them global would go against that (again, imo).

**Comment by SergioBenitez** [comment]
I'm not advocating for _no_ namespace, I'm advocating for the presence of a global one. I appreciate that you want namespacing in general, I agree with that. But I don't see a reason to lack a global namespace. The resolution for the scenario you proposed is obvious, and it's already handled by Tera today: `input` would be the globally defined macro, and `self::input` would be the locally defined macro. You could also easily implement shadowing, where the local namespace trumps the global namespace every time so that `input` would always refer to the locally defined version first and fallback to the globally defined version.

I find it surprising that you think this is bad UX. This just about how function naming works in every major programming language.

**Comment by Keats** [comment]
In which language do users defined functions become global (other than JS without modules) and can be used without importing them or the module containing them?

**Comment by SergioBenitez** [comment]
I didn't say that user defined functions become global. I said that there is a global function namespace. Rust and Haskell, for instance, use the `prelude` to define global items. Rust doesn't have global functions, but it does have global macros, like `println`, which are function-like. In Python, for instance, the `print` function is global, among [many others](https://docs.python.org/2/library/functions.html). Other languages, Ruby, JavaScript, PHP, do something similar. In fact, C/C++ are just about the only languages I can think of that doesn't have function-like items in the global namespace.

**Comment by Keats** [comment]
Ah global functions are something different (in my mind) and is how the first version of filters were implemented.

I will most likely add it back at some point with signatures like `fn(args: HashMap<String, Value>) -> Result<String>`, to fit for example the `url_for` in flask.
I didn't need that yet so haven't got to it yet but that should be coming. They will be different from completely separate from macros though

**Comment by Keats** [comment]
Global functions are in 0.10.4
