### ISSUE TITLE
Getting "context isn't an object" error when passing &Vec<T> as context

### ISSUE THREAD

**Issue by SilverWingedSeraph** [Keats/tera#110]
I have a `Vec<QuoteTemplateContext>` where `QuoteTemplateContext` is 

```
#[derive(Serialize)]
struct QuoteTemplateContext {
    quote: String,
    author: String,
    source_text: String
}
```
I can render templates whose context is a single `QuoteTemplateContext`, but when I pass an `&Vec<QuoteTemplateContext>` I get an error saying:

`Failed to value_render 'list.html.tera': context isn't an object`

What does this mean? In this context, what is an object?

For reference, my target template is this:

```
{% extends "layout.html.tera" %}
{% block content %}
{% for quote in quotes %}
<div class='quote-container'>
  <blockquote>{{quote.quote}}</blockquote>
  <br /> <strong>{{quote.author}}</strong> ({{quote.source_text}})
</div>
{% endfor %}
{% endblock content %}
```

**Comment by Keats** [comment]
Sorry for that :(

Is https://github.com/Keats/tera/commit/eb8a8d9ba2d83a603199752d4279484bab780175 better?

**Comment by SilverWingedSeraph** [comment]
Yeah, that seems a whole lot clearer. Thanks so much!
