### ISSUE TITLE
`add_template` and `add_templates` are confusing

### ISSUE THREAD

**Issue by SergioBenitez** [Keats/tera#111]
The `add_template` and `add_templates` are confusing and error-prone. First, the documentation isn't clear what the arguments are/should be. But I won't go into this as I think the methods should be completely different.

I propose that the `add_template` method have the following signature:

```rust
fn add_template<P: AsRef<Path>>(&mut self, name: &str, path: P) -> Result<()>;
```

where `path` is the full path to the file. Tera should read the file, just like it does in `new`.

So, why this API? First, because reading a template file is not something the client should typically be doing. Maybe a different method, `add_raw_template` can be added to handle this case. But the default should be to read from a file. Second, the present API essentially forces you to use the filename as `name`. If it is not used as `name`, autoescaping isn't done since Tera doesn't know the path. Autoescaping should depend on the filename, not on the template's name.

Accordingly, the `add_templates` function should have the following signature:

```rust
fn add_templates<P: AsRef<Path>>(&mut self, templates: &[(&str, P)]) -> Result<()>
```

**Comment by Keats** [comment]
They were meant more for debugging, I should have probably added a `#[doc(hidden)]` on them.

In practice, I don't think people would want to add template using it (or at least I don't see the usecase).

Let's define the usecase first, what's yours? Extending an existing Tera instance like an admin for example?
If that's the case, I had in mind a `extend(self, glob) -> Tera` method that could be called on a pre-filled Tera instance offered by a framework like Rocket or something else. It could be used like:

```rust
let tera = admin.tera.extends("templates/**/*")
```

Is it another usecase?

**Comment by SergioBenitez** [comment]
I simply need to register a template via a path. Registering templates via a glob is not flexible. It leads to code duplication, which results in error-prone code. I'm already using the `register_template_files` method from #112  [here](https://github.com/SergioBenitez/Rocket/blob/master/contrib/src/templates/tera_templates.rs#L31).

**Comment by Keats** [comment]
I renamed `add_templates?` but am not convinced about using a name other than the filepath for a template name.

Your own testcases show that it can create conflicts https://github.com/SergioBenitez/Rocket/blob/master/contrib/src/templates/mod.rs#L313-L314, rename the first line to just `dir/index.html` and you get a silent error that is annoying to debug

**Comment by SergioBenitez** [comment]
I don't think those test cases show anything that you're implying. What conflict? What silent error?

Being able to name my template whatever I want is already possible with Tera: I just simply name my files whatever I want. This is just making it easier, and more important, more secure. Furthermore, this is the way other template systems work, and so I'm unsure about why you want to go against the grain here.

I did not foresee this being controversial. Why would you want to stifle flexibility because of an arbitrary decision?

**Comment by Keats** [comment]
> What conflict? What silent error?

I have `index.html` and `index.html.tera` in the same folder. I do `{% include "index" %}` in another template while using Rocket, what happens? 
That issue can be solved by checking if a template already exists before that line  https://github.com/SergioBenitez/Rocket/blob/master/contrib/src/templates/mod.rs#L254 (or adding that check in Tera), otherwise the second `insert` will overwrite the first template silently.

It is not that controversial but I want to explore stuff like https://github.com/pallets/jinja/blob/master/jinja2/loaders.py before settling on `add_X` methods to avoid making several breaking changes if I find the loader approach to be better in the end

**Comment by SergioBenitez** [comment]
Tera templates in Rocket must end with .tera, so there's no conflict there. You could, however, have two templates with different secondary file extensions and get the behavior you're describing. Rocket should be checking and emitting a warning in this case. 

I personally dislike the loading class approach. It seems wholly unnecessary. Adding templates via path and contents, the latter specifically, gives you all of the power you need in what I believe is a much simpler package. I don't want to have to create an entire structure just to load templates. I just want to call a method. 

I'll be releasing the next version of Rocket in the next week or so, and so I'm hoping this change will be in by then. I think it's an entirely sound API choice, and am still rather confused about your hesitation towards including it. This API is entirely unlikely to go away; folks will always need to be able to load templates from a file path. Doing it in the python way doesn't fit well with Rust, and it is bound to be less flexible and more work to implement with.

**Comment by Keats** [comment]
The`add_file_template{s}` are completely ok in my mind, the renaming that you want to do at the same time less so. I expect the file path to be the canonical name and dont want to change that in Tera itself.
The plan would be:

1. Add the `add_file_template{s}` that add a file content using their path and only that
2. Figure out how to make your usecase of removing the extension work. Could be by exposing the `build_inheritance_chains` to the public and letting you modify the name of the templates directly inside the Tera instance (outside of Tera)

I'm on holiday until the end of the month though so don't expect too much progress on that until February but I can still review/merge stuff in the mean time, just not code too much
