### ISSUE TITLE
Don't use relative names in macro

### ISSUE THREAD

**Issue by kriomant** [Keats/tera#115]
`compile_templates` macro shouldn't require importing `tera::Tera` type, but use [$crate variable](https://doc.rust-lang.org/beta/book/macros.html#the-variable-crate) instead.

**Comment by LFalch** [comment]
There's a similar problem with the `try_get_value` macro: It requires `serde_json` to be part of the project.

**Comment by Keats** [comment]
On holiday right now but I'd welcome a PR!
