### ISSUE TITLE
Included templates don't evaluate "extends" directives

### ISSUE THREAD

**Issue by robojeb** [Keats/tera#117]
If you include a template which extends another template, the extension element doesn't get evaluated. 

I don't know if this is expected behavior, or even desired behavior but there are situations where it is useful.

For example I have a navigation bar, most of the bar is repeated boiler plate and I just want to place different button elements inside the bar. 
I then include the navigation bar in the pages I want it to exist in. 

Unfortunately if you include a template which itself extends another template only the raw HTML gets added, it doesn't evaluate the extension.

This isn't hard to work around but reduces the ability to eliminate boilerplate.

**Comment by Keats** [comment]
That's intended, `include` is only there for including basic files, macros should be used for anything more complex. Any reasons the navigation bar can't be written as a macro?

**Comment by robojeb** [comment]
I think I could do that, so long as I could pass lists of objects intro macros statically.

Is a thing like this possible 
```
{% macro base(elements, active, user) %}
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top" style="background-color: #2e4482;">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navHeader" aria-controls="navHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">
    </button>
    <a class="navbar-brand" href="/">
        Kessler Git
    </a>

    <div class="collapse navbar-collapse" id="navHeader">
        <ul class = "navbar-nav mr-auto">
            {% for elem in elements %}
            <li class="nav-item"> |
                <a class="nav-link {% if active == elem.id %}active{%endif%}">{{elem.name}}</a>
            </li>
            {% endfor %}
        </ul>
        <ul class = "navbar-nav navbar-right">
        {% if user %}
            <li class="nav-item">
                <a class="nav-link" href="#">{{user.name}}</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link active" href="/login"> Login </a>
            </li>
        {% endif %}
        </ul>
    </div>
</nav>
{% endmacro base %}
```

Then called like
```
navbar::base(elements=[{"id": "home", "name": "Home", "link": "foo"}], ...)
```
I can't seem to get it to work. I keep getting an error on the opening paren when I call the macro

**Comment by Keats** [comment]
That's not supported yeah. Are the elements completely dynamic or do you have role/state (ie navbar ). 
If it isn't dynamic (which I guess it isn't since you can hardcode it in the template), you could pass the current state and let the macro deal with adding the right elements for each state.
Ie:
```jinja2
{% macro base(state, active, user) %}
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top" style="background-color: #2e4482;">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navHeader" aria-controls="navHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">
    </button>
    <a class="navbar-brand" href="/">
        Kessler Git
    </a>

    <div class="collapse navbar-collapse" id="navHeader">
        <ul class = "navbar-nav mr-auto">
            {% if state == "loggedin" %}
                   {{ self::nav_item(name="home", link="foo", active=active=="home") }}
                   {{ self::nav_item(name="another", link="bar", active=active=="another") }}
            {% else %}
                    ...
            {% endif %}
        </ul>
        <ul class = "navbar-nav navbar-right">
        {% if user %}
            <li class="nav-item">
                <a class="nav-link" href="#">{{user.name}}</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link active" href="/login"> Login </a>
            </li>
        {% endif %}
        </ul>
    </div>
</nav>
{% endmacro base %}
```

where `nav_item` would be another macro

**Comment by Keats** [comment]
@robojeb is that working or still an issue?

**Comment by Keats** [comment]
Closing as that's not a feature I want to implement. Let me know if my solution above doesn't work
