### ISSUE TITLE
Update to serde 0.9

### ISSUE THREAD

**Issue by Keats** [Keats/tera#119]
Quite a few changes to do there:

 - `to_value` returns a Result instead of a value but we can unwrap in most cases in Tera, I don't think there is a place where we are using it that can fail
 - removal of `Value::{i64, u64, f64}` for a `Value::Number`

**Comment by dtolnay** [comment]
Rocket is going to want this. :pray:

**Comment by Keats** [comment]
@dtolnay can you expand a bit what can fail from `to_value`? https://docs.serde.rs/serde_json/value/fn.to_value.html

I can propagate the error almost everywhere I use it but returning a result for `Context::add` makes it less nice than before so I'm thinking of unwrapping the `to_value` call, would that be a terrible idea?

**Comment by dtolnay** [comment]
Sure, here are two examples. If it has not caused problems so far then just unwrap - that is equivalent to what it was doing before.

```rust
extern crate serde_json;

use std::collections::BTreeMap;
use std::ffi::OsStr;
use std::os::unix::ffi::OsStrExt;
use std::path::PathBuf;

fn main() {
    // path contains invalid UTF-8 characters
    let non_utf8_path = PathBuf::from(OsStr::from_bytes(b"\x88"));
    println!("{}", serde_json::to_value(&non_utf8_path).unwrap_err());

    // key must be a string
    let mut non_string_keys = BTreeMap::new();
    non_string_keys.insert(vec![0], "v");
    println!("{}", serde_json::to_value(&non_string_keys).unwrap_err());
}
```

**Comment by Keats** [comment]
Thanks, #123 should work, I'll have another look tomorrow

**Comment by SergioBenitez** [comment]
Can we get a new release with this change if it's ready?

**Comment by Keats** [comment]
Probably tomorrow, in planes all day today

**Comment by Keats** [comment]
0.7.0 published
