### ISSUE TITLE
Undefined template vars cause rendering error

### ISSUE THREAD

**Issue by vezult** [Keats/tera#120]
Unlike jinja2 and django templates, it seems that tera will fail to render a template if a referenced var is undefined in the given context.

I fine it quite inconvenient to have to wrap all template vars which I do not *always* want to pass in {% if var_name %}{{ var_name }}{% endif %}. Could we at least have a flag we can optionally pass to render which makes the renderer ignore undefined vars?

**Comment by Keats** [comment]
That's something I want to change but keep forgetting to do it, thanks for opening an issue.

In short wht needs to be done:

- instead of erroring when rendering a variable, return `""`
- if variable is unknown in a conditional, return an error (current behaviour)
- in forloops, replace the variable with `[]`.

We could also add the `else` from Jinja2 to the forloop (http://jinja.pocoo.org/docs/dev/templates/#for) to render a body when there the array is empty or undefined.

This is fairly easy to add, I can help you for a PR or I'll do it during the weekend/next week

**Comment by Keats** [comment]
@vezult are you working on that? otherwise I'll do it tomorrow

**Comment by vezult** [comment]
On Sat, Jan 28, 2017 at 09:02:02AM -0800, Vincent Prouillet wrote:
> @vezult are you working on that? otherwise I'll do it tomorrow

I was going to. I'm not (yet), all that familiar with rust, or this
code base, but it seems fairly simple. My first pass was to return
Err("message") in the inline find_variable() func, rather than
bail!ing.

This causes test_error_render_field_unknown to fail, since we no
longer bail on that. So I need to move that to a test we expect to
succeed.

Testing:

{% if hey < 1 %}...

seems to indicate that a context entry still fails if the
reference is in an expression, but in this case, due to the
variable not containing a number. I've not done any broader testing
than that yet.

Anyway, that's as far as I've gotten at the moment. Like I said, I'm
still learning, so this just seemed like a fairly easy thing to work
on. If you're in a hurry, feel free to fix it. Otherwise, I'd still
like to work on it a bit.

**Comment by Keats** [comment]
`bail!` actually expands to `return Err`: https://github.com/brson/error-chain/blob/master/src/lib.rs#L601-L608

I had a look at the code and it's bit less evident than I thought if we want to keep errors in some cases (namely math and logic nodes), I'm tempted to do a PR and walk you through it if that's ok?

**Comment by vezult** [comment]
On Sat, Jan 28, 2017 at 09:20:07PM -0800, Vincent Prouillet wrote:
> `bail!` actually expands to `return Err`: https://github.com/brson/error-chain/blob/master/src/lib.rs#L601-L608
> 
> I had a look at the code and it's bit less evident than I thought
> if we want to keep errors in some cases (namely math and logic
> nodes), I'm tempted to do a PR and walk you through it if that's 
> ok?

Yeah, that's fine.

-davidc

**Comment by Keats** [comment]
It's in #125

**Comment by SergioBenitez** [comment]
Please don't make this change! This is very, very error prone! This essentially makes an undefined variable a silent error. At present, if you mistakenly forget to include a variable, rendering fails. With this change, rendering will just work! This goes against Rust's philosophy of always checking conditions unless explicitly disregarded.

I don't believe it is cumbersome to use ` {% if var_name %}{{ var_name }}{% endif %}`, but some might differ. Might I propose that a function simply be added to Tera, say `try`, that results in an empty string if the variable is undefined? For instance, you could do `{{ try(var_name) }}`. This makes it explicit that you're okay with inserting an empty string if the variable is undefined. You could even go farther an add extra syntax: `{{ var_name? }}` or `{{ var_name! }}` or `{{! var_name !}}`.

**Comment by vezult** [comment]
On Mon, Jan 30, 2017 at 01:24:31PM -0800, Sergio Benitez wrote:
> Please don't make this change! This is very, very error prone! This
> essentially makes an undefined variable a silent error. At present,
> if you mistakenly forget to include a variable, rendering fails. With
> this change, rendering will just work! This goes against Rust's
> philosophy of always checking conditions unless explicitly
> disregarded.

I suppose it's worth asking a question of intent. Is Tera intended to
be a template system that embodies rust philosophy, or an
implementation of a familiar template language, in rust?

There are a variety of projects out there which provide, or aim to
provide type-safe templating, or otherwise very closely align with
rust philosophy.

I'm interested in Tera specifically because it is very similar in
syntax and behavior to existing template systems (DTL, jinja).

> 
> I don't believe it is cumbersome to use
>
> `{% if var_name %}{{ var_name }}{% endif %}`
>
> but some might differ.

I'm clearly one who does find it cumbersome, but I also understand the
value of being explicit. Either way, it's not a deal-breaker for me,
but it would increase friction for those moving from the templating
systems I mentioned.

>
> Might I propose that a function simply be added to Tera, say `try`,
> that results in an empty string if the variable is undefined? For
> instance, you could do `{{ try(var_name) }}`. This makes it explicit
> that you're okay with inserting an empty string if the variable is
> undefined. You could even go farther an add extra syntax:
>
> `{{ var_name? }}` or `{{ var_name! }}` or `{{! var_name !}}`.

Again, I think it's important to understand what the Tera's goals are.
The syntax above starts to depart significantly from DTL or jinja.
Perhaps that doesn't matter to Tera, but knowing clearly what its goals
are would clarify what is or isn't possible.

{% maybe var_name %}

or something? The use of "try" looks like error handling (eg
try/catch, try/except).

Anyway, that's my $0.02.

-davidc

**Comment by Keats** [comment]
How about adding a flag to Tera that defaults to error like right now and users can do `Tera::disable_error_on_undefined()` to get the behaviour in that PR?

**Comment by SergioBenitez** [comment]
I think it's a bit weird for the engine to do different things based on whether a call was made or not. It might make more sense to have a general `Config` structure that users can pass in. But in any case, I'm for any solution that keeps the current behavior as the default. Personally, I don't think there's any merit to enabling this at all; why can't the user pass in an empty string themselves?

**Comment by dswd** [comment]
This topic might affect more aspects of rendering too. In my PR #128 I am handling any filter return value (for a filter section) that is not a string specially and serialize it to a string. A strict mode might want to throw an error instead.

**Comment by vezult** [comment]
On Mon, Jan 30, 2017 at 02:00:27AM -0800, Vincent Prouillet wrote:
> It's in #125 

OK, so I'm an idiot, but is there anyway to checkout your changes
locally?

From just reading through, it appears like it should work like I
would have expected.

-davidc

**Comment by Keats** [comment]
Ah sorry I missed the last comment.
If you clone the repo, you should be able to checkout the branch directly (branch name has a typo).
```
git fetch origin
git checkout -b undefiend origin/undefiend
```

After some more time with Tera, I'm not convinced this mode should be added after all though.

**Comment by Alex-PK** [comment]
I gave it a try and implemented a `default()` filter (like in twig). It would work like this:

```
{{ nonexistantvar | default(value="default value") }}
```

The implementation is quite simple, but presumes that the `value` passed to `default()` is `Value::Null`, and the current implementation panics in `nonesistantvar` is not in context, with no chance to get to the filter.

So, what I am proposing is to return `Value::Null` if the var is not defined.

**Comment by Keats** [comment]
I think `{% if nonexistantvar %}{{ nonexistantvar }}{% else %}default value{% endif %}` would be the recommended way, you can make a macro to avoid the repetition.
An alternative would be to treat a `default` filter differently and not error if a default is given.

I quite like getting errors instead of having silent nulls so it's very unlikely that my PR on that will get merged

**Comment by Keats** [comment]
(Closed my PR)

Going to close that issue as well, we can start another one if to discuss a `default` filter if wanted.

**Comment by tonyhb** [comment]
For posterity, even though this is a years old issue, I added a mode to tera which ignores undefined variables without erroring in a separate branch.  It adds an option to the AST processor which returns an empty value every time we inspect an undefined ident, and ignores loops on undefined variables.

Here are the relevant commits:

https://github.com/tonyhb/tera/commit/92f6a62ec0aa4528e50a6f6fe5f1dd5cc4aac449
https://github.com/tonyhb/tera/commit/844e4ea26a66d4361d6ef44a912e4b85dfeaefc4

I know this is not a goal of Tera but wanted to post in case it's helpful to anyone else :)
