### ISSUE TITLE
Expose variables used inside a template

### ISSUE THREAD

**Issue by mre** [Keats/tera#121]
Is there an easy way to get the variables used inside a template?

E.g. given the following template
```
Name: {{user.name}}
Password: {{user.password}}
Something: {{something_else}}
```
I'd like to get the set of variables, e.g. {'user.name', 'user.password', 'something_else'}.

Maybe this could be done by analyzing the template AST.
If this part of the engine can not be exposed for any reason, maybe we could have a simple helper function that returns this data. It could be part of an optional `debug` mod which does not interfere with normal usage.

**Comment by Keats** [comment]
Do you only want the variable names used in the file itself or the whole processed template (ie including parents, blocks etc)? Exposing the AST itself is not a problem

**Comment by mre** [comment]
Good point! Err... for my use-case it would be enough to collect only the variables from the file itself, but getting all variables would of course be more generic.

On the other hand my request might be so specific that maybe it's better to expose the AST itself and provide specific functionality - like getting all tags - into a separate "tera-debug" crate. This way we could achieve better separation of concerns and tera would only contain the core engine.

**Comment by Keats** [comment]
Can you have a look at #122 for exposing the AST?

**Comment by mre** [comment]
Looks good! Thanks 😃.

I've tried extracting the variable names with the following test code:

```rust
let mut tera = Tera::new("*").unwrap();
tera.add_raw_template("test.tpl",
                      "{{user.name}} is {{user.age}} years old. He feels {{feeling}}")
    .expect("Invalid template syntax");

let mut variables: Vec<String> = Vec::new();
for node in tera.get_template("test.tpl").unwrap().ast.get_children() {
    if let ast::Node::VariableBlock(box ast::Node::Identifier { name, .. }) = node {
        variables.push(name)
    }
}
assert_eq!(variables, vec!["user.name", "user.age", "feeling"])
```

Since `ast::Node::Identifier` is boxed, I needed to use a nightly feature to extract the actual variable name:

```rust
#![feature(box_syntax, box_patterns)]
```

Maybe there's another, more obvious, solution that I have overlooked.
Could I avoid the pattern matching if the fields of `ast::Node::Identifier` were public?

**Comment by Keats** [comment]
No need to use any features. 
I've updated the `ast` example to show a very basic/incomplete way of getting the identifiers:
https://github.com/Keats/tera/pull/122/commits/0a3ea5ebe93c2341e24867cee667152215194fd8

**Comment by mre** [comment]
Yup, you're right. Works like a charm!
Thank you very much for the quick addition @Keats. 🐇
