### ISSUE TITLE
Merge 2 Context Structs

### ISSUE THREAD

**Issue by sklopi** [Keats/tera#124]
For me it would be very useful, to be able to merge 2 Context structs, where already defined values get overwritten. If there is any interest in this feature i would like to implement this feature.

**Comment by Keats** [comment]
Something like `Context::extend(&mut self, &Context)`? Go for it

**Comment by sklopi** [comment]
`extend` might be better, because that's how it is called in various other (non-rust) libraries.
This would also represent that existing values can be overwritten.
