### ISSUE TITLE
Allow comments before extends tag

### ISSUE THREAD

**Issue by dswd** [Keats/tera#129]
Currently no tags can precede an extends tag, according to the grammar. For most tags, this makes perfect sense as you do not want extends tags nested in if blocks for example. But I think comments before the extends tag are safe. 

For my use case it is important to have some header data in comments right at the beginning of the template. So it would be great if tera could allow for comments preceding the extends tag.

**Comment by Keats** [comment]
I'm not 100% sure about that, can you check an arbitrary line like the second one? What's the usecase exactly?

**Comment by dswd** [comment]
I am working on a static page generator based on tera. For some page attributes like title, date, tags and so on I need a way to set them in the file header (to grab them from there and make them available to the base template in the context as well as to other files as a site structure).

The reason why I dont want to scan the whole file for e.g. `{## NAME=VALUE ##}` is that I want to keep the ability to embed those comments in verbatim blocks where they should not be evaluated but instead be printed verbatim. To avoid getting those comments too, I would have to parse the whole document with a parser similar to tera. However, I can avoid this by mandating that comments must be the first tags of the file so that no verbatim block can start before them.

**Comment by dswd** [comment]
Alternatively I cloud add a front matter to the template files that is separated from the template code by some simple pattern, e.g. `---`. But then the templates will no longer pass and I would need a way to register templates as strings (instead of files) in a `Tera` instance.

**Comment by Keats** [comment]
Ah that's interesting, you're putting the metadata in the template itself rather than in a markdown file or similar?

For the `Tera::add_raw_templates`, I wasn't sure about the API for that yet so it's undocumented for now. I don't think it's going to change much though

**Comment by dswd** [comment]
Yes, my idea is to support markdown and tera templates and to have a similar kind of front matter for both of them. This makes it possible to use certain attributes (e.g. date and title) in listings. In markdown files, the front matter also defines a tera template that is used to provide the layout. If you have more questions about that project, please ask me.

**Comment by Keats** [comment]
Yeah if you have a repo that would be interesting. 
I started a static site generator some time ago as well (https://github.com/Keats/gutenberg) but didn't get very far.

**Comment by Keats** [comment]
@dswd can this be closed? `Tera::add_raw_templates` should be public in the docs in the next release

**Comment by dswd** [comment]
I still think comments should be able to precede an extends tag but it is no longer important in my use case. So close it if you want to.

**Comment by Keats** [comment]
If you can do a PR on the `next` branch, i'll take it

**Comment by Keats** [comment]
This is now allowed on 0.11.0-beta
