### ISSUE TITLE
Escaping Braces

### ISSUE THREAD

**Issue by SergioBenitez** [Keats/tera#135]
Can braces be escaped? I know that I can use `raw`, but that doesn't suffice when I want to mix variables with escaped braces such as below where `name` is in the context:

```jinja2
{% raw %}
    {{ hello }} {{ name }}
{% endraw %}
```

I'm looking for something like:

```jinja2
\{\{ hello \}\} {{ name }}
```

**Comment by Keats** [comment]
No way to do that no, is it not possible to do `{% raw %}{{ hello }}{% endraw %} {{ name }}` in your case?

**Comment by SergioBenitez** [comment]
No, the actual use case is more complex. It looks like:

```jinja
<pre>
  {{
      ${{ bar }}
      something {{ foo }} blah {{ variable }}
  }}
</pre>
```

where only `variable` is actually in the context.

I think a nice way to work around this is to allow the brace type to be changed in a small block. So something like:

```jinja
{% raw '[' %}
    {{ hello }} [[ name ]]
{% endraw %}
```

Where `[[ name ]]` is rendered by Tera.

**Comment by SergioBenitez** [comment]
P.S: Handlebars uses `\{{ var }}` (a single backslash) to escape braces.

**Comment by Keats** [comment]
The other way to do in Jinja2 is to do `{{ "{{ var }}" }}` which wasn't working until 0.7.2 which I just released.

There has been some people wanting another way to escape than `raw` and the string printing above in Jinja2 but it never felt that needed (https://github.com/audreyr/cookiecutter/issues/11)

**Comment by Keats** [comment]
Can this be closed?

**Comment by SergioBenitez** [comment]
Sure, if `{{ "{{ var }}" }}` works as expected!

**Comment by Keats** [comment]
Should be ok but do re-open if you have an issue with it!

**Comment by freinn** [comment]
Hi @Keats I'm using Tera 0.7.2 because is the one that comes with Rocket 0.2.3, and this is not working for me.

Autoescaping is enabled in tera globally (didn't touched that because I can't in the present moment) and my template is this:

``
{% extends "blog/blog_base" %}

{% block content %}

    <h1>{{ titulo }}</h1> 

    {{ "{{ contenido }}" }}

    <br /><br />
    <a href="/blog">Blog</a>
    <br />

{% endblock content %}

{% block gototop %}
    {{ super() }}
{% endblock gototop %}
``

But it simply displays *{{ contenido }}* in the HTML output, when I want the variable value without processing.

**Comment by Keats** [comment]
You want `{{ contenido | safe }}` if `contenido` contains HTML. `{{ "{{ contenido }}" }} will just render the string `{{ contenido }}`.
That made me realise that `safe` is not mentioned in the docs, I'll add it
