### ISSUE TITLE
HashMap support?

### ISSUE THREAD

**Issue by mre** [Keats/tera#136]
Does tera have support for `HashMap`s in templates?
Something like this:

```rust
{% for k, v in mymap %}
  {{ k }} is {{ v }}
{% endfor %}
```

Was looking around for an example but couldn't find anything. That's why I opened up an issue.
I could really use this feature right now. 😁 

As a workaround I could create an array and put the value of `k` into each array element. But that feels a bit dirty.

**Comment by clarcharr** [comment]
I believe that values are coded as `serde_json::Value` which does include maps. But I'm not sure if they're implemented in for loops yet.

**Comment by Keats** [comment]
This is currently not supported, I'll add it in 0.8

**Comment by Keats** [comment]
It's in the `next` branch if you want to try it. Since serde only has `Object`, that means you can also iterate on struct.

Does the order matter in your case? By default serde doesn't preserver the order but has a `preserve_order` feature flag that I haven't tried myself

**Comment by mre** [comment]
Thank you very much @Keats! I'll give it a shot 😃. The order is not important in my case.

**Comment by mre** [comment]
Just wanted to report back that everything works as expected on my side. Good job!

**Comment by Keats** [comment]
0.8 released so you can use that directly from crates.io now!

**Comment by mre** [comment]
Thanks @Keats  🎉

**Comment by xiuno** [comment]
How to get one value from map ?

like this : 
```
{{ mymap.get(k) }}
```

**Comment by Keats** [comment]
{{ mymap[k] }} should work
