### ISSUE TITLE
Does Tera eat PHP code?

### ISSUE THREAD

**Issue by freinn** [Keats/tera#151]
I know is tasty, but I'm creating a blog and when my template contains php code for the reader learning, Tera eats it even in a safe block!

{{ contenido | safe }}

and when I pass some String that contains:

```
<p>
<?php

function tirarDadosBT($carasDado, $objetivo, $tiradas, $suma) {
  if ($suma == $objetivo) {
    print_r($tiradas);
  } else {
    $tiradasAnteriores = $tiradas;
    for ($dado1 = 1; $dado1 < ($objetivo / 2) + 1 && $dado1 <= $carasDado; $dado1++) {
      for ($dado2 = 1; $dado2 < $objetivo - $dado1 + 1 && $dado2 <= $carasDado; $dado2++) {
        $tiradas = $tiradasAnteriores;
        $tiradasActuales = array(); // es como hacer un clear
        $nuevaSuma = $suma + $dado1 + $dado2;
        if ($dado1 <= $dado2 && $nuevaSuma <= $objetivo) {
          $tiradasActuales[] = $dado1;
          $tiradasActuales[] = $dado2;
          array_push($tiradas, $tiradasActuales);
          tirarDadosBT($carasDado, $objetivo, $tiradas, $nuevaSuma);
        }
      }
    }
  }
}

// recibe las caras del tipo de dado que usaremos y el valor objetivo de la suma de números de caras
function tirarDados($carasDado, $objetivo) {
  $tiradas = [];
  echo "Formas posibles de tirar dos dados para obtener " . $objetivo . "\n";
  tirarDadosBT($carasDado, $objetivo, $tiradas, 0);
}

tirarDados(6, 6);
</p>
```

My HTML output simply displays nothing. When I put C++ code, it works fine. PHP lives matter!

**Comment by Keats** [comment]
Can you create a repo reproducing that issue? I don't see how that could fail.

**Comment by freinn** [comment]
@Keats you have a private invite to my repo.

**Comment by Keats** [comment]
Sorry, not going to create a bitbucket account for that.
I tried with your php code above in Tera and it renders just fine, I'm guessing the issue is a bug in how you get the data in the context before Tera or there's a bug with the context switching if you have forloop/blocks etc. Can you paste your full tera template?

**Comment by freinn** [comment]
it is now a github.com repo.

**Comment by Keats** [comment]
Tera renders it fine on my end, looks like it'an issue with the js lib used for highlighting that mess up somehow and insert everything in `<pre>`

**Comment by freinn** [comment]
JS highlighting was added after having this issue because I have to finish all I can in each moment. Do you see the whole PHP and C++ snippets or not?

**Comment by Keats** [comment]
Yeah I see all of it, the later half of the article being in a <pre> though

**Comment by freinn** [comment]
In chrome yesterday I couldn't see it all, I will try in a moment with another browsers. Please email me the generated HTML in your computer. You have my email because I've sent one email to you yesterday.

**Comment by freinn** [comment]
All of this

    </endl;></char></bool></char></char></bool></char></bool></endl;></vector></iostream>

Doesn't exist in my HTML source file. Maybe is my computer or bad installed OS, or maybe is Tera.

**Comment by freinn** [comment]
Not a Tera issue, was a PHP issue for including the *<?php* string. Sorry
