### ISSUE TITLE
Variable for current context

### ISSUE THREAD

**Issue by lukasschmelzeisen** [Keats/tera#160]
Is there a special variable for the current context, similiar to Handlebar's `{{ this }}`? If not, could you implement one?

To elaborate, something like this is needed if I don't know the key names in my context. As an example, consider a context where keys represent link targets and values link names for arbitrary list of links:

```rust
let mut context = Context::new();
context.add("https://github.com", "Github");
context.add("https://reddit.com", "Reddit");
```

Which then could be displayed using a template like:

```jinja
{% for target, name in this %}
  <a href="{{ target }}">{{ name }}</a>
{% endfor %}
```

**Comment by Eijebong** [comment]
`__tera_context` ? Is that what you're looking for

**Comment by lukasschmelzeisen** [comment]
No, `{% for key, val in __tera__context %}` gives an error for me. But I would be satisfied if it could be used in such a way. 

My actual use case for this is trying using a enum with struct variants as the template context. For an enum value like

```rust
enum MyEnum {
    VarA {
        value: String,
    },
    VarB {
        value: String,
    },
}

let my_enum = MyEnum::VarA { value: "my value".to_owned() };
```

[The serialization is:](http://play.integer32.com/?version=stable&mode=debug)
```
{"VarA":{"value":"my value"}}
```

In this case, I don't know how to access either the enum variant name nor its value.

**Comment by Eijebong** [comment]
Just use `{{ __tera_context }}` directly, I don't think you can use it as a hashmap.

I can't think of anything to help you in your use case though

**Comment by lukasschmelzeisen** [comment]
`__tera_context` can only be used to get a string representation of the current context for debugging. I don't see how it helps in my sitation.

**Comment by Keats** [comment]
There is no concept of `this` in Tera, you will need to put the urls in a Vec/array for the first post. I'm not planning to implement it either.
It could potentially be added as global function once global functions are in Tera like in http://stackoverflow.com/questions/3398850/how-to-get-a-list-of-current-variables-from-jinja-2-template but there definitely won't be a `this` keyword.

For your enum rendering, I can print enum variant name and value like so:

```rust
    let my_enum = MyEnum::VarA { value: "my value".to_owned() };
    context.add("enum", &my_enum);
```

```jinja2
    {% for name, val in enum %}
        {{ name }} {{ val.value }}
    {% endfor %}
```

**Comment by lukasschmelzeisen** [comment]
Yes, luckily workarounds exists. I was mainly looking for a nice syntax, but doing this via global functions is arguably better. As this is a WONTFIX, I guess we can close the issue.
