### ISSUE TITLE
Apply filter to "inline variable"

### ISSUE THREAD

**Issue by khorolets** [Keats/tera#166]
Hi! First of all thank you for your great work!

I guess this is a feature request or maybe a question.

I'm getting error if I try to apply filter like so:

```html
{{ "lowecase text" | upper }}
```

I wonder if it is possible to allow to do like the above. For now I've done the workaround by passing it through context.

Before you ask why on Earth I'm trying to use filters like so:

I've created the filter `range` to have a possibility to duplicate some parts of code, like so:

```html
{% for i in 5 | range %}
    {% include "repeat_block.html" %}
{% endfor %}
```

Thank you in advance!

**Comment by Keats** [comment]
Thanks for the kind words!

For this specific case of `range`, I think it will make more sense as a global function (not implemented yet, #102 ) where you could use:

```jinja2
range(max=5)
range(min=1, max=10, step=2)
range(max=5, inclusive=true)
etc
```
I think that would solve your issue better than applying filters in inline variables.

Global functions could also be used for things like [url_for](http://flask.pocoo.org/docs/0.12/api/#flask.url_for) but I didn't have the time and people asking for that.

It should be fairly easy to add though so I might work on it soonish

**Comment by khorolets** [comment]
@Keats Thank you, I agree. Somewhere in the issues, I saw you've mentioned that we can pass functions to context, but I didn't find the example in the docs, could you help me to find where can I look closer, I can make more use of functions in my project.

**Comment by Keats** [comment]
Where did you see that? It's not possible.

The best you can do right now is add filters to the Tera instance. And potentially soon add global functions to the Tera instance but you can't (and won't) be able to pass functions to a context.

**Comment by khorolets** [comment]
#23 But I guess the results of the investigation were unsuccessful. 

Thank you for the answers and your attention. Once more thank you for your great work, I hope I'll be able to contribute when I grow up with Rust.

Good luck!

**Comment by Keats** [comment]
Keeping it open so I don't forget it :)

**Comment by Keats** [comment]
`range` is in 0.10.4
