### ISSUE TITLE
Self namespace doesn't work for macros

### ISSUE THREAD

**Issue by phil-opp** [Keats/tera#167]
I'm running into [this assertion](https://github.com/Keats/tera/blob/master/src/render.rs#L480) when I try to define a macro in the same file.

I try to do something like this:

```jinja
{% macro post_link(page) %}
    <article>
        <h1 class="post-title"><a href="{{ page.path }}">{{ page.title }}</a></h1>
        {{ page.summary | safe }}
    </article>
{% endmacro post_link %}

{{ self::post_link(pages.1) }}
{{ self::post_link(pages.2) }}

```

**Comment by Keats** [comment]
Yeah, macros are meant to be put in a separated file and imported like https://github.com/Keats/tera/blob/master/tests/templates/use_macros.html

Not ideal but I should probably change the assertion and make it clearer in the docs.

**Comment by phil-opp** [comment]
Ok, it works from a separate file. However creating a new file seems a bit unnecessary when the macro is only needed for a single template file.

It also seems that [the README](https://github.com/Keats/tera#macros) is wrong:

> Do note that macros, like filters, require keyword arguments. **If you are trying to call a macro defined in the same file or itself, you will need to use the self namespace**.

**Comment by Keats** [comment]
Docs around macros are not very good yes.
You can use `self::` **only** in macros like in https://github.com/Keats/tera/blob/master/tests/templates/macros.html#L13

I'll update the docs tomorrow
