### ISSUE TITLE
Support filters in key/value for loops

### ISSUE THREAD

**Issue by dswd** [Keats/tera#171]
Example:
```
{% for key, value in var|filter(...) %}
...
{% endfor %}
```

Looking at your code it seems that this is simply an issue of changing the parser.

**Comment by Keats** [comment]
Yeah it's not hard to add, I just couldn't think of a usecase when I did it

**Comment by Keats** [comment]
@dswd do you want to do a PR for it?

**Comment by dswd** [comment]
I do not currently have time to dive into the tera code, sorry.

**Comment by Keats** [comment]
@dswd I can add it in the next version or the one after but I still can't come up with a good example, can you share one?

**Comment by dswd** [comment]
Sure, here you go: I have a list of entries (which are json objects) and want to map them by year so that I get a mapping where each key is the year and the data is a list of entries from that year. I can write a `by_year` filter that does this but I currently can not write `{% for year, entries in data|by_year() %}`

**Comment by Keats** [comment]
If you can try with the current Tera master, it should work.

**Comment by Keats** [comment]
It's in 0.10.6
