### ISSUE TITLE
CLI tool

### ISSUE THREAD

**Issue by nikolay** [Keats/tera#172]
It would be nice if we can use tera for DevOps tasks and have a CLI to expand templates into config files, etc.

**Comment by Keats** [comment]
It can be used in CLI as a library already. I don't see how to make it work as a direct CLI tool though, how would you specify the context?

**Comment by nikolay** [comment]
In my case, the environment variables, but it could be combined with a JSON source or multiple sources.

**Comment by Keats** [comment]
I see. That would be a separate tool though, not Tera itself. I don't have time to do it myself but it should be fairly easy

**Comment by W1M0R** [comment]
@chevdor made one here https://github.com/chevdor/tera-cli
