### ISSUE TITLE
Allow variable indexing in templates

### ISSUE THREAD

**Issue by Keats** [Keats/tera#173]
Such as `my_variables[0]` (equivalent to my_variables.0) or `my_variables["hello"]`  (equivalent to my_variables.hello). The advantage being the indexed version can contain fields that are not valid Tera identifiers, such as `posts/tutorials` for example.

Potential issues (some might be non-existent after trying it):

- chained indexing: `myvar["hey"][0]`
- variable in indexes: `my_var[config.home]`. Could be not allowed and recommend to use `my_var | get(key=config.home)` instead

That might be a breaking change and should only be done once Pest reaches 1.0

**Comment by bootandy** [comment]
Variables inside indexes might be difficult. For instance is the below going to resolve as 'hi' or 'there'?
```
strut S = {a:String, b:String}
context = {
  a: "b"
  v: S{a:"hi", b:"there"}
}

{{ v[a] }}

```

**Comment by Keats** [comment]
That would be resolved in 2 steps, the key being resolved first:

- a => "b"
- v["b"] => "there"

`{{ v["a"] }} -> "hi"`
`{{ v["b"] }} -> "there"`
`{{ v[a] }} -> "there"`
`{{ v[b] }} -> error, b is not in the context`

**Comment by bootandy** [comment]
First pass at this:
https://github.com/bootandy/tera/commit/a9dae544ae71fd3eebcfd5a5463d92488eb781ba
