### ISSUE TITLE
Calling global functions with no args

### ISSUE THREAD

**Issue by kardeiz** [Keats/tera#178]
On the README, there is an example:

    {% set my_var = global_fn() %}

However, it seems like Tera doesn't support calling global functions like this. It seems like I have to do:

    {% set my_var = global_fn(_="") %}

It would be nice if Tera supported calling global functions that don't expect args like this, but if this is not feasible the README should be corrected. 

This is on `0.10.5`.

Thanks!

**Comment by Keats** [comment]
Ah that's a bug, I'll fix it later today. Thanks for the report!

**Comment by Keats** [comment]
I pushed a commit to master that should fix it if you can have a look when you have time

**Comment by Keats** [comment]
It's in 0.10.6
