### ISSUE TITLE
Multiple inheritance is buggy

### ISSUE THREAD

**Issue by Keats** [Keats/tera#179]
`index.html`:
```html
{% block content %}
Index
{% endblock %}
```

`docs.html`:
```html
{% extends "index.html" %}

{% block content %}
  Docs
  {% block more_content %}
    MORE
  {% endblock %}
{% endblock %}
```

`page.html`
```html
{% extends "docs.html" %}

{% block more_content %}
  SINGLE
{% endblock %}
```

Output of page.html expected: `'\n  Docs\n  \n  SINGLE\n\n'`
Current output: it will try to render the `index.html` content block

**Comment by Keats** [comment]
Turns out the way inheritance is currently done is completely wrong...

**Comment by uniphil** [comment]
awesome fix! I ran into another multiple inheritance bug yesterday where

`bottom.html`
```jinja2
{% block pre %}{% endblock pre %}
{% block main %}{% endblock main %}
```

`mid.html`
```jinja2
{% extends "bottom.html" %}
{% block pre %}
this should appear in before the main stuff
{% endblock pre %}
```

`top.html`
```jinja2
{% extends "mid.html" %}
{% block main %}
the main stuff
{% endblock main %}
```

When rendering `top.html`, the block `pre` from `mid.html` was missing.

Adding
```jinja2
{% block pre %}{{ super() }}{% endblock pre %}
```

made it appear, but sort of defeats the point.

Is #180 likely to fix this, or should I open a new issue? I'd check whether it works on master, but I won't be back at that computer until Monday.

**Comment by Keats** [comment]
I just added a test for that case in https://github.com/Keats/tera/commit/38b9ba7e15e7c4b7c0ae66d74f3f2b7c849dbac6 and it seems to work fine on master
