### ISSUE TITLE
Allow variables set outside blocks to use in blocks and in the extended template

### ISSUE THREAD

**Issue by msarris** [Keats/tera#182]
It would be a nice feature to be able to set variables outside blocks and then to be able to use the values inside blocks. This currently results in an error.

Also the variables should also be available in the extended template. For example to add CSS classes to the body tag in the base template, or to set a page title.

**Comment by Keats** [comment]
> It would be a nice feature to be able to set variables outside blocks and then to be able to use the values inside blocks. 

Do you have a real example template that uses that? (can be jinja2/django/twig, no need to be tera)

**Comment by msarris** [comment]
This is something that I might do, in Twig for example:

```
# base
<!doctype html>
<html>
<head>
  <title>
    MySite
    {% if page_header is defined %}
      | {{ page_header }}
    {% endif %}
  </title>
</head>
<body>
  {% if page_header is defined %}
    <header>
      <h1>{{ page_header }}</h1>
     </header>
  {% endif %}
  <main>
    <div id="page-body">
      {% block page_body %}{% endblock page_body %}
    </div>
    <div id="page-sidebar">
      {% block page_sidebar %}{% endblock page_sidebar %}
    </div>
  </main>
</body>
</html>
```
```
# home
{% extends "base" %}

{% set page_header = "Homepage" %}
{% set is_admin = is_granted("ROLE_ADMIN") %}

{% block page_body %}
  Welcome to the {{ page_header }}

  {% if is_admin %}
    Stuff only for admins. 
  {% endif %}
{% endblock page_body %}

{% block page_sidebar %}
   Sidebar public content ...

  {% if is_admin %}
    Stuff only for admins. 
  {% endif %}
{% endblock page_sidebar %} 
```

**Comment by Keats** [comment]
Seems like something that can be added, i'll take a PR for that!

**Comment by bootandy** [comment]
Going to take a quick look at this as I'm curious. I think I've reduced it down to a simpler failing test referenced in the above commit.

**Comment by Keats** [comment]
@bootandy keep in mind this is a feature request so it's normal that the behaviour is currently "failing"

**Comment by Keats** [comment]
I agree with you @bootandy 
Closing this
