### ISSUE TITLE
Implement block("foo") function to retrieve block contents

### ISSUE THREAD

**Issue by msarris** [Keats/tera#183]
A nice feature would be to be able to retrieve the contents of a block via a function (`block()` for example). This would allow you to check if a block has any assigned contents, and to make decisions based on this (for example to show a sidebar or not).

This should also work with extending templates. You should be able to retrieve the block contents from the sub template in the base template.

```
# base.tera

{% block sidebar %}{% endblock sidebar %}

{% set sidebar = block("sidebar") %}

{% if sidebar != "" %}
    <div class="sidebar">
        {{ sidebar | safe }}
    </div>
{% endif %}
```

```
# sub.tera

{% extends "base" %}

{% block sidebar %}
    Some content ...
{% endblock sidebar %}
```

A good place to look how this works in the Twig templating library btw: https://twig.sensiolabs.org/doc/2.x/functions/block.html

**Comment by Keats** [comment]
I'm not sure I see the point to be honest, you have `super()` and can have nested blocks. You could have a `{% block sidebar-tweaks %}{% endblock sidebar-tweaks %}` in your `sidebar` block and just change that in the child template. You could also use a macro for the sidebar depending on how much stuff is changing.

**Comment by msarris** [comment]
I use it quite a lot in Twig. For example to also add classes to the body depending on whether a certain block has content. With the sidebar example I would add `with-sidebar` as a class to the body tag for example. That wouldn't be possible with a macro or just the blocks.

**Comment by Keats** [comment]
Hmm I'm still not sure I see where I would want (or have wanted) to use that feature so I'm thinking no.
 
I'll leave it open though in case people want to +1 or discuss about it
