### ISSUE TITLE
Panics (unwrap on None) when {% set x = 0 / 0 %}

### ISSUE THREAD

**Issue by kennytm** [Keats/tera#189]
Test case:

```rust
    assert_eq!(
        &Tera::one_off("{{ 0 / 0 }}", &Context::new(), false).unwrap(),
        "NaN"
    );
    println!("^ this one should be fine...");

    assert_eq!(
        &Tera::one_off("{% set x = 0 / 0 %}{{ x }}", &Context::new(), false).unwrap(),
        "NaN"
    );
    println!("^ but this one panics...");
```

**Expected:** `NaN` should be stored in `x` and printed out. Or at least, a `tera::Error` should be thrown stating that assigning from non-finite number is not supported at the moment.

**Actual:** Panics:

```
---- test_div_by_zero stdout ----
	^ this one should be fine...
thread 'test_div_by_zero' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:335
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   9: <core::option::Option<T>>::unwrap
  10: tera::render::Renderer::eval_expression
  11: tera::render::Renderer::eval_set
  12: tera::render::Renderer::render_node
  13: tera::render::Renderer::render
  14: tera::tera::Tera::render
  15: tera::tera::Tera::one_off
```

Note that [`serde_json::Number::from_f64`](https://docs.rs/serde_json/1.0.2/serde_json/struct.Number.html#method.from_f64) returns None if the input is non-finite (NaN, inf, -inf), so [`unwrap()` shouldn't be used](https://github.com/Keats/tera/blob/397fe36df6062b38a55872e799a32a1b2a44b12d/src/render.rs#L347). 

cc #45?

**Comment by Keats** [comment]
Thanks again, fixed in https://github.com/Keats/tera/commit/bc2ade03b2a3f1e44e8fc73816841237807cc289

**Comment by Keats** [comment]
In 0.10.7
