### ISSUE TITLE
`is` is not an expression

### ISSUE THREAD

**Issue by lifthrasiir** [Keats/tera#194]
Jinja alows for tests like `{% if a is odd or b is odd %}`, but in Tera `{% if <exp> is <test> %}` is a single node so that would be an error.

**Comment by Keats** [comment]
Hmm I guess we can make it work like the `if` nodes. I'll have a look for the next version once [pest](https://github.com/pest-parser/pest) v1 is released

**Comment by Keats** [comment]
Fixed as of 0.11.0-beta, stable release will come once `pest` releases 1.0
