### ISSUE TITLE
How can I create a layout and a child template based on it?

### ISSUE THREAD

**Issue by kokinarido** [Keats/tera#195]
In the documentation there's only "Extending another instance of Tera" which is what I need. 

How can I create a layout template and a child template based on it?

**Comment by Keats** [comment]
Hmm are you looking for [inheritance](https://github.com/Keats/tera#inheritance) rather than extending by any chance?

**Comment by kokinarido** [comment]
And also:

```

#[macro_use] extern crate tera;
#[macro_use] extern crate lazy_static;

use iron::prelude::*;
use iron::status;
use tera::Tera;
use tera::Context;

//.....................


fn index(_: &mut Request) -> IronResult<Response> {
    Ok(Response::with((iron::status::Ok, tera.render("home/index.html"))))
 }

```
error:


```
error[E0423]: expected value, found module `tera`
  --> src/main.rs:27:42
   |
27 |     Ok(Response::with((iron::status::Ok, tera.render("home/index.html"))))
   |                                          ^^^^--------------------------
   |                                          |
   |                                          did you mean `tera::render(...)`?
```

when I replace `tera.render` with` tera::render`, it doesn't compile either  because `render` is a module.

**Comment by Keats** [comment]
`tera` is the name of the crate, you need to instantiate a Tera instance first like so: https://github.com/Keats/tera/blob/master/examples/basic.rs#L13
Iron has a Tera integration though: https://github.com/leshow/iron-tera

**Comment by kokinarido** [comment]
`tera is the name of the crate, you need to instantiate a Tera instance first like so: https://github.com/Keats/tera/blob/master/examples/basic.rs#L13`

I already have had that in my code. How to fix the error?

**Comment by kokinarido** [comment]
![screenshot_2017-07-19_15-30-08](https://user-images.githubusercontent.com/28803222/28355667-8fd955ea-6c97-11e7-89db-9bde1fb9f435.png)

**Comment by Keats** [comment]
use `TEMPLATES::render`

**Comment by kokinarido** [comment]
error: no associated item named `render` found for type `TEMPLATES` in the current scope

**Comment by Keats** [comment]
I meant `TEMPLATES.render` sorry

**Comment by kokinarido** [comment]
yes, but it requires the second parameter - context. I don't have one because for now there're no variables in my template. how can I avoid passing it?

**Comment by Keats** [comment]
A context is mandatory, you can pass `&Context::new()` if you don't really have one

**Comment by kokinarido** [comment]
```
fn index(_: &mut Request) -> IronResult<Response> {
    let mut ctx = Context::new();
    Ok(Response::with((iron::status::Ok, TEMPLATES.render("home/index.html", &ctx))))
 }

```

error:
`
the trait bound `std::result::Result<std::string::String, tera::Error>: iron::modifier::Modifier<iron::Response>` is not satisfied
`

**Comment by Keats** [comment]
`render` returns a `Result` so you will need to handle it

**Comment by kokinarido** [comment]
thanks
