### ISSUE TITLE
Passing a variable to a parent layout

### ISSUE THREAD

**Issue by kokinarido** [Keats/tera#197]
Say, I have an Iron app. In it there're a parent template-layout and a few child ones. I want to pass a few variables directly to the parent layout. I don't want to pass it to each of child templates via Context. 

Nobody knows. In Rails it's possible, in other frameworks too.

Is it possible with Tera? Or does Iron have to support this in the first place?

**Comment by Keats** [comment]
Tera has no concept of Iron or http. If you are using inheritance, the parent layout will get all the values of the context automatically when rendering a child template.
I don't really see how frameworks could pass variables to the parent layout automatically, unless they have a concept of global context and update the url in a middleware or something

**Comment by kokinarido** [comment]
Ok
How can I get access to, say, an enum or function defined in app.rs from a template? Possible?

    #main.rs
    
    enum E1 { Var1, Var2 }
    fn func1(a: &str) { println!("hi") }

   # my_page.html

   E1 ???
   func1("fdsfdsfds") ????

**Comment by Keats** [comment]
No Tera can't access Rust code. If you want to access Rust from a template engine https://github.com/lfairy/maud would be a better choice
