### ISSUE TITLE
Context from Serde Serializable

### ISSUE THREAD

**Issue by bfrog** [Keats/tera#20]
It would be nice if instead of having to build out a context for the template... we could just pass in anything that serde sees as serializable.

like...

``` rust
impl Render<T: Serializable> for Template {
   fn render(tmpl: &str, ctx : &T) { ... }
}
```

Would be very convienent indeed

**Comment by Keats** [comment]
The issue with that is that it allows use of Tera that will error, ie I could call `render("hello.html", &1)` and it would be ok for the compiler but with no way of actually using that variable in the template since it doesn't have a name
