### ISSUE TITLE
How to use date filter to parse NaiveDateTime value

### ISSUE THREAD

**Issue by samrayleung** [Keats/tera#210]
Hey Keats, I have an issue now, I define a `NaiveDateTime`  field named  `create_time` to represent Postgresql timestamp. Now I want to format `create_time` with `date` filter when renders it, but the compiler complains that 
```
Error parsing `"2017-07-30T14:47:57.602"` as rfc3339 date
```
could you give me some suggestion about how to fix this issue so I could format `create_time` correctly

**Comment by Keats** [comment]
Hmm so the filter doesn't know about `NaiveDateTime` and is trying to parse it as a rfc3339 date.

https://github.com/Keats/tera/blob/master/src/filters/common.rs#L61 should be expanded to try parsing the input as a `NaiveDateTime` (https://docs.rs/chrono/0.4.0/chrono/naive/struct.NaiveDateTime.html#example-43) if rfc3339 fails

**Comment by samrayleung** [comment]
So, do you mean the `date` filter parses `NaiveDateTime` as `DateTime` and it fails. In order to use `date` filter to parse `NaiveDateTime`, I have to parse `NaiveDateTime` to rfc3339 before, right?

**Comment by Keats** [comment]
rfc3339 is timezone aware so a naive datetime might not yield the output you think of.

I meant that it shouldn't be too hard to had `NaiveDateTime` support to the `date` filter in Tera. I'll do it when I have time but would welcome a patch for that.
In the meantime, you can probably add some kind of default timezone to your `NaiveDateTime` to make it into a `DateTime` and then use https://docs.rs/chrono/0.4.0/chrono/struct.DateTime.html#method.to_rfc3339

**Comment by samrayleung** [comment]
It feels so good to send a pull request to add a patch, but I am new to Rust so that I am afraid I am not skillful enough to patch it :(

**Comment by Keats** [comment]
Don't worry, I'll do it but I'm busy this week so probably next week

**Comment by Keats** [comment]
Fixed as of 0.11.0-beta, stable release will come once `pest` releases 1.0

**Comment by samrayleung** [comment]
Keats, thanks for your hard work :)
