### ISSUE TITLE
Use GlobSet instead of glob

### ISSUE THREAD

**Issue by Keats** [Keats/tera#212]
So we can do more fancy globbing

**Comment by Keats** [comment]
`globset` is not currently a replacement for `glob` though: https://github.com/rust-lang-nursery/glob/issues/59

**Comment by Gilnaa** [comment]
Have a look at (globwalk)[https://github.com/Gilnaa/globwalk]

**Comment by Keats** [comment]
That looks great but I believe it should be part of the `globset` crate no? The code is farily short and in the short thread above they are talking about moving the `glob` walk feature to `globset` at some point
