### ISSUE TITLE
Question about "object"

### ISSUE THREAD

**Issue by samrayleung** [Keats/tera#216]
Hey Keats, I have occured a strange problem. Say, this is my rust code
```rust
#[get("/admin/index")]
pub fn index(user: User, db: DB) -> Template {
    let visitor_logs = VisitorLog::query_login_user(db.conn(), user.0);
    let users = user::User::query_by_id(db.conn(), user.0);
    let mut context = HashMap::new();
    if let Some(user) = users.first() {
        context.insert("username", UserInfo::Username(user.username.to_string()));
    }
    if let Some(log) = visitor_logs.first() {
        context.insert("access_time", UserInfo::AccessTime(log.access_time));
    }
    Template::render("admin/index", &context)
}
```

and this is my tera file
```html
                <div class="media-body">
                    <h5 class="media-heading">User:</h5>
                    <ul class="list-unstyled user-info">
                        <li> <a href="">{{username}}</a> </li>
                        <li>Last Access :
                            <br>
                            <small>
                  <i class="fa fa-calendar"></i>&nbsp;{{access_time}}</small>
                        </li>
                    </ul>
                </div>
```
the expected rendered html should show `username` and `access_time`, but I have no idea 
why the rendered result looks like this:
```html
<div class="media-body">
                    <h5 class="media-heading">User:</h5>
                    <ul class="list-unstyled user-info">
                        <li> <a href="">[object]</a> </li>
                        <li>Last Access :
                            <br>
                            <small>
                  <i class="fa fa-calendar"></i>&nbsp;[object]</small>
                        </li>
                    </ul>
                </div>
```
I just wonder what is going on, Is there something wrong ?

**Comment by Keats** [comment]
It seems `username` and `access_time` are structs and those get converted to `Value::Object` by Serde which Tera renders as `[object]`.

What are `UserInfo::Username` and `UserInfo::AccessTime`? If you remove those calls, it should work as expected since you would have a string for the username and a string/int for the time

**Comment by samrayleung** [comment]
The `UserInfo` is `enum`:
```rust
#[derive(Deserialize, Serialize)]
enum UserInfo {
    Username(String),
    AccessTime(NaiveDateTime),
}

```

**Comment by Keats** [comment]
You don't need that enum, `String` is serializable by serde automatically and `NaiveDateTime` is as well if you add the `serde` feature to chrono: https://github.com/chronotope/chrono#usage

**Comment by samrayleung** [comment]
It makes sense, thanks for your suggestion :)

**Comment by samrayleung** [comment]
Hey, Keats ,I have another question. Say, I have a `base.html.tera` file, and other tera files (eg, `index.html.tera` and `profile.html.tera`)are extended from `base.html.tera`. Some code  in `base.html.tera` as below:
```html
<div class="media-body">
                    <h5 class="media-heading">User:</h5>
                    <ul class="list-unstyled user-info">
                        <li> <a href="">[object]</a> </li>
                        <li>Last Access :
                            <br>
                            <small>
                  <i class="fa fa-calendar"></i>&nbsp;[object]</small>
                        </li>
                    </ul>
                </div>
```
 When I render `index.html.tera`, I insert `username` and `access_time` into `context`, when I render `profile.html.tera`, could I stop inserting `username` and `access_time` again, could I insert a `value` into the parent tera file once, and could render its childern tera file with  `value` many times?

**Comment by Keats** [comment]
Rendering are completely separated so there's no way to do that.
The way it's done in Django for example is to define some hook in the framework where you can add for example the request (https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-TEMPLATES) but that's the framework responsibility, not the templating engine

**Comment by samrayleung** [comment]
oops, get it. Thanks again for your help :)

**Comment by samrayleung** [comment]
I reopen this issue because I have the same issue. Now I have to define a `enum`, but I still get an object, instead of a value, how to solve this problem ?

**Comment by Keats** [comment]
I don't really understand why you are wrapping it into an enum?

**Comment by samrayleung** [comment]
Because I need to. Say, I need to return `Vec<Post>` and `String`, and I could not
insert `Vec<Post>` and `String` into a same `Hashmap`, so I need to define an enum.
```html
<div class="media-body">
                    <h5 class="media-heading">User:</h5>
                    <ul class="list-unstyled user-info">
                        <li> <a href="">{{username}}</a> </li>
                        <li>Last Access :
                            <br>
                            <small>
                  <i class="fa fa-calendar"></i>&nbsp;{{access_time}}</small>
                        </li>
                    </ul>
                </div>
				
                            <table id="dataTable" class="table table-bordered table-condensed table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>Number</th>
                                        <th>Title</th>
                                        <th>SubTitle</th>
                                        <th>Create Time</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    {% for post in posts %}
                                    <tr>
                                        <td>{{loop.index}}</td>
                                        <td>{{post.title}}</td>
                                        <td>{{post.subtitle}}</td>
                                        <td>{{post.create_time}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
```
So, could you get my point ?

**Comment by Keats** [comment]
> Say, I need to return Vec<Post> and String, and I could not insert Vec<Post> and String into a same Hashmap, so I need to define an enum.

If they both impl Serialize sure you can.

```rust
let mut context = Context::new();
context.add("posts", &posts);
context.add("username", &username);
```

This will work just fine. See https://tera.netlify.com/docs/usage/#usage the part about Context

**Comment by samrayleung** [comment]
But I not only return `Vec<Post>` and `String`, I just take something for
example. I may need to return `User`, `Post`, `Vec<T>`,or `String`, but they are
not the same type, so in order to insert into a same `Hashmap`, I need to define
a `enum`, I think `enum` is the best way to satisfy my need, but it seems `enum` could
not render correctly :)

**Comment by Keats** [comment]
The way with Tera is to use `Context`, where you can put anything that impl Serialize in it. For example https://github.com/Keats/tera/blob/master/examples/basic.rs#L27-L31 shows how it works with 3 different types, it would work that way with your `User`, `Post` etc

**Comment by samrayleung** [comment]
It seems everything I put into `Context` should be `reference` , is it ?

**Comment by Keats** [comment]
Yep, the definition of `Context::add` is https://docs.rs/tera/0.10.10/tera/struct.Context.html#method.add

**Comment by samrayleung** [comment]
Thanks so much for your patience, I have solved my issue perfectly, thanks again :)
