### ISSUE TITLE
Using Rockets uri! in templates

### ISSUE THREAD

**Issue by Korvox** [Keats/tera#217]
Rocket [recently added](https://github.com/SergioBenitez/Rocket/commit/eeef8a44ce44774c2431a18ad2d0ca9943cf21f9) a uri! macro that can derive urls for handlers (ie url_for). Tera talks about url_for [a lot](https://tera.netlify.com/docs/templates/#global-functions), but as a concrete function registered via `register_global_function`. Is there a way to expose this Rocket macro inside templates directly, or should we just wrap the macro invocation in a method and register that?

**Comment by Keats** [comment]
Tera has no knowledge of Rust or Rocket so you will need to wrap the macro in a global fn
