### ISSUE TITLE
Testers, filters, and global functions should be traits

### ISSUE THREAD

**Issue by SergioBenitez** [Keats/tera#219]
At present, all of these have signatures that require either static function (testers, filters), or static function/closures (global functions). Instead, all of these should use traits so that any structure with arbitrary state can be used as a test/filter/global function handler. Here's what I'm imagining:

```rust
trait Tester: 'static {
    fn(&self, _: Option<Value>, _: Vec<Value>) -> Result<bool>;
}

trait Filter: 'static {
    fn(&self, _: Value, _: HashMap<String, Value>) -> Result<Value>;
}


trait GlobalFn: Send + Sync + 'static {
    fn(&self, _: HashMap<String, Value>) -> Result<Value>;
}
```

For backwards compatibility and ease-of-use, you can provide a blanket impl for fn-like types. For instance, for `Tester`, we can do:

```rust
impl<F: 'static> Tester for F where F: Fn(Option<Value>, Vec<Value>) -> Result<bool> {
    fn(&self, a: Option<Value>, v: Vec<Value>) -> Result<bool> {
        self(a, v)
    }
}
```

**Comment by Keats** [comment]
Did it come up as something asked for Rocket? That seems ok to me.

**Comment by Keats** [comment]
@SergioBenitez Do you have a concrete example for the changelog from actual use? I'll probably implement it this week

**Comment by remexre** [comment]
What'd the status on this end up being? Did there turn out to be some hidden pitfall to using traits?
