### ISSUE TITLE
Do we need complex maths?

### ISSUE THREAD

**Issue by Keats** [Keats/tera#22]
Simple math (only 1 operation) should be enough for most of the cases

**Comment by mitsuhiko** [comment]
Just steal the math that Jinja2 supports: plus, minus, div, floor div, mod, mult, power. All of those turned out to be super useful.

**Comment by Keats** [comment]
Did you get a request for precedence/complex operations like `{{ 1 + 2 * 4 - 1 / 2 }}` or did you implement it without thinking like I did?
I never do more than stuff like `+1`, `-1`, `*20` in templates usually so I don't know how common more complex maths is
