### ISSUE TITLE
`pluralize` should add the "s" when the number is 0

### ISSUE THREAD

**Issue by kennytm** [Keats/tera#220]
The singular form should be taken only when the input is exactly the integer 1. But currently, [by design](https://github.com/Keats/tera/blob/272f6c0c77750864eba3ace91b30a7137f051682/src/filters/number.rs#L10-L23), every number below 2 uses the singular form, which is [grammatically incorrect with 0](https://www.quora.com/Why-do-we-say-use-a-plural-noun-when-we-specify-quantity-as-zero). 

Test case:

```
0 thing{{ 0 | pluralize }}
```

* Expected output: `0 things`
* Actual output: `0 thing`

Version: `tera 0.10.10`.

**Comment by Keats** [comment]
Eh TIL. I'll fix it in the 0.11 branch

**Comment by Keats** [comment]
Fixed as of 0.11.0-beta, stable release will come once `pest` releases 1.0

**Comment by LFalch** [comment]
The new implementation is still wrong

**Comment by LFalch** [comment]
Perhaps an extra flag should be added for languages like French, where zero would also make the noun take singular form.

**Comment by kennytm** [comment]
If localization support is needed, the `pluralize` function will be insufficient, and probably out of scope (#134). See the CLDR plural rules.

**Comment by Keats** [comment]
Localization is definitely out of scope as @kennytm said. Direct link to the plural rules: http://cldr.unicode.org/index/cldr-spec/plural-rules
