### ISSUE TITLE
Investigate passing functions instead of templatetags

### ISSUE THREAD

**Issue by Keats** [Keats/tera#23]
Functions would be like filters that don't have a first arg?
Could also fake kwargs like `{{ url_for(view_name="hello", user.id, company.id }}` and have the kwargs be a hashmap but not sure if that is actually needed

**Comment by Keats** [comment]
@mitsuhiko how would a custom `cache` tag (for example) work as a function ?

That's the example in Jinja2 docs (http://jinja.pocoo.org/docs/dev/extensions/#module-jinja2.ext) and we actually had something similar at a previous job where the templatetag was like: 
```django
{% caching currency country %}
// render something
{% endcaching %}
```

**Comment by mitsuhiko** [comment]
In Jinja2 you can do this:

```{% call cache_block('currency', 'country') %}
...
{% endcall %}```

**Comment by Keats** [comment]
Ha didn't know about `call`.

Notes for myself below.
So to sum up things, we should be able to register functions that would have the following type:

```rust
type TeraFn = Fn(args: &[Value]) -> TeraResult
```

Someone wanting to add a fn will need to write its own argument handling (enough args, their types etc).
`TeraResult` is `Result<String>`.

You could add fns globally by calling `tera.add_fn("url_for", url_for)`.

In the templates, you would use it like `{{ url_for("profile", user.id) }}` that would translate a `FunctionNode` with args == `["profile", user.id]`.

For tags like caching that takes content, it's a bit of a blur.

```html
{% exec cache_row(currency, country) %}
...
{% endexec %}
```
In this case, `cache_row` would be called with args == `[currency, country]` but how would it work to stop/continue rendering the children. Ie if in cache, return the result and otherwise render the content.


Inline functions seem easy enough to implement, basically the same as filters will be. Not convinced about block functions yet, need to have examples other than caching.

**Comment by mitsuhiko** [comment]
BTW. I recommend to stay somewhat compatible with Twit/Jinja instead of deriving to stay consistent with Rust to make syntax highlighting and editor support work. Eg: `call/endcall` > `exec/endexec` (and `and` instead of `&&` etc.).

**Comment by Keats** [comment]
Actually, If we pass functions, I'm not sure we need filters anymore, doing `{{ capitalize(name) }}` is the same as `{{ name | capitalize }}` and makes Tera simpler since there's only one type of thing you can write: functions.

The lack of kwargs in Rust is annoying but maybe we can fake them in the templates with something like:
`format_date(date, format="YYYY-MM-DD")` and the signature of a function could be `fn my_fn(args: [Value]. kwargs: HashMap<String, Value>) -> TeraResult`

**Comment by Keats** [comment]
We could even remove args and only have kwargs, ie `{{ capitalize(text=name) }}`

A bit more verbose but clearer to use

**Comment by mitsuhiko** [comment]
@Keats jinja supports functions just fine. The reason it has filters separately are twofold: functions live in the same namespace as template variables but filters are in a separate one. This avoids a common issue with name clashes. Secondly filters can be constant folded whereas function calls can not.

For instance if you do `{{ "<foo bar>"|upper }}` in Jinja it will be optimized to `"<FOO BAR>"` automatically if the filter permits it. We cannot do such things for functions because we do not know if it won't be shadowed at runtime by a template variable.

Also functions are terrible for chaining whereas filters come natural.

**Comment by Keats** [comment]
@mitsuhiko thanks for the feedback, totally makes sense. Hopefully I will have time to implement filters soon
