### ISSUE TITLE
Default filter

### ISSUE THREAD

**Issue by stephanbuys** [Keats/tera#231]
Hi, would a `default` filter still be able to make it into `v0.11`? Syntax would be: `{{ undefvar|default('x') }}`  or `{{ undefvar|default(1) }}` , etc?

**Comment by Keats** [comment]
Yeah it was mentioned in #46 but forgot to do it. I'll implement it this week

**Comment by Keats** [comment]
It's added in the 0.11 branch if you want to try it

**Comment by stephanbuys** [comment]
Awesome - will try it, quick question - why is it necessary to type `value=`?

**Comment by stephanbuys** [comment]
Some feedback - there might be an issue when testing on a property of an object:
`Expr { val: Ident("s.index"), negated: false, filters: [FunctionCall { name: "default", args: {"value": Expr { val: String(""), negated: false, filters: [] }} }] }`

**Comment by Keats** [comment]
> why is it necessary to type value=?
All filters (and macros) in Tera have mandatory keyword arguments. Only tests can be used without them.

> there might be an issue when testing on a property of an object
Can you detail the issue? I added a test like `{{ obj.val | default(value="hey") | capitalize }}` but it works as expected

**Comment by Keats** [comment]
ah I left a stray `println!`, removed now

**Comment by Keats** [comment]
Fixed as of 0.11.0-beta, stable release will come once `pest` releases 1.0
