### ISSUE TITLE
Heads-up: fun use of Tera

### ISSUE THREAD

**Issue by stephanbuys** [Keats/tera#232]
Hi Vincent, as you know I've been following tera for a long time, and I'm happy to have really started using it over the last few weeks, it has come a long way. You might be interested in the very unconventional use that this kind of system enables:

https://github.com/stephanbuys/dmt

**Comment by Keats** [comment]
Interesting! Is it like the use of Jinja2 in Ansible? I'd recommend using TOML over YAML but that's mainly because I dislike YAML...

**Comment by stephanbuys** [comment]
It supports env, YAML and CSV, toml can easily be supported by a plugin. Its on my list :-)

Correct - I was inspired by Saltstack, it is more general purpose though as it is easy to turn any text file into a template, just as easy to add data.
