### ISSUE TITLE
Sort filter (and possibly some others)

### ISSUE THREAD

**Issue by stephanbuys** [Keats/tera#233]
Hi, would it be possible to implement the following filters:

1) `sort`, as per Jinja, the ability to either sort an array of strings or an array of objects according to a field.
2) `dedup` or `uniq`, ability to eliminate duplicates based on (1), or any sorted list.

**Comment by Keats** [comment]
I want to add that but it's not super clear how that would work, my thoughts were:

- `{{ my_array | sort }}` will sort primitives only, if you have objects/tuple instead and use `sort`, it will do nothing I guess?
- `{{ my array | sort(attribute="age")` will sort an array of hashmap/objects by the given attribute

but I'm not 100% convinced yet

**Comment by stephanbuys** [comment]
I actually really like your proposal, what bugs you?

**Comment by Keats** [comment]
It looks better after seeing it written but tuples will not be sortable, which is probably ok I think

**Comment by stephanbuys** [comment]
Well you could make the tuple index numerical, zero-indexed? Almost exactly like rust?
so `{{ my array | sort(attribute=0) }}` would be first element of dict or tuple - that would be very cool :-)

**Comment by Keats** [comment]
I don't think you can just do that, sorting a tuple implies accessing it like `k.1` and you can't put a variable for the index. I think it's fair enough to just ignore tuples for now and focus on string/numbers/objects.

If anyone is willing to add it, it should be in the `0.11` branch in the `src/builtins/filters/array.rs` and the tests should be in the same file.

**Comment by hoggetaylor** [comment]
I'll see if I can get something going for this.

**Comment by Keats** [comment]
Shipped in 0.11, thanks @hoggetaylor !
