### ISSUE TITLE
importing macro fails in themes directory

### ISSUE THREAD

**Issue by NuLL3rr0r** [Keats/tera#235]
I'm creating a theme for Gutenberg using Tetra templates. I faced an issue with defining and using macros. I'm not sure if I'm missing something here since I couldn't find anything in the documentation.

Let's say we have a Gutenberg website and a theme:

```
    .
    |_ content
    |_ templates
    |_ themes
        |_templates
            |_ index.html
            |_ page.html
            |_ macros.html
```

I tried to import macros from index.html:

```
{% import "macros.html" as macros %}
```

But, I'll get the following error:

```
Error: Failed to render page '/home/babaei/dev/babaei-net-blog-source/babaei.net/content/blog/2016-04-29-discourse-as-a-blog-comment-service-on-freebsd-without-docker.md'
Reason: Failed to render 'minimal-blog/templates/page.html' (error happened in 'minimal-blog/templates/index.html').
Reason: Template 'macros.html' not found
```

However, if I copy macros.html to the parent template folder (outside the theme directory, inside the actual website) then it compiles fine:

```
    .
    |_ content
    |_ templates
        |_ macros.html
    |_ themes
        |_templates
            |_ index.html
            |_ page.html
            |_ macros.html
```

Am I missing something here? Is that a bug? or, is it expected behavior?

**Comment by NuLL3rr0r** [comment]
By the way, here is the [website source](https://github.com/NuLL3rr0r/babaei-net-blog-source) and the [theme source](https://github.com/NuLL3rr0r/gutenberg-theme-minimal-blog) for investigation.

**Comment by NuLL3rr0r** [comment]
Update: I noticed importing macros from page.html works but not from index.html.

Since I pushed to the master branch, here is [the repo at the commit with the described issue](https://github.com/NuLL3rr0r/gutenberg-theme-minimal-blog/tree/4b24566e6b782f8aab9907befaf66fd4a839501f) and [the one which includes macros from page.html but not index.html which builds fine](https://github.com/NuLL3rr0r/gutenberg-theme-minimal-blog/tree/4aa556252f2d6627bef56c11cf26613b821ce50d).

**Comment by Keats** [comment]
Should that be in Gutenberg rather than Tera?

**Comment by Keats** [comment]
I'll close this one since it's gutenberg related. I had a quick look and it should really work, see the one referenced above
