### ISSUE TITLE
Erroneous link in documentation

### ISSUE THREAD

**Issue by HeroicKatora** [Keats/tera#240]
Documentation fix
--------

In the documentation for v0.11, the link in this line should be replaced by `https://tera.netlify.com/` otherwise it does not work correctly on other websites such as on `https://docs.rs/tera/0.11.0-beta.1/tera/`.
https://github.com/Keats/tera/blob/ebd4326bc4ee9dbae7b530d30e87c8b7fd00f3ce/src/lib.rs#L5

**Comment by Keats** [comment]
Thanks a lot!
I've fixed it in dd21df7

**Comment by Keats** [comment]
Releasing 0.11, it's going to be fixed. Thanks!
