### ISSUE TITLE
Using super in non-inherited template panics

### ISSUE THREAD

**Issue by HeroicKatora** [Keats/tera#243]
Using `super` in block of a template that does not extend another causes a panic. It should produce an error result instead. Below is a small example for causing this behaviour.

```
{% block main %} {{ super() }} {% endblock main %}
```

**Comment by Keats** [comment]
This is already fixed in 0.11, which is available as beta on crates.io. The beta is pretty stable and is only waiting for `pest` to not be beta anymore to get released
