### ISSUE TITLE
 questions

### ISSUE THREAD

**Issue by GildedHonour** [Keats/tera#245]
1) How can I check if a variable exists or has been passed to a template, inside a template?

2) How can I pass a variable to a layout directly? I don't want to have to create a variable in each template and pass it.

**Comment by Keats** [comment]
1. I don't think there is a way to check if a value has been passed vs being falsy, ie

```jinja2
{{ if my_array }}
{{ endif }}
```
will be both false is `my_array` is an empty array or not in the context. If it is to set a default value, there is a `default` filter coming in 0.11

2. I'm not sure what you mean. You pass a context to a template renderer and the context will be available in all templates used in the template you're rendering, minus macros.
