### ISSUE TITLE
Crates depending on 0.11.0-beta.3 (and below) appear to be unpublishable

### ISSUE THREAD

**Issue by acmcarther** [Keats/tera#249]
This is a very ephemeral issue, but I figured I'd track it anyway:

Cargo resolves dependencies "differently" under `cargo publish`, promoting Tera's `pest` crate dependency where it shouldn't. This is problematic, because `pest` had a breaking change between `1.0.0-beta.17` and `1.0.0-rc-1`. Cargo resolves the former under `build` which works, and the latter under `publish` which doesn't (until https://github.com/Keats/tera/commit/2f9cf115f2e4f590cb40f21d34933319b03f9fac)

It can be fixed without much trouble by publishing `tera-0.11.0-beta.4` containing that commit.

**Comment by Keats** [comment]
I meant to release a 0.11-rc.0 today, would that work for you?

**Comment by Keats** [comment]
Scratch that, just published beta 4 so it keeps working in the meantime, next version should be the proper 0.11 anyway

**Comment by acmcarther** [comment]
Beta4 work like a charm and I was able to publish.

Thanks for the super quick turnaround!
