### ISSUE TITLE
Importing macros inside includes no longer possible

### ISSUE THREAD

**Issue by Lirusaito** [Keats/tera#250]
It would appear that importing macros is somewhat broken in the latest release, in that an included template with an imported macro namespace will give an error that the namespace does not contain the desired macro, unless the top level template has the namespace imported.

But that's so wordy, let's have the code speak for itself:
__macros:__
```jinja
{% macro my_macro() %}
my macro
{% endmacro %}
```
__includeme:__
```jinja
{% import "macros" as macros %}
{{ macros::my_macro() }}
```
__example:__
```jinja
{% include "includeme" %}
```
And here's a cleaned up excerpt based off of example/basic.rs
```rust
#[macro_use] extern crate tera;

use tera::Context;

fn main() {
    match compile_templates!("examples/templates/**/*").render("example", &Context::new()) {
        Ok(s) => println!("{:?}", s),
        Err(e) => {
            println!("Error: {}", e);
            for e in e.iter().skip(1) {
                println!("Reason: {}", e)
            }
        }
    }
}
```
Will produce the following output:
```
Error: Failed to render 'example': error while rendering a macro from the `macros` namespace
Reason: Macro `my_macro` was not found in the namespace `macros`
```

Unless a line like the following is in __example__:
```jinja
{% import "macros" as macros %}
```

I believe this to be a bug because it used to work this way, and it would make more sense if macros included in a file worked regardless of whether they were being included in another file, after all one expects the included file to stand alone, right?

PS: I've been tracking this all night(since at least 12 AM EST) (and for the last day or so before that), so if any of this doesn't make sense, just let me know and I'll clear it up ^^;

**Comment by Keats** [comment]
That does seem like a bug, I'll have a look. Thanks for the report!

**Comment by Keats** [comment]
@Lirusaito Can you check #251 to see if that works for your now?

**Comment by Lirusaito** [comment]
Sorry for the delay, I've been pushing forward with delayed work now that I can actually run again ^^;
Yeah, that seems to work for my smaller test cases, I'll let you know if it breaks once it reaches rocket.
Thanks for the speedy fix!

**Comment by Keats** [comment]
I'll merge that for now and wait a couple of days before a new release in case someone spots another regression like that

**Comment by Lirusaito** [comment]
Alright, so I'm still researching exactly why, but I still have some issue related to this.
Here's what I've learned so far:
I have a file, let's call it index.html.tera, that has
```jinja
{% include "whatever" %}
more content here
{% include "somethingelse" %}
more stuff
```
None of that really matters except the first line, though, I get the failure as long as it's present
whatever.html.tera contains the following:
```jinja
{% import "test_macro" as test %}
{{ test::test() }}
```
and that is, of course
```jinja
{% macro test() %}
TEST SUCCESS
{% endmacro test %}
```
Our basic test case as described above, I just wrote it differently so it'd make sense inside my project.

Anyway, when whatever.html.tera contains ONLY that, I'll get a TEST SUCCESS and the rest of the content displayed; but when it has a bunch of other things, that's when it starts complaining with the same error as before:
```rust
=> Error: Failed to render 'page': error while rendering a macro from the `test` namespace
=> Error: Macro `test` was not found in the namespace `test`
```

I'm still diving into the specifics of why, I just figured it'd be polite to make it known.

**Comment by Lirusaito** [comment]
I've figured it out, though this may not be the only case, and this might be intended behavior(if it is, I apologize).
I was writing giant blocks where I would import right before I needed to call macros.
So, sometimes, it'd look like this
```jinja
Stuff
{% if user %}
stuff here
{% import "test" as test %}
{{ test::test() }}
other stuff here
{% endif %}
more stuff```

The issue is apparently here:
```jinja
{% if user %}
{% import "test" as test %}
{{ test::test() }}
{% endif %}```
And it can be fixed by doing this:
```jinja
{% import "test" as test %}
{% if user %}
{{ test::test() }}
{% endif %}```

I can, of course, just fix all these(probably import at the tops of files), unless the old behavior is desirable and you'd like to fix it so it will work.

**Comment by Lirusaito** [comment]
Also, a macro does not appear to be able to use a macro in another file on its own, anymore.

submacros:
```jinja
{% macro test() %}
Success!
{% endmacro test %}
```
macros:
```jinja
{% import "submacros" as sub %}
{% macro test() %}
{{ sub::test() }}
{% endmacro test %}
```
index:
```jinja
{% import "macros" as macros %}
{{ macros::test() }}
```

Since this didn't work, I tried this:
macros:
```jinja
{% macro test() %}
{% import "submacros" as sub %}
{{ sub::test() }}
{% endmacro test %}
```
But line 2 errors, for that.

So I tried
index:
```jinja
{% import "submacros" as sub %}
{% import "macros" as macros %}
{{ macros::test() }}
```
This works, but this defeats the purpose of macros including each other, I feel, because you should only need to import a macro and shouldn't have to do setup for the internals of the macro, littering a list of imports at the tops of all files that use one that uses another that uses another, etc.

**Comment by Lirusaito** [comment]
Also, should I make this another issue? Or even two others?

**Comment by Keats** [comment]
For the `import` in a `if`, it wasn't really intended to work. I guess I should restrict the use of import in the grammar to not be allowed inside other nodes but that's a breaking change so for the next major version.

The 2nd one is definitely a bug though, I'd appreciate if you open a separate issue for each (you can just copy/paste your posts)
