### ISSUE TITLE
Better Examples

### ISSUE THREAD

**Issue by bootandy** [Keats/tera#253]
I am volunteering to write some more examples for this project. I envisage just being able to cd to an examples directory and execute "cargo +nightly run" and run the code with Rocket (I imagine most people are using this library with Rocket). I would like the examples to look like this Rocket example:

https://github.com/SergioBenitez/Rocket/tree/master/examples/ranking

This should stop things like this happening: https://github.com/SergioBenitez/Rocket/issues/192 (which happened to me too).

Let me know if you agree with this.

**Comment by Keats** [comment]
Happy to have more examples!
The issue you linked however is Rocket specific as it removes the extensions before adding it to Tera, your first attempt is how it would work normally as you can see in the docs: https://tera.netlify.com/docs/templates/#inheritance

> I imagine most people are using this library with Rocket

I wouldn't be so sure about that 😉

**Comment by bootandy** [comment]
Interesting, I didn't know that. thanks. I'll build a rocket-specific example. 

What are people mostly using this library for if not with rocket? On its own to build email templates or paired with a different web framework?

**Comment by Keats** [comment]
I build Tera for https://github.com/Keats/gutenberg so anyone using it

**Comment by Keats** [comment]
I should have mentioned that a Rocket example probably should be in the Rocket repo, not here as Rocket doesn't work on stable Rust and everything in this repo should

**Comment by bootandy** [comment]
That sounds sensible. Thanks.
