### ISSUE TITLE
Cannot import other macros into macro file

### ISSUE THREAD

**Issue by Lirusaito** [Keats/tera#255]
It appears a macro file cannot import another file of macros for use in its own, anymore.

submacros:
```jinja
{% macro test() %}
Success!
{% endmacro test %}
```
macros:
```jinja
{% import "submacros" as sub %}
{% macro test() %}
{{ sub::test() }}
{% endmacro test %}
```
index:
```jinja
{% import "macros" as macros %}
{{ macros::test() }}
```

Since this didn't work, I tried this:
macros:
```jinja
{% macro test() %}
{% import "submacros" as sub %}
{{ sub::test() }}
{% endmacro test %}
```
But line 2 errors, for that.

So I tried
index:
```jinja
{% import "submacros" as sub %}
{% import "macros" as macros %}
{{ macros::test() }}
```
This works, but this defeats the purpose of macros including each other, I feel, because you should only need to import a macro and shouldn't have to do setup for the internals of the macro, littering a list of imports at the tops of all files that use one that uses another that uses another, etc.

**Comment by Keats** [comment]
It's fixed in the commit above, you can try the `next` branch to play with it as you seem very good at finding cases I didn't think before with macros!
