### ISSUE TITLE
docs.rs failed to build tera-0.11.3

### ISSUE THREAD

**Issue by samuelcolvin** [Keats/tera#261]
https://docs.rs/crate/tera/ and the logs of the failure: https://docs.rs/crate/tera/0.11.3/builds/86080

Appears to be an error when building the docs for tera.

**Comment by Keats** [comment]
This is because pest (a dependency of Tera) is not building: https://github.com/onur/docs.rs/issues/23

**Comment by Keats** [comment]
It's now building again
