### ISSUE TITLE
Add enumerate filter

### ISSUE THREAD

**Issue by bootandy** [Keats/tera#262]
I found myself needing an enumerate filter (similar to jinja2's loop.index0) :

https://github.com/bootandy/window_funcs/blob/master/templates/init.html.tera#L35

Is there any reason there isn't an enumerate filter for loops? & Can I add one to tera ?

http://jinja.pocoo.org/docs/2.10/templates/#for

**Comment by Keats** [comment]
Tera has almost all those variables as well: https://tera.netlify.com/docs/templates/#for
Is it not working for you?

**Comment by bootandy** [comment]
oops I did not see that thank you. sorry.
