### ISSUE TITLE
Consider adding a "Why Tera" document

### ISSUE THREAD

**Issue by jwatt** [Keats/tera#266]
Cool project! It's unclear to me why I would prefer Tera over other templating languages, though, specifically Liquid since so many people know that and there's so much content out their using it. I'd like to be able to guage for myself if Tera is such an improvement over Liquid that it's worth losing out on the rather substantial compatibility benefits that come with using Liquid. It would be very helpful to have a document in the root dir explaining this. Maybe someday it could eventually even become the template equivalent of the awesome:

https://github.com/crdoconnor/strictyaml/blob/master/FAQ.rst

(Or maybe not. :-) )

**Comment by Keats** [comment]
Tera is based on [Jinja2](http://jinja.pocoo.org/docs/2.10/) and the [Django template engine](https://docs.djangoproject.com/en/2.0/topics/templates/) which represents 99% of the template engine used in the Python community so it's not a new thing.

There are template engines inspired by them in other languages:

- [Twig](https://twig.symfony.com) is based on Jinja2 for PHP 
- [nunjucks](https://github.com/mozilla/nunjucks) for JS
- Tera for Rust

I believe both Jinja2 and Liquid were inspired by [smarty](https://www.smarty.net/crash_course) and are very equivalent in terms of features, except that Jinja2 (and thus Tera) has a few more cool things like macros and math operations.

Tera is definitely not a groundbreaking template engine, you should be able to feed it templates from a random python project or some ansible playbook and it should roughly work, assuming there is no python code in them obviously.

**Comment by jwatt** [comment]
Nice, that's useful information, thank you. Maybe much of it could be added to https://tera.netlify.com/docs/templates/#templates ? If you don't agree, then feel free to close this issue of course. :)

**Comment by Keats** [comment]
It's mentioned on the homepage under the tagline already: http://tera.netlify.com (Based on Jinja2 and Django templates)
I don't really want to mention Liquid as I've never used it myself and don't want people getting the idea it's a port of Liquid
