### ISSUE TITLE
Add loop controls

### ISSUE THREAD

**Issue by Keats** [Keats/tera#267]
`break` and `continue`: see http://jinja.pocoo.org/docs/dev/templates/#loop-controls in Jinja2

This would avoid ugly things like https://github.com/Keats/book/blob/master/templates/page.html#L29-L43

**Comment by aluminous** [comment]
Hello @Keats , I'd like to work on this feature!

**Comment by Keats** [comment]
Go for it! Don't hesitate if you have any questions
