### ISSUE TITLE
feature request: built-in date global function to get the current timestamp

### ISSUE THREAD

**Issue by NuLL3rr0r** [Keats/tera#268]
Here is the use case: I would like my theme to update the copyright year automatically each time I generate my blog. I can do this with Hexo static generator. I'm aware of the built-in date filter which can be used to parse a timestamp on a page in Tera. But, I couldn't find a way to get the current timestamp inside a Tera template.

**Comment by Keats** [comment]
Adding a global function is sadly a potentially breaking change so it will need to wait the next major version.

**Comment by NuLL3rr0r** [comment]
OK, thank you for considering that.

**Comment by Keats** [comment]
Thinking about it, it's not a breaking change actually so i'll add it to the next version

**Comment by Keats** [comment]
@NuLL3rr0r any idea on the API?

You'd want to return the local datetime and/or the timestamp so I can the things like:

```
now() -> returns local datetime
now(timestamp=true) -> returns local timestamp
```
No format argument as the user can just call the date formatting filter if needed.
A `utcnow` could be added later if we don't want local datetime but utc instead?

**Comment by NuLL3rr0r** [comment]
Well, <code>utcnow</code> seems like a good idea to me and the default local date time should be fine in my opinion. And the timestamp parameter seems like a good addition to me.

It would also be great if it allows some formatting or returning part of the date (e.g. {{ now.Format "2006"}} or now.Year).

**Comment by Keats** [comment]
There's already a date filter so you can do `{{ now() | date(format="%Y") }}`. Not as pretty as `now.Year` but Tera is going through JSON which has no concept of datetimes sadly.
Duplicating the formatting to be in now/utc_now would be a bit unfortunate imo

**Comment by Keats** [comment]
Ended up grouping them and having `utc` be an argument: #295

**Comment by Keats** [comment]
@NuLL3rr0r You can try the `next` branch if you want to play with it, I think I'll do a release once #291 is done

**Comment by NuLL3rr0r** [comment]
Thank you so much! I'll try it.
