### ISSUE TITLE
Expressions for String Arrays

### ISSUE THREAD

**Issue by cetra3** [Keats/tera#274]
Not sure if this is currently possible in tera, but it would be nice to be able to create arrays.

```
{% set vars = ["A","B","C"] %}
```

Also in for loops it would be handy:

```
{% for var in ["A","B","C"] %}
{{var}}
{% endfor %}
```

**Comment by Keats** [comment]
Arrays creation is currently not supported anywhere in Tera: not in `set`, `for` or kwargs.

I believe adding it to `set` and `set_global` would be the priroity #1, then kwargs and last for `for`. It shouldn't be too hard to add if anyone wants to do it!

**Comment by Keats** [comment]
You can try the branch mentioned above if you want to play with it!
