### ISSUE TITLE
enable 'set_global' in variables

### ISSUE THREAD

**Issue by verpeteren** [Keats/tera#275]
According to the [documentation](https://tera.netlify.com/docs/templates/#assignments), global variables can be enabled in loops . Unfortunately, it is currently not possible to set variables in a macro (loop).

I am currently using the following hack to avoid code duplication.

#### Example macro

```jinja
{% macro is_it_special( iterable ) %}
     {% set_global myvar = "FALSE" %}                                                     
     {% for prop in iterable.properties %}
         {% if prop is containing("special_key") %}
             {% if prop.special_key.name == "special_value" %}
                 {% set_global myvar = "TRUE" %}
             {% endif %}
         {% endif %}
     {% endfor %}
     {{ myvar }}                                        
{% endmacro is_it_special %}
```

#### Example call

```jinja
{% set is_special = macros::is_it_special(iterable=nested_hashmap) | trim %}
{% if is_special == "TRUE" %}
   <h1>There is something special going on</h1>
{% endif %}
```

Please note the `TRUE`, 'FALSE' and the `trim` filter.

It would be very convient global variables can be set directly inside macros.
If this is not possible, an alternative would be to explicetly document that the macros allways return (whitespaced) strings.

**Comment by Keats** [comment]
The first line of the macros docs is:

> Think of macros as functions or components that you can call and return some text.

I could throw in `pure` but `set_global` usage is only meant to be in loops to avoid these kind of workarounds: https://stackoverflow.com/questions/30611762/set-flag-in-jinja2-loop-access-outside-of-loop

The main point of macros is that they are isolated in scope so I don't think it would make sense to allow setting global variables outside of it
