### ISSUE TITLE
Missing testers and filters with Rocket and Tera

### ISSUE THREAD

**Issue by alexandre-janniaux** [Keats/tera#279]
Hi,

I am failing at rendering a template with filters and testers, basically with ``json_encode`` and ``containing``, in a macro or not. It throws the following error when trying to render the page.

```
    => Error: Failed to render 'questionnaire.client': error while rendering a macro from the `fields` namespace
    => Error: Tester 'containing' not found 
```
What I understood is that they are registered by default in Tera, so I come here first to know if I did something wrong or not.

Thank you for your help.

**Comment by alexandre-janniaux** [comment]
I started to use the git version of rocket so as to use ``Template::custom`` and dump the Tera instance, and it seems that it solves the issue. I don't really understand why though, as the ``Default`` trait of ``Tera`` and its other constructors should correctly initialize the instance.

**Comment by Keats** [comment]
Which version was in the `Cargo.lock`? The `containing` test was added in 0.11.0 so maybe that's the reason? Or does it also happen with all the tests/filters?

**Comment by alexandre-janniaux** [comment]
I bumped to 11.6 in my Cargo.toml, did a cargo update + cargo build and checked the Cargo.lock to find a tera = "0.11.6" inside, but I believe I don't understand Cargo build system enough and I didn't check if I had two tera version in the Cargo.lock. 

I will test again the previous version of my code during the evening.

I had access to some filters (capitalize).

**Comment by alexandre-janniaux** [comment]
Actually, it seems to come from rocket_contrib, but I don't know how to override the dependency version of a dependency.

```
├── rocket_contrib v0.3.9
│   [dependencies]
│   ├── glob v0.2.11
│   ├── handlebars v0.28.3
│   │   [dependencies]
│   │   ├── lazy_static v0.2.11 (*)
│   │   ├── log v0.3.9 (*)
│   │   ├── pest v0.3.3
│   │   ├── quick-error v1.2.1 (*)
│   │   ├── regex v0.2.10 (*)
│   │   ├── serde v1.0.43 (*)
│   │   └── serde_json v1.0.16 (*)
│   ├── log v0.3.9 (*)
│   ├── rocket v0.3.9 (*)
│   ├── serde v1.0.43 (*)
│   ├── serde_json v1.0.16 (*)
│   └── tera v0.10.10
│       [dependencies]
│       ├── chrono v0.4.2 (*)
│       ├── error-chain v0.10.0 (*)
│       ├── glob v0.2.11 (*)
│       ├── humansize v1.1.0
│       ├── lazy_static v0.2.11 (*)
│       ├── pest v0.4.1
│       ├── regex v0.2.10 (*)
│       ├── serde v1.0.43 (*)
│       ├── serde_json v1.0.16 (*)
│       ├── slug v0.1.3
│       │   [dependencies]
│       │   └── unidecode v0.3.0
│       └── url v1.7.0 (*)
```

**Comment by Keats** [comment]
Looks like it's just rocket not using the latest version then, not Tera.
I don't know if it's possible to override a subdependency either
