### ISSUE TITLE
truncate should not append an ellipsis

### ISSUE THREAD

**Issue by jkcclemens** [Keats/tera#281]
See title. This is not the behavior I expect from something called `truncate`. A truncate function should just cut the string off at that length. Appending an ellipsis could be its own filter or (even better) handled by the user.

Basically, [this](https://github.com/jkcclemens/paste/blob/master/web/templates/base.html.tera#L123) should not be necessary.

**Comment by Keats** [comment]
Tera is mostly inspired by Django (https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#truncatechars) and Jinja2 (http://jinja.pocoo.org/docs/2.10/templates/#truncate) which have the ellipsis.

However, I should add the equivalent of the `end` parameter to the filter so you can do `end=""` and not have the ellipsis.
