### ISSUE TITLE
Support rendering strings templates with custom filters/tests 

### ISSUE THREAD

**Issue by alexandre-janniaux** [Keats/tera#282]
Hi,

Currently, the only way to render a string is either to use ``Tera::one_off`` function, which doesn't allow custom filters, or to write the string in a file and give the filename to Tera.

I'm in the case where users can use variables that, in my previous application, I transformed into values thanks to jinja by creating a new instance/context and registrating the allowed filters.

Is it planned to add this feature to Tera ?

**Comment by Keats** [comment]
Can you do that by creating a Tera instance first (`Tera::default`()) and add raw templates/filters?
Like https://github.com/Keats/gutenberg/blob/56335b125572dab86348b3d83e877da6e2b39a10/components/rendering/benches/all.rs#L91 except I don't add any filters there

**Comment by alexandre-janniaux** [comment]
Nice, I didn't understand it was possible, thank you !
