### ISSUE TITLE
truncate breaks multi-char graphemes

### ISSUE THREAD

**Issue by jkcclemens** [Keats/tera#286]
Hello! I return with another potential issue with `truncate`! You may not consider this in the scope of Tera to handle, but since I wrote my own function to safely truncate on grapheme boundaries, I thought it was worth mentioning.

See this [Rust Playground example](http://play.rust-lang.org/?gist=b80e9a75b4ee7dcdad7cd1d1b05d0ca3&version=stable&mode=debug). The current style (naive) works fine on everything but the last test, which actually produces a different emoji than was even in the source text.

**Comment by clarcharr** [comment]
Personally, I'd prefer a Unicode-aware truncation algorithm, although it might be best to defer that to something like the `unic` crate.

**Comment by jkcclemens** [comment]
Actually detecting the grapheme boundaries is not something Tera need do, since crates like [unicode-segmentation](https://crates.io/crates/unicode-segmentation) (used in the playground example) exist.

**Comment by clarcharr** [comment]
@jkcclemens That was mostly what I meant by deferring to another crate. Both the [`unicode-segmentation`](https://docs.rs/unicode-segmentation/1.2.1/unicode_segmentation/trait.UnicodeSegmentation.html#tymethod.grapheme_indices) and [`unic-segment`](https://docs.rs/unic-segment/0.7.0/unic_segment/struct.GraphemeCursor.html) crates offer some form of functionality like this.

Personally, I recommend the latter as it is more efficient; you simply have to do:

```
let mut gc = GraphemeCursor::new(trunc_len, s.len());
gc.next_boundary(s, 0);
```

**Comment by jkcclemens** [comment]
I'm not really sure why there's a split between `unicode-` and `unic-` crates, but for the record, `unicode-segmentation` also has a [`GraphemeCursor`](https://docs.rs/unicode-segmentation/1.2.1/unicode_segmentation/struct.GraphemeCursor.html) struct, which I didn't even know about! Thanks for pointing that out.

**Comment by clarcharr** [comment]
@jkcclemens The unicode-rs crates are not super maintained; the `unic` crate is actively maintained right now and I'd generally recommend using those if you need them for anything.

**Comment by jkcclemens** [comment]
@clarcharr Good to know!

Also, with further investigation, using a cursor like you mentioned above is just as bad as the `very_naive_truncate` function in the example. The offset is not in terms of graphemes but in terms of bytes, as mentioned in the documentation: "The `offset` parameter must be on a codepoint boundary.".

**Comment by Keats** [comment]
I'll take a PR for that!

**Comment by Keats** [comment]
Anyone willing to make that fix for the next version?

**Comment by clarcharr** [comment]
@Keats I may be able to get out a PR in a few days

**Comment by vdagonneau** [comment]
I noticed that I could tackle that bug easily. I made a patch for it. Here is the PR: #312

**Comment by Keats** [comment]
@clarcharr @jkcclemens happy with the PR above?

**Comment by jkcclemens** [comment]
Looks good to me!

**Comment by Keats** [comment]
It's in 0.11.11
