### ISSUE TITLE
Tera hangs whenever you insert a free opening brace 

### ISSUE THREAD

**Issue by alexander255** [Keats/tera#29]
This hangs tera in line 5:

    {% block title %}Index{% endblock title %}
    {% block head %}
        {{ super() }}
        <style type="text/css">
            .important { color: #336699; }
        </style>
    {% endblock head %}
    {% block content %}
        <h1>Index</h1>
        <p class="important">
          Welcome to my awesome homepage.
        </p>
    {% endblock content %}

Particularly the opening brace ("{") in the ".important { color: #336699; }" CSS statement, breaks the parser.

This example came straight from your front page. :wink:

**Comment by Keats** [comment]
Verry good point, didn't think of css at all

**Comment by alexander255** [comment]
Actually I tried to use tera as a processor for Rust: I had hit the limits of `macro_rules!` when doing double-substitution of parts of function and impl bodies. The same applies to CSS and JavaScript as well, of course.

**Comment by Keats** [comment]
That's fixed in master, will do release 0.1.1 with comments once #26 has landed

**Comment by daogangtang** [comment]
I meet it too.

**Comment by Keats** [comment]
Pushed 0.1.1 that should fix the issue

**Comment by daogangtang** [comment]
nice work.

**Comment by Keats** [comment]
Closing
