### ISSUE TITLE
Add wasm target

### ISSUE THREAD

**Issue by Keats** [Keats/tera#294]
AFAIK only chrono fails to compile so disabling/tweaking all date related filters/global functions should do the trick

**Comment by Keats** [comment]
So `cargo +nightly build --release --target wasm32-unknown-unknown` does build now.
The question is: what do I do now? Anyone has an idea?

**Comment by Keats** [comment]
A good idea would be a playground on the documentation site where you can write some templates, set some data and render it

**Comment by pickfire** [comment]
Is the idea of playground still valid? I wanted to try tera online but I can't seemed to find any playground yet to easily do that.

**Comment by Keats** [comment]
The wasm target works but there is no playground right now. It would be great though.
