### ISSUE TITLE
Fix error handling in Render

### ISSUE THREAD

**Issue by synlestidae** [Keats/tera#3]
This code sample, when placed in tests/templates/ (and added to the test suite)

`<h1>{{object.nonexistent_field}}</h1>`

causes the following error

`thread 'test_templates' panicked at 'called 'Option::unwrap()' on a 'None' value', ../src/libcore\option.rs:330`

It's pretty clear why -- render.rs is full of unsafe unwraps. @Keats you already know about this, but I thought I should file the first issue to track this.

**Comment by synlestidae** [comment]
To start, lookup_variable now returns an Option type: 886850369249741facdd820c5035b94c18b391fb. I expect that soon render will be able to capture when a variable lookup failed, and return an error like "so-and-so variable not initialized".

**Comment by Keats** [comment]
Thanks for that!
Lots of work to be done with error handling!

**Comment by Keats** [comment]
Error handling for rendering is now in master
