### ISSUE TITLE
Range function and variable arguments

### ISSUE THREAD

**Issue by vdagonneau** [Keats/tera#301]
Hello ! 

If I'm not mistaken I may have stumbled upon a bug in the range function. At the very least it has a counterintuitive (to me) behavior.

### Minimal code that works

```
extern crate tera;

use tera::{Context, Tera};

fn main() {
    let mut context = Context::new();
    context.add("ctx_start", &0);
    context.add("ctx_end", &3);

    let result = Tera::one_off(
        "{% for i in range(start=ctx_start, end=ctx_end) %}{{ i }}\n{% endfor%}",
        &context,
        true
    );
    println!("{}", result.unwrap());
}
```

### Minimal code that doesn't work

```
extern crate tera;

use tera::{Context, Tera};

fn main() {
    let mut context = Context::new();
    context.add("ctx_start", &0);
    context.add("ctx_end", &3);

    let result = Tera::one_off(
        "{% set set_end = ctx_start + 3 %}{% for i in range(start=ctx_start, end=set_end) %}{{ i }}\n{% endfor%}",
        &context,
        true
    );
    println!("{}", result.unwrap());
}
```

The only difference is when I set a variable in the template itself. Am I missing something ?

**Comment by Keats** [comment]
Note:

1. works normally
2. `set` returns a float and `end` only works with integers

The `range` function should try to parse it as int, that should be an easy fix if anyone is interested

**Comment by vdagonneau** [comment]
I took a dive into the code thanks to your pointers.

I think the problem is that both `eval_expr_as_number` and `eval_as_number` are working only on `f64` internally. Probably because the JSON number can be either `f64`, `u64` or `i64` ?

I am working on a commit to work with Number instead and stop casting every number back to an `f64`. It seems to work for now but breaks on `NaN` (divide by zero).

**Comment by Keats** [comment]
Thanks! If you do a PR, do it on the `next` branch
