### ISSUE TITLE
Dynamic template loading

### ISSUE THREAD

**Issue by GildedHonour** [Keats/tera#303]
How can I load and render template dynamically? That is, if I edit a template and reload a page without recompiling a project, the changes should be applied.

**Comment by Keats** [comment]
Where is the template stored, in a file? The way https://github.com/Keats/gutenberg does it is to watch the files for changes and call `tera.full_reload()` on the instance to re-parse all templates

**Comment by GildedHonour** [comment]
Yes, in a file

I meant - instead of compiling and reloading, can tera load a template only when it's requested?

**Comment by Keats** [comment]
You can load a template from a string using `add_raw_template{s}` but not only load a specific file no. Any reason you don't want to load all the templates?

**Comment by GildedHonour** [comment]
yes
when I want to change a template without having to recompile my project

**Comment by Keats** [comment]
then you will need to have some kind of file watcher like mentioned in https://github.com/Keats/tera/issues/303#issuecomment-397824237
Tera does not watch files directly so there are only 2 choices:

- have a 3rd party code watch files (https://github.com/Keats/gutenberg/blob/master/src/cmd/serve.rs for the hot reload Gutenberg uses)
- re-compile the project but that's going to be slow

**Comment by GildedHonour** [comment]
you didn't understand my question.

**Comment by Keats** [comment]
I'm still not sure what this means.

**Comment by GildedHonour** [comment]
You've not been thinking during these 1.5 years. I want you to think!
