### ISSUE TITLE
How to render a value which is optional depening on its state?

### ISSUE THREAD

**Issue by GildedHonour** [Keats/tera#306]
An option is passed into a template. How can I check if it's Some or None -- is_some() or is_none() -- if calling functions directly in a tera template isn't allowed?

**Comment by Keats** [comment]
If you want only Some/None:

```
{% if my_value is defined %} my_value is Some {% else %} my_value is None {% endif %}
```

If you don't mind falsy values counted as None (like `""`, `[]` etc), you can just use `{% if my_value %}{% endif %}`
