### ISSUE TITLE
Support for "is not" in tests

### ISSUE THREAD

**Issue by anowlcalledjosh** [Keats/tera#308]
Jinja2 supports using `is not` for tests, like so:

```html+jinja
{% if 4 is not divisibleby(2) %}
everything is broken
{% endif %}
```

It would be awesome if Tera could support the same! `if not 4 is divisibleby(2)` just doesn't look as nice :)

**Comment by Keats** [comment]
I'm still not sure about that, leaving it open to collect some feedback.

**Comment by jcgruenhage** [comment]
> `is not` does look better but with this change `if not 4 is not divisibleby(2)` would also be valid and that does look ugly :/

Sure, it gives people more options to make ugly expressions, but it also gives them options to avoid them, so I'd say this would be a change for the better.
