### ISSUE TITLE
Add support for negative length in `truncate`

### ISSUE THREAD

**Issue by codesections** [Keats/tera#313]
Many languages allow negative numbers in string-manipulation functions to index from the end of the string rather than the beginning, and it would be very helpful if the `{{ truncate }}` filter supported this behavior.  For example, it would be very nice to write:

```jinja2
{{ "Hello world!" | truncate(length=-1, end="") }}
```
and get `Hello world`.

Right now, you can get something similar with the much more verbose:

```jinja2
{% set len="Hello, world!" | length %}
{{ "Hello, world!" | truncate(length=len-1, end="") }}
```

**Comment by Keats** [comment]
I'm not sure it makes sense to have that, it's not that common to want to truncate to a string specific char number

**Comment by codesections** [comment]
The use case I was thinking about was more trimming the last few characters off of a string.  I encountered the issue when using the Gutenberg `current_path` variable, which ends with a trailing `/`.  Netlify removes this slash so I also wanted to remove it in my cannonicial links.  So I have:

```
    {%- set len = config.extra.live_base_url~current_path | length -%}
    <link rel="canonical" href="{{ config.extra.live_base_url ~ current_path 
    | truncate(length=len - 1, end="") }}">
```

That **particular** use case might be rare, but trimming the last `n` characters off of a string seems like it's a pretty common need.  For example, if structured data always ends with the same info, this could trim off the last field (or maybe trim off an email signature? Or a closing HTML tag?)

But, there is a work-around, so definitely not essential.

**Comment by Keats** [comment]
I don't think I'll add that but if anyone also wants it, please comment on that.
