### ISSUE TITLE
Concat string with integer

### ISSUE THREAD

**Issue by Txuritan** [Keats/tera#314]
It appears that you aren't able to concat a string with an integer. Not sure if this was intentional but the only way around it I've found was to send a vector of integers (basically replacing the range function).

What im trying to do:
```
{% for page in range(start=1, end=comic.pages) %}
<a href={{ "/c/" ~ page }}>Link</a>
{% endfor %}
```

**Comment by Keats** [comment]
The string concat was left intentionally simple to start with. It can be improved or for your usecase we could also add a `as_str` filter to convert other values into string.

**Comment by Txuritan** [comment]
I think a `as_str` filter would be better, to work around this I created a function that expands the number into a `Vec<String>`. This then causes a problem with if statements due to the type difference and I really don't was to pass in a separate Vector just for that.

**Comment by Keats** [comment]
I also think the `as_str` filter is better: the main reason I don't want to allow concatenating different types is to avoid at render time errors like `"/c/" ~ page` where `page would be an object and you would get `/c/[object]` or something. With the `as_str` filter, it could still happen but the user has to convert it to str explicitely first.

I'll take a PR for it, it seems pretty simple to implement

**Comment by Txuritan** [comment]
How should I handle maps and vectors, I was thinking of using the join filter for vectors but I'm not sure what I should do for maps.

**Comment by Keats** [comment]
Tera already has a way to transform values into str (https://github.com/Keats/tera/blob/master/src/context.rs#L93-L115) just use that one for consistency.

**Comment by Keats** [comment]
I feel like in the end it shouldn't error when concatenating string and integers at least so I'll add that for the next version

**Comment by Keats** [comment]
It's in 0.11.18
