### ISSUE TITLE
Feature request: add builti `| camel_case`, `| pascal_case` filters

### ISSUE THREAD

**Issue by matklad** [Keats/tera#315]
Hi!

I am using tera to generate [rust code](https://github.com/matklad/libsyntax2/blob/8d319ebb1c353c7de2c488826b93d0f7d6668686/src/ast/generated.rs.tera). It is awesome, but I need to be able to switch between `FN_ITEM` and `FnItem` styles of naming, and it would be cool if there were built-in filters for that. 

I can and do write my own filters for this, but I think "generating Rust code" is an awesome use-case for tera, so it might be a good idea to build this in :)

**Comment by Keats** [comment]
> I am using tera to generate rust code.

Neat :o 

Is there an existing crate that does all of that already?

**Comment by matklad** [comment]
>Is there an existing crate that does all of that already?

I am not sure what **all** here refers to :)

 For case conversions, there's an aptly-named [heck](https://crates.io/crates/heck).

For "using tera for codegen", I cobbled something together, but I think it should be possible to make a rather neat crate for this, if the need arises. Basically, you can have a pair of files `foo.rs.tera` and `foo.ron`, a template and the data for it in the [ron](https://github.com/ron-rs/ron) format. Then, a generic driver can process the sources tree and convert each .tera/.ron pair into .rs.

**Comment by Keats** [comment]
Sorry *all* was referring to case conversion here :) I might use those filters in https://github.com/Keats/kickstart as well actually

> For "using tera for codegen", I cobbled something together, but I think it should be possible to make a rather neat crate for this, if the need arises. Basically, you can have a pair of files foo.rs.tera and foo.ron, a template and the data for it in the ron format. Then, a generic driver can process the sources tree and convert each .tera/.ron pair into .rs.

That sounds really neat!

**Comment by Keats** [comment]
@matklad are you planning to do a PR or should I tag this issue as a good first issue?

**Comment by matklad** [comment]
> are you planning to do a PR 

unlikely :)

**Comment by Keats** [comment]
Having thought about it a bit more, I don't think it makes sense to add those to the default Tera as it isn't THAT common. 
It is pretty easy to add them yourself and Tera already has a pretty long list of dependencies.

**Comment by matklad** [comment]
Yep, it might make sense as a separate `tera-heck` crate or something.
