### ISSUE TITLE
Better error messages for macros

### ISSUE THREAD

**Issue by paulcmal** [Keats/tera#318]
When writing a macro (`banner::banner`), i encountered the case when i forgot to import the macro namespace into the current template, and was greeted by this error message:
```
Error: Failed to render pager 1
Reason: Failed to render 'mytheme/templates/index.html': error while rendering a macro from the `banner` namespace
Reason: Macro `banner` was not found in the namespace `banner`
```

If we'd like it to be more welcoming and user-friendly, we may consider adding another check [before](https://github.com/Keats/tera/blob/8f5c1f08c47816cf6e09df849284a5c042fdd762/src/renderer/mod.rs#L485) may to produce a more useful error message:
```
Reason: Macros namespace `banner` was not found in the current template. Have you maybe forgotten to import it, or misspelled it?
```

I tried to build gutenberg with a such modification but unfortunately failed for the moment (not because of the modification itself). I'll give it more time in the coming days :)

**Comment by Keats** [comment]
I would take a PR for that!

**Comment by Keats** [comment]
Added as part of a refactoring

**Comment by paulcmal** [comment]
Thanks! Sorry I was away/unavailable for a while :)
