### ISSUE TITLE
Empty tera instance?

### ISSUE THREAD

**Issue by iptq** [Keats/tera#324]
Is there a way to create an empty instance of Tera and manually add templates? I'm trying to pack templates into the binary and would like to be able to compile templates manually using `add_new_templates`.

**Comment by Keats** [comment]
`Tera::default` should do the trick and then https://docs.rs/tera/0.11.12/tera/struct.Tera.html#method.add_raw_templates

**Comment by iptq** [comment]
Ah, thanks. Guess I should always look in the foreign traits first
