### ISSUE TITLE
Reorganizing the docs?

### ISSUE THREAD

**Issue by paulcmal** [Keats/tera#332]
Hey i love the project but i feel like the docs could be so much easier to read through. I think the Templates page especially is just really full of stuff. That could be divided into separate sections and some stuff (like detailed filters/tests/functions docs) could be moved to separate pages to reduce cognitive overhead when you know what info you're looking for.

I don't have an idea yet for the whole organization of the docs, but for the templates page I'd propose a page (or section) organized like this:
```
# Templates

## Introduction

### Tera basics (comments, values, operations)
### Raw
### Whitespace control

## Data structures

### Literals
### Variables (+ link to assignments)
### Expressions

## Manipulating data

### Assignments
### Filters + list of built-in (+ link to more docs)
### Tests + list of built-in (+ link to more docs)
### Global functions + list of built-in (+ link to more docs)
→ Need more, use macros (link to macro section)

## Control structures

### Conditions (if)
### Loops (for)

## Template interactions

### Include
### Inheritance

## Extending templates

### Macros
### Custom global functions
### Custom tests
### Custom filters
```

What do you think?

That would mean changing the way the sidebar menu currently works, among other things. I'd be happy to contribute this and try and do more contributions to the docs. Thank you so much for building this amazing templating engine and taking the time to write basic documentation! <3 I hope we can work on making it clearer and more welcoming to newcomers :)

**Comment by Keats** [comment]
Thanks for the kind words!

I like having a single page, it makes CTRL+f easy. The original inspiration was http://jinja.pocoo.org/docs/2.10/templates/

The structure looks ok but a few things need to be changed imo:

- Inheritance should have its own ## level
- include is in control structure
- I kind of like having the built-ins at the end like in the Jinja2 doc so they don't clutter too much the middle of the page

**Comment by paulcmal** [comment]
Ok i'll start working on that :)

> I like having a single page, it makes CTRL+f easy.

That's not always true. I love to ^f around too, but when you have so much information on a single page you can get a lot of false positives and you have to scroll around (that's less of a problem if the menu is well-organized).

> The original inspiration

Those docs look good indeed. The main difference is there navigation menu goes a level deeper, but i think that's a big difference in terms of usability (given the organization of the content). If we can arrange to reorganize the pages making third-level heading more relevant, would you accept a PR to the current navigation menu?

> I kind of like having the built-ins at the end like in the Jinja2 doc so they don't clutter too much the middle of the page

I was thinking of simply listing them (a single phrase/line per entry) where it's relevant, but then having separate pages for each type of built-ins with more complete docs per entry (usage, etc). Would that be fine with you? I could also do the same but with the more complete docs just down the page, but i think it's important to have the list of built-ins when talking about filters/tests/functions because as a newcomer it gives you an idea what you can achieve with it without having to scroll around so much.
