### ISSUE TITLE
Child template cannot execute a macro defined in parent template

### ISSUE THREAD

**Issue by darakshan** [Keats/tera#333]
Fails in 0.11.14, worked in 0.11.12.
Relevant tests here: [main.rs.zip](https://github.com/Keats/tera/files/2361008/main.rs.zip)

**Comment by paulcmal** [comment]
I also ran into some weird macro problem today after upgrading gutenberg (pull & build from master). My problem is not that child templates cannot execute a parent's macro, but rather that the macro itself importing another macro seems to fail now.

```
Error: Failed to render section '/home/user/Site/content/donner/_index.md'
Reason: Failed to render 'mytheme/templates/section.html': error while rendering macro `banner::banner` (error happened in a parent template)
Reason: Macro namespace `utils` was not found in template `mytheme/templates/index.html`. Have you maybe forgotten to import it, or misspelled it?
```

It worked just fine before. But now it complains that the `banner` macro cannot run because the parent template (of the template calling the macro) hasn't imported the macros used (and imported) by `banner` itself. My macro file does have this line, and neither `index.html` nor `section.html` use the `utils` macros.
```
{% import "macros/utils.html" as utils %}
```

I feel like both may be related :)

**Comment by Keats** [comment]
The commit above should fix @darakshan issue.

Can you try with the `next` branch @paulcmal and post template samples if it doesn't work?

**Comment by Keats** [comment]
I *just* marked `Context::add` as deprecated, I'll need to fix those warnings in Gutenberg when I release 0.11.15.

Not sure what you are doing but if you want to use git version of Tera in Gutenberg, you will need to replace it in all Cargo.toml. The easiest way to check if something is fixed is to clone Tera and write a test, this way we also get a bonus test :D

**Comment by paulcmal** [comment]
> you will need to replace it in all Cargo.toml

You don't have any other idea by any chance? That's already the case :)
```
tera = { git = "https://github.com/keats/tera", branch = "next" }
```

```
user@laptop:gutenberg$ grep -r "tera = \"" *
user@laptop:gutenberg$ 
```
↑ The same command used to return i believe 7 Cargo.toml files to edit :)

> we also get a bonus test :D

That's a great bonus indeed! I was planning on writing a dedicated test, but to be honest i feel more comfortable testing it "in the real world" first and then writing the test. Maybe i'll try the other way around lol

**Comment by Keats** [comment]
> ↑ The same command used to return i believe 7 Cargo.toml files to edit :)

Returns 9 files for me.

> That's a great bonus indeed! I was planning on writing a dedicated test, but to be honest i feel more comfortable testing it "in the real world" first and then writing the test. Maybe i'll try the other way around lol

Another way is to paste the templates involved (simplified) and I'll write the tests :D

**Comment by paulcmal** [comment]
> Returns 9 files for me.

Indeed that was the number!

> I'll write the tests :D

I'm already working on it :D

**Comment by paulcmal** [comment]
The test I came up with fails also in `next`. Here's what I got:
```
#[test]
fn macro_can_load_macro_from_child() {
    let mut tera = Tera::default();
    tera.add_raw_templates(vec![
        ("submacros", "{% macro emma() %}Emma Goldman{% endmacro emma %}"),
        ("macros", "{% import \"submacros\" as submacros %}{% macro hommage() %}{{ submacros::emma() }} was an amazing person!{% endmacro hommage %}"),
        ("parent", "{% block main %}Adolf Thiers was a terrible person!{% endblock main %} Don't you think?"),
        ("child", "{% extends \"parent\" %}{% import \"macros\" as macros %}{% block main %}{{ macros::hommage() }}{% endblock main %}")
    ]).unwrap();

    let result = tera.render("child", &Context::new());
    assert_eq!(result.unwrap(), "Emma Goldman was an amazing person! Don't you think?".to_string());
}
```

It produces:
```
---- renderer::tests::macros::macro_can_load_macro_from_child stdout ----
	thread 'renderer::tests::macros::macro_can_load_macro_from_child' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Msg("Failed to render \'child\': error while rendering macro `macros::hommage`"), State { next_error: Some(Error(Msg("Macro namespace `submacros` was not found in template `child`. Have you maybe forgotten to import it, or misspelled it?"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })', libcore/result.rs:945:5
```

**Comment by Keats** [comment]
It should be fixed in the `next` branch

**Comment by paulcmal** [comment]
Thank you :heart: 

Do you think you will release the new version soon, or should i manually downgrade the tera version in gutenberg in the meantime?

**Comment by paulcmal** [comment]
I confirm it works like a charm, thanks :)
