### ISSUE TITLE
Accessing an array through loop.index seems not to work

### ISSUE THREAD

**Issue by zoosky** [Keats/tera#334]
```
        {% set ics = ["fa-rocket","fa-paper-plane","fa-diamond","fa-signal"] %}
        {% for a in ics %}
        {{ ics[loop.index] }}
        {% endfor %}

```
This is only needed when mixing two same size arrays in a for-loop.

**Comment by Keats** [comment]
It's actually one of the most classic programming error: off by one.
`loop.index` is 1-indexed so Tera will try to do `ics[4]` which is out of bounds and gives the error message. The error message is generic as by the time we're doing a lookup we don't know anymore it's an index, it has been converted to a json pointer.

**Comment by zoosky** [comment]
Should this work?

````
        {% set ics = ["fa-rocket","fa-paper-plane","fa-diamond","fa-signal"] %}
        {% for a in ics %}
            {% set i = loop.index -1 %}
            {{ ics[i] }}
        {% endfor %}
´´´
The error: Reason: Variable ics[i] can not be evaluated because: Variable `i` not found in context while rendering 'page.html'

**Comment by Keats** [comment]
Which version are you using? I just added the exact same code as test and it passes

**Comment by Keats** [comment]
Either way, I've updated the error message for your first case and it will say:

> Variable `ics[loop.index]` not found in context while rendering \'tpl\': the evaluated version was `ics.4`. Maybe the index is out of bounds?

instead.

**Comment by zoosky** [comment]
I use gutenberg 0.4.1 from brew.

**Comment by Keats** [comment]
Ah that would be the reason I guess. 
Gutenberg 0.4.2 contains the latest version of Tera which had a completely rewritten renderer which fixed quite a few bugs like that along with a 1.5-4x speed increase!

**Comment by Keats** [comment]
0.4.2 is already out; I don't know how homebrew releases happen though

**Comment by zoosky** [comment]
I saw the the release two hours ago and checked with brew. Just checked again. Still 0.4.1.

**Comment by paulcmal** [comment]
@zoosky Just for the record there's also `loop.index0` to address this use-case, as specified in the [tera docs](https://tera.netlify.com/docs/templates/#for) :)
