### ISSUE TITLE
set_global broken in macros

### ISSUE THREAD

**Issue by paulcmal** [Keats/tera#336]
Hi, I believe the `set_global` function doesn't work as it should in macros. It does define the variable in the parent's context, but it is not accessible from the macro context. The most simple way to reproduce is:
```
{% macro test_global() %}
    {% set_global output = "Gutenberg!" %}
    {{ output }}
{% endmacro test_global %}
```

Produces:
```
Error: Failed to render page '/home/user/Site/content/_common/footer.md'
Reason: Failed to render 'mytheme/templates/page.html': error while rendering macro `macros::test_global` (error happened in a parent template)
Reason: Variable `output` not found in context while rendering 'mytheme/templates/widgets/macros.html'
```

The value is accessible from `page.html` and `index.html` though (the former extends the latter).

PS: Here the `error happened in a parent template` is inaccurate. We're not exactly extending the template that failed, but rather importing it so the wording probably should be different :)

EDIT: I'm running gutenberg 0.4.2 and tera 0.11.5

**Comment by paulcmal** [comment]
I came up with two test cases:
```
#[test]
fn macro_can_redefine_global_context() {
    let mut tera = Tera::default();
    tera.add_raw_templates(vec![
        ("parent", "{% import \"macros\" as macros %}{{ macros::test_global() }}{{ value1 }}{{ value2 }}"),
        ("macros", "{% macro test_global() %}{% set_global value1 = \"42\" %}{% for i in range(end=1) %}{% set_global value2 = \" is the truth.\" %}{% endfor %}{% endmacro test_global %}")
    ]).unwrap();

    let result = tera.render("parent", &Context::new());
    assert_eq!(result.unwrap(), "42 is the truth.");
}

#[test]
fn macro_can_access_redefined_global_context() {
	let mut tera = Tera::default();
	tera.add_raw_templates(vec![
		("parent", "{% import \"macros\" as macros %}{{ macros::test_global() }}-{{ value1 }}-{{ value2 }}"),
		("macros", "{% macro test_global() %}{% set_global value1 = \"ACAB\" %}{% for i in range(end=1) %}{% set_global value2 = \"1312\"%}{% endfor %}{{ value1 }}-{{ value2 }}{% endmacro test_global %}"),
	]).unwrap();

	let result = tera.render("parent", &Context::new());
	assert_eq!(result.unwrap(), "ACAB-1312-ACAB-1312");
}
```

The first one runs fine on gutenberg 0.11.5. The second one doesn't, fails with:
```
failures:

---- renderer::tests::macros::macro_can_access_redefined_global_context stdout ----
	thread 'renderer::tests::macros::macro_can_access_redefined_global_context' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Msg("Failed to render \'parent\': error while rendering macro `macros::test_global`"), State { next_error: Some(Error(Msg("Variable `value1` not found in context while rendering \'macros\'"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    renderer::tests::macros::macro_can_access_redefined_global_context

test result: FAILED. 308 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by Keats** [comment]
(╯°□°）╯︵ ┻━┻

The first one is buggy, `set_global` should be restricted to the current macro and not allowed to modify the template global context (macros have a fully separated context).

The second one is failing correctly, `value1` and `value2` are only set in the macro and don't exist in the global context.

That should be pretty easy to fix the first one if you want to try!

**Comment by Keats** [comment]
```
{% macro test_global() %}
    {% set_global output = "Gutenberg!" %}
    {{ output }}
{% endmacro test_global %}
```

is definitely a bug as well though

**Comment by paulcmal** [comment]
> macros have a fully separated context

So if I get it, there's two contexts: there's shared global context among macros, and among regular templates, but not in between them? Sorry the [set_global docs](https://tera.netlify.com/docs/templates/#assignments) were not very instructive about what kind of "global" we're talking about: site-wide, template-wide, namespace-wide…

I'll rewrite the tests accordingly and try to mess around with the bugs if i can :)

**Comment by paulcmal** [comment]
The tests in the PR all pass woohooo! But I'm not sure whether I understood properly how global a global context should be ^^

**Comment by Keats** [comment]
> So if I get it, there's a shared global context for most templates, and each macro gets its own? Or is set_global always template-wide? Sorry the set_global docs were not very instructive about what kind of "global" we're talking about: site-wide, template-wide, namespace-wide…

So in short when you're rendering the template, you have one global rendering context: what the user gave as `Context`. You can add to that by using `set` or `set_global`. For loops get their own local context as well, because a `set` in a forloop will be only valid during the iteration. To allow setting values in the global context from within a `forloop`, you can use `set_global instead.

Macros are effectively mini-templates so they get a global context equivalent to their arguments and `set`/`set_global` can only add to their own context: macros are never allowed to interact in any way with the original global context.

**Comment by paulcmal** [comment]
> one global rendering context

So the global context is shared between parent/child templates, correct?

Thanks for taking the time to explain! :)
