### ISSUE TITLE
Hashmap key access

### ISSUE THREAD

**Issue by Riamse** [Keats/tera#339]
It doesn't seem clear from https://tera.netlify.com/docs/templates/#data-structures whether Tera is able to use `variable[k]` or `variable.k` to access things from a hashmap (e.g. if `variable = HashMap::new()`), only arrays/lists and tuples. Does tera support these?

**Comment by Keats** [comment]
Should work yes, although `.k` is limited to valid Tera identifiers so if it's not the case, `[k]` is a better choice.
