### ISSUE TITLE
length filter returns different values for string?!

### ISSUE THREAD

**Issue by paulcmal** [Keats/tera#341]
I think i just stumbled on a bug (yet again :D). Apparently, when assigned to a variable, the length of a string can be different than the value you get when calling `{{ variable | length }}` directly. I encountered this when dealing with HTML output generated by gutenberg (i.e. splitting a page in several parts).

How to reproduce:
```
{% set string = "&lt;p&gt;" %}
{{ string | length }}
{% set size = string | length %}
{{ size }}
{{ string | length }}
```

Produces:
```
17

9
17
```

That's a super weird thing happening here :boom:

**Comment by Keats** [comment]
It's kind of expected but not very intuitive. You will get the right value by doing `string | safe | length`.
The reason is that `set` automatically marks the value as `safe` to avoid having to escape the right hand side so `{{ size }}` is the equivalent of `{{ string | safe | length }}`

**Comment by paulcmal** [comment]
Thanks for the explanations! I'll write some docs about this. How does the number 17 come up though? It's not twice the number of chars. From my testing, i'd say that escaped characters count twice; is that the case?

How about truncate in this case? Is it the same that I should probably pass the `safe` filter on it first? And also that it's not the case when i use it in a `set` statement? If so, i guess it's sort of advised when dealing with escaped content to assign the value to a variable before running filters?

**Comment by Keats** [comment]
>How does the number 17 come up though? 

Escaping `&lt;p&gt;` gives `&amp;lt;p&amp;gt;` which has 17 characters.

`safe` should be used almost everywhere in HTML/XML templates except in `set` or in condition/loops
