### ISSUE TITLE
Redefining value in loop breaks the loop?

### ISSUE THREAD

**Issue by paulcmal** [Keats/tera#342]
Hey, here's another weird bug! When i try to redefine the current value in a for loop, the value on the next iteration gets stuck on the one i just redefined. Here's an example:

```
{% set string = "abcdefghdijklm" | split(pat="d") %}
{% for i in string %}
    {% set i = i ~ "lol" %}
    {{ i }}
{% endfor %}
```

This produces : ` abclol abclollol abclollollol `. I'm expecting `abclol efghlol ijklmlol` as output.
Removing the `set i` line produces `abc efgh ijklm` (as expected).

Some weird stuff :D

**Comment by Keats** [comment]
Looks like a bug in the forloop stack! It might be an interesting first dive for someone interested in contributing, there's even the testcase!

**Comment by paulcmal** [comment]
Thanks for the fix! :+1:
