### ISSUE TITLE
Variable name used in for loop is ignored

### ISSUE THREAD

**Issue by danno131313** [Keats/tera#344]
When I make a for loop in a template, the variable name I use is completely ignored and property access works for any variable name I want, as long as the field is there.

For example:
```
{% for comment in comments %}
    <p>{{ comment.content }}</p>
    <p>{{ whocares.content }}</p>
    <p>{{ doesntmatter.content }}</p>
```

All three p tags would display the exact same content.

Using latest version of Tera and Rust 1.29 stable on Arch Linux.

**Comment by Keats** [comment]
whoa that's weird, needs to be fixed along #342
