### ISSUE TITLE
Expressions involving functions

### ISSUE THREAD

**Issue by vojtechkral** [Keats/tera#348]
Some expressions that involve function calls don't work
One such example is math operations on numbers:

```jinja2
{% set a = 3 %}
{% set b = a + func_returning_integer() %}
```

This throws an unimplemented panic in `src/renderer/processor.rs:661`

The workaround is to use an intermediate variable:

```jinja2
{% set a = 3 %}
{% set tmp = func_returning_integer() %}
{% set b = a + tmp %}
```

Another similar code is with string concatenation:

```jinja2
{% set a = "abc" %}
{% set b = a ~ func_returning_string() %}
```

This one fails to parse, the workaround is the same.

I'm not sure if this is by design or an implementation limitation, but I'd say at least the first one should work...

**Comment by Keats** [comment]
That's a bug - well an unimplemented thing really. It should be easy to fix

**Comment by Keats** [comment]
Both should be fixed in the `next` branch if you want to try

**Comment by vojtechkral** [comment]
@Keats Yes, it works now. Thanks!
