### ISSUE TITLE
Truncate end part seems to be not wroking

### ISSUE THREAD

**Issue by steadylearner** [Keats/tera#349]
I am following example of in [official example](https://tera.netlify.com/docs/templates/#introduction)

```
{{ value | truncate(length=10, end="") }}
```

But it concats **...** in every case instead of what defined inside **end="               "** part

**Comment by Keats** [comment]
Which version of Tera are you using? There are tests covering that and I just tried it in both tests and templates and both worked.

**Comment by steadylearner** [comment]
I am using tera = "0.11.18" for Visual Studio Code shows that it is the lastest version.

I used this two samples inside two curly brackets with Lorem Texts.

**| truncate(length=5, end="")**
**| truncate(length=10, end="++++++")**

but result in browser is 

 **accus…**
**et est at …**

So I think that end part is not working properly inside my app.

I am using 

Dependencies such as 

[dependencies]
# server and database
rocket = "*"
rocket_codegen = "0.3.17"
diesel = { version = "1.3.3", features = ["postgres", "r2d2", "chrono"] }

# serialize and deserialize
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
"
# template and markdown extension
tera = "0.11.18"

[dependencies.rocket_contrib]
default-features = false
features = ["tera_templates"]

Somewhat like this inside Firefox_Developer Version Browser.

I like your crate for having better documentation for others. Hope we can find better solution for this.
and thanks for the fast response.

**Comment by Keats** [comment]
I am really confused, if I try to render `{{ "Lorem Ipsum blabla blabla" | truncate(length=5, end="**") }}` I get Lorem** as expected.
Is it possible to make a small project or test reproducing the issue?

**Comment by steadylearner** [comment]
**I have uploaded files to [git repository](https://github.com/steadylearner/tera_truncate_with_rocket) so that you can test it easily.**

If you couldn't find any problem with this. I will ask help to Rocket crate author.

Browser - Firefox Developr Version(inside Linux 16.04)

**Comment by Keats** [comment]
So this repo is actually using tera 0.10: https://github.com/steadylearner/tera_truncate_with_rocket/blob/master/Cargo.lock#L551 which is almost 20 versions behind by now and the `end` parameter was added in one of those.
It looks like you will have to wait until rocket_contrib 0.4 is released

**Comment by steadylearner** [comment]
Then, I will wait for the new release of the Rocket Crate. 

**You can close this issue and thanks for the explanation and fast responses.**
