### ISSUE TITLE
Could compile_templates be a function?

### ISSUE THREAD

**Issue by daboross** [Keats/tera#351]
Right now `compile_templates` is declared as a macro, but it doesn't seem to do anything that requires being a macro. Is there anything blocking it being a function instead?

It seems like this:

```rust
#[macro_export]
macro_rules! compile_templates {
    ($glob: expr) => {{
        match $crate::Tera::new($glob) {
            Ok(t) => t,
            Err(e) => {
                println!("Parsing error(s): {}", e);
                ::std::process::exit(1);
            }
        }
    }};
}
```

Could equivalently be this:

```rust
pub fn compile_templates(dir: &str) -> Tera {
    match Tera::new(dir) {
        Ok(t) => t,
        Err(e) => {
            println!("Parsing error(s): {}", e);
            ::std::process::exit(1);
        }
    }
}
```

This would have the advantage of simplicity, reduce the apparent "magic" of `compile_templates`, give better documentation with a type signature, and not require `#[macro_use]`.

**Comment by Keats** [comment]
`compile_templates!` will be completely removed for 1.0  as it is not really useful imo

**Comment by daboross** [comment]
Alright, thanks.
