### ISSUE TITLE
Document importance of relative path for compile_templates macro

### ISSUE THREAD

**Issue by danielpclark** [Keats/tera#359]
One of the examples: 

https://github.com/Keats/tera/blob/9a869af290093cd707f5d9880535a7731e94d58e/examples/actix/src/main.rs#L40

shows using an absolute path for rendering templates.  This works on my local machine but when I deploy to Heroku then Tera can't find the templates.

    thread 'gotham-worker-5' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Msg("Template \'landing_page/index.html.tera\' not found"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', libcore/result.rs:1009:5

Switching from absolute path to relative path in my code allows it to now work on Heroku.

These are the lines of relative paths that work.

     compile_templates!("app/views/**/*.tera");
     TERA.render("landing_page/index.html.tera", &context).unwrap();

And using

    concat!(env!("CARGO_MANIFEST_DIR"), "/app/views/**/*.tera");

Causes it to fail just on Heroku.

**Comment by Keats** [comment]
The `compile_templates` macros is getting removed for 1.0.0

**Comment by danielpclark** [comment]
Okay.  Would you mind letting me know what the preferred practice is then?  Thanks.

**Comment by Keats** [comment]
I haven't really done any kind of web dev in Rust yet but I would probably do something like https://github.com/getzola/zola/blob/master/components/templates/src/lib.rs#L30-L51 to have everything in the binary. A bit repetitive if you have many though.

Otherwise I would use relative paths like ` compile_templates!("app/views/**/*.tera");` rather than using the `concat` approach. The example should probably remove `concat` if it causes issues

**Comment by danielpclark** [comment]
Path and hashmap wise it's the same as the macro.  The key difference would be storing the template strings inside the binary rather that reading the file on request.  If the point is to store the templates in the binary could we not just change the `compile_templates!` macro to do that?

I kind of like using the macro and would be fine with the change to internally storing the templates.

I'll be writing a blog post tomorrow with the Gotham web framework using Tera for templates, Webpack for assets, and deploying to Heroku.  Depending on when my editor publishes it will be out in a week or a month.  Just wanted to make sure I'm not recommending any usage of this project which this project is against.

**Comment by Keats** [comment]
I would use Tera::new then. Something like https://github.com/Keats/tera/blob/v1/examples/basic/main.rs#L15-L24
