### ISSUE TITLE
Avoid allocations

### ISSUE THREAD

**Issue by Keats** [Keats/tera#364]
Right now, the `Context::insert` method converts a value to JSON value and it seems to be cloned when passing the context to the `render` method.

It would be ideal to store in `Context` the data before converting (ie as `dyn Serialize`) but this is not possible. There might be a way to do that but I don't know any right now.

Another solution could be for `Tera::render` to take a Context by value instead of a `T: Serialize` so we can grab the data. It would disallow rendering with something other than a `Context` but we could add functions to still provide that if needed. If I'm not reading this wrong, it would be a win in terms of allocations too big to ignore.

**Comment by Keats** [comment]
@andy128k you're better at traits than me, do you see any way we can store values pre-conversion in the context?

**Comment by andy128k** [comment]
@Keats This sounds similar to what I was talking about [here](https://github.com/Keats/tera/issues/340#issuecomment-440013422). Currently I'm experimenting in [this branch](https://github.com/Keats/tera/compare/v1...andy128k:value-trait).

**Comment by Keats** [comment]
It's a bit different as the change I'm talking about is purely for the current context.
If you manage to have your branch working I would be super impressed/happy!

**Comment by andy128k** [comment]
@Keats I had no chance to work on it. I hope next week I'll have time.

**Comment by Keats** [comment]
No worries, I'm just super curious to see if ti's going to work :p

**Comment by Keats** [comment]
@andy128k I see you have made more changes since the last time I checked, do you think it's going to work overall?

**Comment by Keats** [comment]
How would that look from a user perspective? Compared to the current `Serialize` automatic derive

**Comment by andy128k** [comment]
serde_json::Value will still be possible to use, but built-in types like i32, String, Vec, HashMap are also usable.

**Comment by Keats** [comment]
Can I help in some ways?

**Comment by andy128k** [comment]
Looking at amount of changes and amount if changes to do, I would say, this experiment failed. :(
A lot of efforts and risks to break something with questionable outcome.

This approach allows to clone less but has also drawbacks. Pass `String` by reference is good thing but doing the same for `i32`,  is a total waste of resources (fat pointer is 4 times larger). Implementation of filters also becomes much trickier (Do we expect customers of Tera to write their own filters?).

Json also adds some simplifications. Having single number type is a big deal. Should `nth` filter accept `u32`, or only `usize`? What about `i32`?

IMHO, `serde_json::Value` could stay (unless you really want to have DateTime as first-class citizen or distinguish integers and floats).

**Comment by Keats** [comment]
The main issue is that `serde_json` serialization is the bottleneck of https://github.com/getzola/zola both in speed and memory usage. That's because there are many pages with a big string (the content) dwarfing everything else. I expect the perf loss from fat pointers to integers to not matter in comparison.

I do agree that JSON simplify some things, my only issue with it is the cloning needed to render a template that cannot be avoided

**Comment by andy128k** [comment]
I see two directions to move here:
1. focus on performance and try to clone less, by using references as much as possible. Here benchmarks should help.
2. introduce own `Value` type. Serialization/deserialization is not needed if generic From/Into implementations will be provided.

**Comment by Keats** [comment]
The main issue with `serde-json` is that it will clone when serialising. It's fine for small data but if you have a section with thousands of pages in Zola, that's going to be painful. Part of the issue is some Tera function that might be solved with the new traits, I still need to test it.

**Comment by Keats** [comment]
The commit above is what I had in mind when creating the issue. This will not reflect in benchmarks however as we need to clone it there but in practice it will mean lower memory usage.

Tracking memory/allocations is done using heaptrack on the `bench` example:

```bash
$ cargo build --release --example bench
$ heaptrack target/release/examples/bench               
```
Still shows 10k temp allocations in `Processor::render_body` but at least the memory consumed is down by 1/3.
This still needs to clone the full object though. In this case a 100x100 integer table is not too bad on the memory but there will be issues in Zola when you fetch an object with 100+ blog post length string content since it WILL need to be serialised to JSON, which means allocating lots of memory.

I'm not sure whether you've seen https://github.com/Keats/tera/issues/340#issuecomment-445287866

**Comment by Keats** [comment]
@andy128k are you still working on that? I see some changes from the 28

I will add another bench example with a string-heavy template to represent a more common Zola usecase.

Regarding allocations, I believe we could use `write!` to bypass some allocations.
For example, the `examples/bench` will do current number -> string -> push to string result 10k times (the number of integer variables in the context`. This seems a bit wasteful.

**Comment by Keats** [comment]
Another potential improvement is to try to make https://github.com/Keats/serde-tera work with `Cow` for the strings if it's possible. It would also allows us to have our own Value types, which means we could have SafeString as well that do not require escaping

**Comment by Keats** [comment]
https://github.com/maciejhirsz/ramhorns is a very interesting take, a bit similar to what you were doing @andy128k with the trait no?

**Comment by andy128k** [comment]
@Keats Yes, it looks similar. But it is much easier to implement this for mustache-templates than for jinja-templates. There is no filters in mustache, no tests (this is even in its motto "Logic-less templates"). All transformations are done before context is passed to template engine.

**Comment by lukexor** [comment]
I may be a bit late to this topic, but I just started on my Rocket/Tera implementation after some time off and this change breaks compatibility with rocket_contrib and it doesn't seem like they've noticed or updated any of their documentation on the matter.

Their Template::render method still expects a Seralizable object, which tera::Context is no longer.

https://api.rocket.rs/v0.4/rocket_contrib/templates/struct.Template.html#method.render

I also noticed the Tera documentation isn't up to date with this new handling of context either. It still recommends passing a borrow to context.

https://tera.netlify.com/docs/

With that said - I'd like to continue using tera::Context - however, I'm unsure how to use the tera.render function with Rocket. If that question is better asked over on a Rocket thread, I'll move over there to ask. For a quick work around I'm just using HashMaps but it's not as flexible as tera::Context.

**Comment by Keats** [comment]
Passing a borrowed context is still the main way to use of Tera::render. If you want to pass a `Serialize` value, you can use https://docs.rs/tera/1.0.2/tera/struct.Context.html#method.from_serialize
rocket_contrib is on a year old release of Tera so it's probably just out of date.

**Comment by jebrosen** [comment]
Hi! I'm a little late to this issue, but the removal of `Serialize` was a bit confusing when it was reported to us (<https://github.com/SergioBenitez/Rocket/issues/1236#issuecomment-589486907>). The relevant method in rocket works with either `tera` or `handlebars` and therefore still needs `T: Serialize`; for tera it goes through `from_serialize`.

Is there any harm in `Context` implementing `Serialize` again, even if it's not used directly by `tera`? `Context::insert` still requires `T: Serialize` for the data anyway. I might be missing something in regard to which operations are more/less expensive now, but it seems to me that having `impl Serialize for Context` wouldn't make performance any worse than it already is in these scenarios.

**Comment by Keats** [comment]
The render_* methods only works with `Context` and not `Serialize` anymore so I don't think it would help this issue? You would need to rebuild a `Context` from the Serialize value (as a `Value` or not). Unless the idea is to do Context that impl Serialize -> recreate new Context with Context::from_value?

**Comment by Keats** [comment]
Implementing Serialize by hand shouldn't break anything, I'll take a PR for it
