### ISSUE TITLE
Lots of filters and functions, where should they go?

### ISSUE THREAD

**Issue by RealOrangeOne** [Keats/tera#365]
I'm thinking of adding a load of filters to Tera, specifically so I can use them in [`zola`](http://github.com/getzola/zola), but wondering where they should be implemented? It'd be great if Tera was much more like a batteries-included template engine!

1. In `tera`
2. In `zola`
3. In, say, a separate `tera-contrib` package

Filters i'm thinking of, Many of them _stolen_ from https://gohugo.io/functions/:

- base64 encode / decode (exists in `zola` currently)
- MD5 / SHA1 / SHA256
- Exposing [`std::hash`](https://doc.rust-lang.org/std/hash/trait.Hash.html#tymethod.hash)
- Reading environment
- Basic file IO? Maybe
- https://github.com/jiri/rust-emojicons
- Random number generation / choice / shuffle etc
- Lorem ipsum generator
- JSON pretty print
- regex comparison

The contrib package idea has the benefit of not requiring additional dependencies and binary bloat when the filters aren't necessary. Although does add additional dependencies to other projects, which isn't necessarily ideal.

**Comment by Keats** [comment]
There is a `json_encode` with a `pretty` parameter in Tera. 
There is also a `matching` filter that takes a regex.

For the others, I wouldn't put them in Tera itself, they seem pretty niche

**Comment by Keats** [comment]
Some of those can be added in Zola though, not 100% certain about all of them though
