### ISSUE TITLE
Update v1 branch to 2018 edition

### ISSUE THREAD

**Issue by Keats** [Keats/tera#367]
Since we're already bumping versions in that branch, might as well bump it once more...

**Comment by opilar** [comment]
I'd like to work with this issue

**Comment by opilar** [comment]
Seems I should run `cargo fix` only and it will do all work. Am I right?

**Comment by Keats** [comment]
In theory yes I think, but I haven't used `cargo fix` at all myself

**Comment by caemor** [comment]
See https://rust-lang-nursery.github.io/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html for more informations about it. But in short just run the commands from LFalch

**Comment by opilar** [comment]
There is no use `dyn` for trait objects in the current codebase. Should we use it?

**Comment by opilar** [comment]
@Keats look at [dyn trait for trait objects](https://rust-lang-nursery.github.io/edition-guide/rust-2018/trait-system/dyn-trait-for-trait-objects.html)

**Comment by LFalch** [comment]
That is also covered in https://rust-lang-nursery.github.io/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html#writing-idiomatic-code-in-a-new-edition

**Comment by opilar** [comment]
@LFalch year, but `cargo fix --edition-idioms` does nothing.
