### ISSUE TITLE
URLs fall victim to the default escape_html function's overagressive escaping

### ISSUE THREAD

**Issue by iirelu** [Keats/tera#368]
When setting a URL via a template variable, the obvious answer is to use `<a href="{{ url }}">`, but this is subtly wrong in a way that arguably doesn't really matter. Thanks to [`tera::escape_html`](https://docs.rs/tera/0.11.20/tera/fn.escape_html.html) escaping even `/` (as recommended by OWASP), what would otherwise look like `<a href="/foo/bar">Example</a>` instead looks like `<a href="&#x2F;foo&#x2F;bar">Example</a>`. This continues to work, at least on all modern browsers, but needlessly escaping unreserved characters in URLs is recommended against by everything I can find.

The obvious answer to this is to use `{{ url | safe }}`, but that's overkill, and potentially serves as another vector for bugs and attacks by letting *all* unescaped characters through. A filter like "url_safe" might work, but I don't know the answer.

**Comment by iirelu** [comment]
Thinking more, I think an `attr_escape` would work best, something that marks it as safe and only escapes `"` and `'`.

**Comment by Keats** [comment]
I kind of like the idea of having a single `escape` personally, so we could add something like `escape(type="js")` if we want to have built-in support for escaping other format than HTML. It's already possible to give Tera your own escape fn but it means you cannot mix html/js rendering for example. Not sure how common this is.

**Comment by iirelu** [comment]
Honestly, unless any evidence of lone forward slashes being able to single-handedly cause malformed HTML or be a possible attack vector can be found, I think it might just be best to not escape `/`s.

While looking for information about it I stumbled across [this stackexchange post](https://security.stackexchange.com/questions/49852/why-should-xss-filters-escape-forward-slash) which offers a good rationale for escaping forward slashes. That does make things tougher.

Still, OWASP itself recommends a different set of escaping rules for "complex attributes like href, src, style, or any of the event handlers like onmouseover". Reading more, I see it actually explicitly states that URLs should be escaped differently from other attributes, meaning that once again I think a simple `url` filter could do the job. Sure, it could be longer like `escape(type="url")` but that's not the kind of thing that's fun to type dozens of times in a row, and this is a pretty safety-critical thing.

Another argument for a `url` filter is that it could possibly perform some URL validation, and print out warnings (or errors) when the given input is an invalid URL.

**Comment by Keats** [comment]
Can you write the potential doc of the `url` filter in the issue to make sure we agree on the design? Seems like it can/should be added with the next release.

**Comment by iirelu** [comment]
Sorry, a bout of leukemia has knocked me out of action. I can't really help with this any more.

**Comment by Keats** [comment]
:o Sorry to hear that, hope you get better

I'll add it to the v1 later

**Comment by Keats** [comment]
Looks like the URL filter could use the https://docs.rs/percent-encoding/1.0.1/percent_encoding/ crate

**Comment by Keats** [comment]
I think I completely forgot that there already is a `urlencode` filter? So we can just do `urlencode | safe` for urls and it should be fine

**Comment by randomairborne** [comment]
```{{ variable | urlencode | safe }}``` will escape colons in the protocol, which breaks most URLs.
