### ISSUE TITLE
[Feature Request] Ability to create an empty Tera instance

### ISSUE THREAD

**Issue by kinnison** [Keats/tera#371]
Hi,

I wish to create an empty Tera instance as I intend to load *all* my templates from a database (ideally on demand, but I'm happy to load them all up-front.

I can't find a way to do this without giving Tera a glob known to not match anything which seems somewhat counterproductive.  The internals seem to be set up to cope with a lack of glob internally
but I can't find a sane way to create such an instance.  Is there one?

Thanks,

Daniel

**Comment by Keats** [comment]
`Tera::default()` should do what you want

**Comment by kinnison** [comment]
Of course it should.  I can't believe I didn't even look for that :/

Sorry to have asked such a silly question :-)

**Comment by kolloch** [comment]
Just found this here. Just to say that I also missed it.
