### ISSUE TITLE
Document how to include templates in compiled binary?

### ISSUE THREAD

**Issue by evitalis** [Keats/tera#372]
I recently wrote an application using tera and for some reason, even when `include = ["templates/*]" in my Cargo.toml my code cannot find the templates when run outside of the project directory.

Did I miss in the documentation how to accomplish this, and if not is it something that can be added?

When I run `cargo package` I can see the templates in the crate, but when I `cargo install` my project and run it is when I see the errors.

**Comment by Keats** [comment]
The way I do it  personally is a `lazy_static` Tera instance like in: https://github.com/getzola/zola/blob/master/components/templates/src/lib.rs#L30-L51

**Comment by evitalis** [comment]
@Keats Using `include_str!()` seemed to help just fine. Thank you.
