### ISSUE TITLE
split lines with split filter

### ISSUE THREAD

**Issue by areux** [Keats/tera#373]
I was playing with `zola` templates and needed to split this body into lines:

```plain
{% alert() %}
multi
ple
lines
{% end %}
```
I tried `{{ body | split(pat="\n") }}` but it didn't do anything, apparently `"\n"` or `'\n'` doesn't get passed to pat argument as a single line feed character from html template.

my workaround was to register a filter myself: 

```rust
pub fn lines(value: Value, _args: HashMap<String, Value>) -> TeraResult<Value> {
    let s = try_get_value!("lines", "value", String, value);
    Ok(to_value(s.lines().collect::<Vec<_>>()).unwrap())
}
```
I don't know much about html and I just yesterday found out about static site generators and subsequently zola and tera :smile:. what am I missing?

**Comment by Keats** [comment]
I have just added a test for splitting on `\n` on the `v1` branch and it does seem to work.
It might be related to shortcodes itself, I'll have a look after the festivities

**Comment by Keats** [comment]
I'm confused, adding a test to Tera with the exact same context/template as in your zola example works:

```rust

#[test]
fn split_on_context_value() {
    let mut tera = Tera::default();
    tera.add_raw_template(
        "split.html",
        "{{ body | split(pat='\n') }}",
    ).unwrap();
    let mut context = Context::new();
    context.insert("body", "multi\nple\nlines");
    let res = tera.render("split.html", context);
    assert_eq!(res.unwrap(), "[multi, ple, lines]");
}
```

but the same template rendering fails in Zola, despite having the same context. I'll have a look tomorrow, I must be missing something obvious x)

**Comment by Keats** [comment]
Found the issue: serde_json will escape `\n` into `\\n` which will not split since there isn't `\\n` in the string.

**Comment by Keats** [comment]
Not entirely sure what to do.
One thing could be to not use serde-json and switch to our own format (something like https://github.com/Keats/serde-tera) in Tera itself. More code to maintain but we might be able to do something faster/more specific than serde-json allows.
