### ISSUE TITLE
Add tests to ensure parser requires whitespaces

### ISSUE THREAD

**Issue by Keats** [Keats/tera#379]
Seen on pest gitter:

```
Armin Ronacher
@mitsuhiko
Jan 10 17:12
is there something like a word boundary thing I can use in pest?
foo { "partial" ~ identifier } also matches on "partialfoo" instead of what i want: "partial foo"
(i thought i would steal from tera's grammar for the solution but even tera parses {% foritem in seq %} as an alias for {% for item in seq %})

.... 

Dragoș Tiselice
@dragostis
Jan 10 22:01
@mitsuhiko, WHITESPACE needs to be present in such cases, i.e. "partial" ~ WHITESPACE ~ identifier. This is because ~ considers WHITESPACE as completely optional. #333 will make this more flexible in that you will be able to force ~ to contain at least one whitespace.

...

yeah. i get that
my issue was actually that when i switched to ${} i forgot to add ! to inner expressions
that was not entirely obvious
ident = !{ XID_START ~ XID_CONTINUE* } partial_block = ${ "partial" ~ WHITESPACE ~ ident ~ WHITESPACE? ~ object_def_body } object_def_body = !{ "{" ~ fields ~ "}" }
```

Full discussion is https://gitter.im/pest-parser/pest?at=5c376ef8317e2407cd0e3651
In short it means that `{%- ifname %}` will be considered valid

This is not intended and should be fixed on the v1 branch.
The first step is to have failing tests for all this kind of missing whitespace issue and then fix the grammar. It could be a nice occasion to clean up the grammar at the same time, there are enough tests that it should be fairly safe to do big changes.

**Comment by Keats** [comment]
Here is the related test:


```rust
// https://github.com/Keats/tera/issues/379
#[test]
fn lex_requires_whitespace_between_things() {
    let inputs = vec![
        "{% filterupper %}hey{% endfilter %}",
        "{% fora in b %}{{a}}{% endfor %}",
        "{% for a inb %}{{a}}{% endfor %}",
        "{% ifi18n %}世界{% else %}world{% endif %}",
        "{% ifi18n %}世界{% eliftrue %}world{% endif %}",
        "{% blockhey %}{%endblock%}",
        "{% macrohey() %}{%endmacro%}",
        "{% setident = 1 %}",
        "{% set_globalident = 1 %}",
        "{% extends'base.html' %}",
        "{% import 'macros/image.html' asimage %}",
        "{% import'macros/image.html' as image %}",
    ];

    for i in inputs {
        let res = TeraParser::parse(Rule::template, i);
        println!("{:?}", i);
        assert!(res.is_err());
    }
}
```

if someone wants to get started on that.

**Comment by Keats** [comment]
@dragostis what would be the best way to fix this? Is there a change for that coming in the next release of pest?

**Comment by dragostis** [comment]
The next version of pest will have explicit whitespace, so it will be very obvious where whitespace can be used and where it must be used. But until then, an easy way to fix this is to simply lookahead and make sure that when you match a keywords, the following character is not alpha, for example. Something like `keyword ~ !alpha`.

**Comment by dragostis** [comment]
There's quite a bit more work to do, yes. I'm trying to gather more feedback during the design phase in order to have a really solid 3.0 release.

**Comment by Keats** [comment]
Doing something like `keyword ~ !alpha` fails, maybe my syntax is a bit too funky https://github.com/Keats/tera/blob/v1/src/parser/tera.pest

**Comment by dragostis** [comment]
Forgot to mention, but `keyword ~ !alpha` should be in an atomic rule. Another solution can be to force a whitespace in after the keywords that expect identifiers after them, e.g. `"... block" ~ WHITESPACE ~ ident ...`.

**Comment by Keats** [comment]
That works but the fact that I cannot combine `_!` is a bit annoying as this means I need to add `!{..}` intermediate wrapper for some rules now.
I have seen it mentioned in some pest issues but that would be nice to have that working
