### ISSUE TITLE
globwalk does not work with absolute paths

### ISSUE THREAD

**Issue by sunjay** [Keats/tera#380]
I filed an [issue about this in globwalk](https://github.com/Gilnaa/globwalk/issues/18), but I feel like people might run into it here like I did so I'm opening an issue.

I was writing code along the lines of the below:

```rust
let absolute_path_from_config = ...;
let pattern = absolute_path_from_config.join("*.html");
let tera = Tera::new(pattern);
```

And it was just not working. I even had the `glob` crate (for separate reasons) loading the same pattern. It printed out the right paths with no issue.

I did some investigation and realized that the `globwalk` crate itself doesn't work when the path is absolute.

If the `globwalk` crate isn't fixed in time, a workaround may be to use the `glob` crate itself. I'm not super familiar with the code, so I'll leave that decision to you. :)

**Comment by Keats** [comment]
That's good to know, I guess it's a block for the v1 release then.

**Comment by sunjay** [comment]
Looks like a fix has already been made. Could you go to the linked issue and test the fix for the author? You know tera better than I do. :)

**Comment by Keats** [comment]
Can you add a test for absolute paths in the v1 branch? Otherwise i'll do it this weekend and try the fix then

**Comment by sunjay** [comment]
> Can you add a test for absolute paths in the v1 branch?

Sorry, I won't have a chance to do that.

> Otherwise i'll do it this weekend and try the fix then

Thanks! Sorry I can't do more. :)

**Comment by Keats** [comment]
Added a failing test for now, the patch in globwalk will fix it for real

**Comment by sunjay** [comment]
Thank you!
