### ISSUE TITLE
Errors are not sync

### ISSUE THREAD

**Issue by Arnaz87** [Keats/tera#381]
I'm using tera in a project where I'm also using rlua, but rlua uses for it's errors the failure crate, which is not directly compatible with standard rust errors. They do have though a compatibility option that converts rust errors to failure errors, but it expects the base errors to be send+sync, and it seems tera errors aren't.

**Comment by Keats** [comment]
Is it Tera 0.11? The next version (1.0.0) will have plain Error struct instead of `error-chain` so that will work

**Comment by mitchtbaum** [comment]
> Is it Tera 0.11? 

Yes.

> The next version...

Is there a list of changes somewhere?

**Comment by Keats** [comment]
> Is there a list of changes somewhere?

https://github.com/Keats/tera/blob/v1/CHANGELOG.md#100-unreleased

There might be other changes but that's at least 90% of it

**Comment by mitchtbaum** [comment]
:pray:

**Comment by Arnaz87** [comment]
It's still not send, it can't be unless [the source field](https://github.com/Keats/tera/blob/7189735eb5c4aef225dd3a5294ddf21f5c2fb5fa/src/errors.rs#L47) is also sync+send, but I don't know if all errors ever are, most should be though.

**Comment by Keats** [comment]
Doing a blanket unsafe impl Send & Sync only for a third-party crate seems a bit odd though, is that what `failure` recommends?

**Comment by Arnaz87** [comment]
I didn't mean `unsafe impl Send/Sync`, I meant `source: Option<Box<dyn StdError + Send + Sync>>`, I don't know if that's possible with rust but it's not unsafe, just that if for some weird reason, some crate has non-send-sync errors, it will stop working.

I don't know what failure recommends, they just say they're by default incompatible with std errors.

**Comment by Keats** [comment]
Afaik you cannot implement StdError if you add Send + Sync

**Comment by Keats** [comment]
So what's missing for the v1 branch to work with `failure`?

**Comment by mitchtbaum** [comment]
I'm pretty sure it's okay now.  rlua removed it in their latest version.

**Comment by Keats** [comment]
Closing then

**Comment by 64** [comment]
I don't believe it is solved. I'm using the `1.0.0-beta.6` release.

Using this:

```rust
#[derive(Debug, Fail)]
pub enum Error {
    #[fail(display = "template error: {}", _0)]
    Template(tera::Error),
}
```

Generates the error:
```
error[E0277]: `(dyn std::error::Error + 'static)` cannot be shared between threads safely
  --> src/app.rs:39:17
   |
39 | #[derive(Debug, Fail)]
   |                 ^^^^ `(dyn std::error::Error + 'static)` cannot be shared between threads safely
   |
   = help: the trait `std::marker::Sync` is not implemented for `(dyn std::error::Error + 'static)`
   = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<(dyn std::error::Error + 'static)>`
   = note: required because it appears within the type `std::boxed::Box<(dyn std::error::Error + 'static)>`
   = note: required because it appears within the type `std::option::Option<std::boxed::Box<(dyn std::error::Error + 'static)>>`
   = note: required because it appears within the type `tera::Error`
   = note: required because it appears within the type `app::Error`

error[E0277]: `(dyn std::error::Error + 'static)` cannot be sent between threads safely
  --> src/app.rs:39:17
   |
39 | #[derive(Debug, Fail)]
   |                 ^^^^ `(dyn std::error::Error + 'static)` cannot be sent between threads safely
   |
   = help: the trait `std::marker::Send` is not implemented for `(dyn std::error::Error + 'static)`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(dyn std::error::Error + 'static)>`
   = note: required because it appears within the type `std::boxed::Box<(dyn std::error::Error + 'static)>`
   = note: required because it appears within the type `std::option::Option<std::boxed::Box<(dyn std::error::Error + 'static)>>`
   = note: required because it appears within the type `tera::Error`
   = note: required because it appears within the type `app::Error`
```

**Comment by Keats** [comment]
Isn't that a bug in failure that it isn't compatible with errors from the standard library? Is failure still maintained?

**Comment by 64** [comment]
It seems to be more of an intentional design choice than a bug.
