### ISSUE TITLE
group_by key stringification behavior

### ISSUE THREAD

**Issue by jondlm** [Keats/tera#383]
It would be nice if the `group_by` filter only performed stringification on non-string keys. An example should highlight this nicely:

Template context:

```
[
  {"id": 1, "group": "a"},
  {"id": 2, "group": "b"},
  {"id": 3, "group": "c"},
  {"id": 4, "group": "a"},
  {"id": 5, "group": "b"},
  {"id": 6, "group": "c"},
  {"id": 7, "group": "a"}
]
```

Template:

```
{% for group, things in something | group_by(attribute="group") %}
{{group}}
{% endfor %}
```

Actual output:
```
"a"
"b"
"c"
```

Desired output:
```
a
b
c
```

I already have a passing test case and PR ready to submit but I wanted to check if you're open to this change before I submit it.

**Comment by Keats** [comment]
Looks fine, the current output do seem buggy to me
