### ISSUE TITLE
Add line/offset information to Error type

### ISSUE THREAD

**Issue by sunjay** [Keats/tera#391]
Since you're moving away from error-chain for v1, would it also be possible to have information in the errors about where in the template the error occurred? 

It would be very neat if errors like "Failed to parse 'one_off`" included more information about where exactly the parse error occurred. Even just an offset/index into the source file text would allow me to produce nicer errors that actually show the area where the problem occurred.

I know pest provides some [`Span` information](https://docs.rs/pest/2.1.0/pest/struct.Span.html), so maybe you could take advantage of that?

**Comment by Keats** [comment]
That's already the case? Errors are chained so you will need to iterate through their sources to get the full error, which contains the span information. Zola does it like this: https://github.com/getzola/zola/blob/next/src/console.rs#L94-L103

**Comment by sunjay** [comment]
Awesome! Thank you!
