### ISSUE TITLE
accessing keys and values of a map

### ISSUE THREAD

**Issue by tcurdt** [Keats/tera#393]
I am trying to access the keys of hashmap and then lookup via keys. But I am a little lost when looking at the docs. This is what I tried:

```
{% set map = section.pages | group_by(attribute="year") %}
{% for year in map.keys() | reverse %}
  {% set posts = map[year] %}
```

**Comment by Keats** [comment]
Tera templates cannot execute Rust code like `.keys()` and there is no way to iterate only on the keys of a hashmap, it could be an interesting improvement though.

Taking the context of your issue in Zola, something like that might work:

```jinja2
{% set map = section.pages | group_by(attribute="year") %}
{% set_global years = [] %}
{% for year, ignored in map %}
  {% set_global years = years | concat(with=year) %}
{% endfor %}
{% for year in years | reverse %}
   {% set posts = map[year] %}
{% endfor %}
```

Not great but we don't have the luxury of using Python like Jinja2/Django :/

**Comment by tcurdt** [comment]
Wow, that's really really ugly :) but thanks for the work around!
I don't understand why the `global` is necessary though.
And yes - exposing the keys and values as arrays would be a nice addition then.

**Comment by Keats** [comment]
> I don't understand why the `global` is necessary though

`set` is local, so calling `set` in a forloop only sets the value for the current iteration, which isn't what we want here. This is is to avoid having to use workarounds like https://stackoverflow.com/questions/9486393/jinja2-change-the-value-of-a-variable-inside-a-loop

**Comment by tcurdt** [comment]
Oh, OK. Wasn't aware that jinja2 has such ugly corners, too. Thanks for the explanation.
