### ISSUE TITLE
Add support for Django's {% empty %} in for-loops

### ISSUE THREAD

**Issue by mxmerz** [Keats/tera#395]
I am missing support for an `{% empty %}` statement in for-loops. I know the [`{% empty %}` statement](https://docs.djangoproject.com/en/2.1/ref/templates/builtins/#for-empty) from Django's templating language:

> The for tag can take an optional {% empty %} clause whose text is displayed if the given array is empty or could not be found:
> 
> ```
> <ul>
> {% for athlete in athlete_list %}
>     <li>{{ athlete.name }}</li>
> {% empty %}
>     <li>Sorry, no athletes in this list.</li>
> {% endfor %}
> </ul>
> ```

**Comment by Keats** [comment]
I think I would rather wrap the forloop in a if rather than add the `empty` statement to keep things simple

**Comment by mxmerz** [comment]
Wrapping the `for`-loop in an `if` is, of course, possible – but template authors would have to do this for practically _every_ `for`-loop. 

``` django template
<ul>
{% if athlete_list is defined and athlete_list|length > 0 %}
	{% for athlete in athlete_list %}
		<li>{{ athlete.name }}</li>
	{% endfor %}
{% else %}
	<li>Sorry, no athletes in this list.</li>
{% endif %}
</ul>
```
For my taste, this is too much boilerplate code in the template.

**Comment by Keats** [comment]
I'll take a PR for it
