### ISSUE TITLE
[Possible bug?] Is there an ability to index a tuple inside a vector?

### ISSUE THREAD

**Issue by Figments** [Keats/tera#397]
So I have a vector of type `Vec<(String, i32, String)>` that I want to use to pass information about a user's comment (namely the username, id, and avatar filename), but Tera doesn't currently support tuples that exist inside vectors, so every time I try to load the template trying to index a position within that inner tuple, the template crashes.

**Comment by Figments** [comment]
For added clarification, the issue crops up whenever iterating over a vector containing tuples and trying to reference the specific parts of that tuple. For example, assume there’s a variable `comments` with the type `Vector<(String, String String)>`:

```
{% for comment in comments %}
    {{ comment.0 }}
    {{ comment.1 }}
    {{ comment.2 }}
{% endfor %}
```

This will fail with an error reading “cannot find item comment.0 in template” or something along those lines (will update with the actual error when I’m at my computer), despite the fact that those items do exist within the tuple `comment`. 

This happens when using Tera through Rocket’s integration, if that helps any.

**Comment by Figments** [comment]
Never mind. Managed to figure out the problem.

**Comment by Keats** [comment]
What was the issue? How did you fix it?

**Comment by Figments** [comment]
It was an issue with how I was declaring the variable to get pushed to the template, not an issue with the template itself.
