### ISSUE TITLE
Pluralize should take an optional prefix

### ISSUE THREAD

**Issue by 64** [Keats/tera#402]
Some more complex words like 'category' can't be pluralized using the current `pluralize` filter. It should do what django does and accept an optional prefix so that you can do something like:

	categor{{ 1 | pluralize(prefix="y", suffix="ies") }}

which results in:

	category

**Comment by Keats** [comment]
Agreed. Although the names of the arguments might need to be bikeshedded a bit

**Comment by 64** [comment]
Oh, yeah, prefix definitely isn’t the right word here.

How about ‘singular’ and ‘plural’? You could also keep ‘suffix’ as a synonym for plural to prevent it being a breaking change.

**Comment by Keats** [comment]
There is a v1 branch so breaking changes are fine there.
