### ISSUE TITLE
Adding a new function for Context to build it from serde_json::Value?

### ISSUE THREAD

**Issue by magiclen** [Keats/tera#406]
Currently the `Context` has `into_json`, but it does not have any functions like `from_json`.

Using the `insert` method to input data from `serde_json::Value::Object(serde_json::Map)` costs too much.

**Comment by Keats** [comment]
Would the signature be `Context::from_json(obj: Value) -> Result<Context>`? There is also the `TryFrom` trait that could be used but it would push the min version of Rust to 1.34, which is ok.

**Comment by Keats** [comment]
@magiclen can you have a look at https://github.com/Keats/tera/pull/409 ?

**Comment by magiclen** [comment]
Awesome! That is very good for me.
