### ISSUE TITLE
TeraError should be public

### ISSUE THREAD

**Issue by FuGangqiang** [Keats/tera#41]

**Comment by Keats** [comment]
It's public in master, I'll release a new version when pest releases 0.4, I'm currently running on a branch for it

**Comment by FuGangqiang** [comment]
oh, yes
I didn't check the master

**Comment by Keats** [comment]
I just published 0.1.3 that has public error types

**Comment by FuGangqiang** [comment]
Thanks for Reminding，
and glad to see it.
