### ISSUE TITLE
How to ignore specified file (like .DS_Store) at compile_templates 

### ISSUE THREAD

**Issue by linca-apricot** [Keats/tera#413]
I want to ignore .DS_Store at compile_templates.
but i couldn't find a way in a document.

https://tera.netlify.com/docs/usage/#usage

```
templates/
  .DS_Store
  index.html
  index.json
```

```rust
let tera = compile_templates!("templates/**/*");
```

```
* Failed to read template '"templates/.DS_Store"'
stream did not contain valid UTF-8
```

**Comment by Keats** [comment]
In the v1 you can specify globs so you can use `templates/**/*.{html,json}` for example

**Comment by linca-apricot** [comment]
Thanks. Using this method, if index.yml, index.edn, and more are added, I have to add more extension in every time.

```
templates/**/*.{html,json, yml, edn, ...}
```

I want to exclude files like below.

```
compile_templates!("templates/**/*").exclude(".DS_Store");
or
compile_templates!("templates/**/*").exclude(".*");
```

is there no way to ignore?

**Comment by Keats** [comment]
Loooks like it is possible in `globwalk` (https://docs.rs/globwalk/0.7.1/globwalk/#advanced-globbing) but not with the current interface which takes a `&str`

**Comment by linca-apricot** [comment]
I tried exclude pattern. It works.
https://unix.stackexchange.com/questions/164025/exclude-one-pattern-from-glob-match
```
compile_templates!("templates/**/[!.]*");
```
