### ISSUE TITLE
Processing time is increased even with unused values

### ISSUE THREAD

**Issue by linca-apricot** [Keats/tera#414]
I inserted &Vector<Document> (1000over elements) to a Context.
I don't use the ref documents, but  processing time is increased.
Why?
I expect that context has reference of documents (don't have copy), and if i don't use the parameter it does not significantly affect processing time.

### Template (JSON)
site.docs is unused.
```
 "site": {
    "total_posts": {{ site.total_docs }}
 },
```

### With context.insert("docs", &docs);
Context
```rust
// docs: Vec<Document>
// docs.len() is 1000over

let mut context = Context::new();
context.insert("docs", &docs);
context.insert("total_docs", &docs.len());
```

```bash
cargo run --release (9.028s)
```

### Without context.insert("docs", &docs);
Context
```rust
// docs: Vec<Document>
// docs.len() is 1000over

let mut context = Context::new();
// context.insert("docs", &docs);
context.insert("total_docs", &docs.len());
```

```bash
cargo run --release (0.848s)
```

**Comment by linca-apricot** [comment]
insert() does not affect.
```rust
let start = Instant::now();
context.insert("docs", &docs);
let end = start.elapsed();
println!("{}.{:03} sec", end.as_secs(), end.subsec_nanos() / 1_000_000);
// => 0.000 sec
```

render() does some process if a parameter in context is unused.

```rust
let start = Instant::now();
let rendered = self.tera.render(&template, &context)
                        .expect("Failed to render template");
let end = start.elapsed();
println!("{}.{:03} sec", end.as_secs(), end.subsec_nanos() / 1_000_000);
// => 0.050 sec
```

**Comment by Keats** [comment]
In v1, `render` takes a context by value but you will still pay the cost of serializing even if you don't use the variables, as it would require the interpreter to track all variables usage.
The main issue here is that Tera serializes values to JSON and operates on that, not structs, so it doesn't know about references.

**Comment by linca-apricot** [comment]
I got it.

https://github.com/Keats/tera/blob/7b75481de3c0d23cabff5fe3fac1ee90bd99802e/src/tera.rs#L309

tera.render() method always convert `data: &T` to value.

```rust
context.insert("docs", &docs);
for d in &docs {
    let rendered = self.tera.render(&template, &context)
                            .expect("Failed to render template");
}
```

convert context first, and then pass to render method.
```rust
let value = to_value(&docs)?;
let template = self.get_template(template_name)?;
for d in &docs {
    let renderer = Renderer::new(template, self, value);
    renderer.render();
}
```

dont't use tera.render().
use Renderer::new() and render().

**Comment by Keats** [comment]
Make sure you look at the v1 version, quite a few changes there and very close to 1.0 release

**Comment by linca-apricot** [comment]
OK, I check the v1 version. I look forward to release v1.

https://github.com/Keats/tera/blob/v1/src/tera.rs#L302

tera.render() always call context.into_json().

```rust
pub fn render(&self, template_name: &str, context: Context) -> Result<String> {
```

I want to pass not only Context but also Value.
```rust
pub fn render(&self, template_name: &str, value: Value) -> Result<String> {
```

anyway, thanks!

**Comment by Keats** [comment]
There is https://docs.rs/tera/1.0.0-beta.9/tera/struct.Context.html#method.from_value for that

**Comment by linca-apricot** [comment]
Thanks! I will try using 1.0.0-beta.9.

**Comment by linca-apricot** [comment]
I tried.
It didn't work well, but I will think a little more.
Please let me know if other interfaces are exist. If it has no interface, it does not matter.

### Version

Cargo.toml
```toml
tera = "1.0.0-beta.9"
```

https://github.com/Keats/tera/blob/v1/src/tera.rs#L302

```rust
pub fn render(&self, template_name: &str, context: Context) -> Result<String> {
    let template = self.get_template(template_name)?;
    let renderer = Renderer::new(template, self, context.into_json());
    renderer.render()
}
```

### context.into_json() is called 1000over times.

docs is `Vec<Document>` that has 1000over document.
`into_json()` is called 1000over times.

```rust
// not one doc. I want to insert docs to all outputs.
context.insert("docs_all", &docs);
for doc in &docs {
    context.insert("doc", doc);
    let rendered = tera.render(&template_name, context)
                       .expect("Failed to render template");
}
```

### I want to call context.into_json() one time, and pass it to loop.

```rust
use tera::renderer::Renderer as TeraRenderer;

pub fn render_by_value(&self, template_name: &str, value: Value) -> Result<String> {
    let template = tera.get_template(template_name)?;
    let renderer = TeraRenderer::new(template, tera, value);
    renderer.render()
}
```

```rust
// not one doc. I want to insert docs to all outputs.
context.insert("docs_all", &docs);
let value = context.into_json();
for doc in &docs {
    let rendered = tera.render(&template_name, value.clone())
                       .expect("Failed to render template");
}

```

but I can't use private tera::renderer::Renderer.

```rust
error[E0603]: module `renderer` is private
 --> src/renderer.rs:8:11
  |
8 | use tera::renderer::Renderer as TeraRenderer;
  |           ^^^^^^^^
```

**Comment by Keats** [comment]
Sorry you lost me a bit there.

You have > 1000 documents and you want to render a template for each.
In these templates, you want `doc`, the current document and `docs_all` all the documents right?
An obvious first question is why do you need the full list of docs for a single doc template.

For the API bit, it looks like you could use a `Context::insert_value` that takes a `(&str, Value)` as param? Something like:

```rust
context.insert("docs_all", &docs);
for doc in docs {
    let mut ctx2 = Context::new();
    ctx2.insert("doc", doc);
    ctx2.extend(context.clone();
    let rendered = tera.render(&template_name, ctx2)
                       .expect("Failed to render template");
}
```
Or convert `docs` to `Value` before and iterate on the inner doc Value in a `match` with the `insert_value` function no?

**Comment by linca-apricot** [comment]
Sorry, I'm not good at explaining (and not good at english).

>In these templates, you want doc, the current document and docs_all all the documents right?

Yes.

>An obvious first question is why do you need the full list of docs for a single doc template.

For example, I use full list of docs for a single doc template.
```
{
  "total_posts": {{ docs | length }},
  "recent_posts": {{ docs | take(n=5) | json_encode }},
  "doc": {{ doc | json_encode }}
}
```

>For the API bit, it looks like you could use a Context::insert_value that takes a (&str, Value) as param? Something like:

```rust
context.insert("docs_all", &docs);
for doc in docs {
    let mut ctx2 = Context::new();
    ctx2.insert("doc", doc);
    ctx2.extend(context.clone();
    let rendered = tera.render(&template_name, ctx2)
                       .expect("Failed to render template");
}
```

current my code is like above.
and 1000times `context.into_json()` in `tera.render()`  takes a very long time.
if i remove `docs_all`, It will end soon.

**Comment by linca-apricot** [comment]
> Or convert docs to Value before and iterate on the inner doc Value in a match with the insert_value function no?

Maybe, I want it like this.

```rust
context.insert("docs_all", &docs);
let mut value = context.into_json();
for doc in value { // I don't know Value is iterable and can be inserted.
    value.insert("doc", doc);
}
// don't call render. I want to pass the value. I don't want to call into_json().
// is there render_by_value?
let rendered = tera.render_by_value(&template_name, value)
                       .expect("Failed to render template");
```

**Comment by Keats** [comment]
render is only by value. `tera.render(&template_name, Context::from_value(value))`.
I'll have a look later today or tomorrow if I can have an example of a working sample

**Comment by linca-apricot** [comment]
Thanks Thanks!
Sorry, The title of issue is already different from the current question.

My current questions is
`context.into_json()` in `render(&self, template_name: &str, context: Context)` takes long time to process in loop. I want to speed up it.

https://github.com/Keats/tera/blob/v1/src/tera.rs#L302

I will look at the code at tera and serde more.

**Comment by Keats** [comment]
That's normal, serializing to Value clones all strings. If your document objects have a lot of text, it's going to take time

**Comment by linca-apricot** [comment]
my document objects have a lot of text.

my first question is
>I expect that context has reference of documents (don't have copy)
and answer is
> serializing to Value clones all strings

OK, I understood.
(I didn't want to clone strings, wanted to have reference to docs.)

I will think about a good way to avoid to clone a lot of text.
Thanks!

**Comment by linca-apricot** [comment]
I think it is almost the same issue https://github.com/Keats/tera/issues/364

**Comment by Keats** [comment]
> I think it is almost the same issue #364

It is but I haven't figured out a way to make that work yet.
The most efficient way to render your things would be (not ran so there might be bugs):

```rust
let mut top_context = Context::new();
top_context.insert("total_posts", &docs.len());
// You probably are not displayed all of the elements from a doc,
// you could create a vec/tuple of  what you need instead
top_context.insert("docs_all", &docs.iter().take(5).collect());
for doc in docs {
    let mut ctx2 = Context::new();
    ctx2.extend(top_context.clone();
    ctx2.insert("doc", doc);
    let rendered = tera.render(&template_name, ctx2).expect("Failed to render template");
}
```

For 1000 docs, you will get 1000x `serialize` + 1000*5 clone of `Value`. If you can trim down the `docs_all` for what you actually need to render, it will be fine.

**Comment by linca-apricot** [comment]
Thanks your work.

### 1. trim down the docs_all for what you actually need to render
Yes. It is done in 0.6sec.
(but, I want to set all of documents)

```rust
let mut top_context = Context::new();
top_context.insert("total_posts", &docs.len());
top_context.insert("docs_all", &docs.iter().take(5).collect());
for doc in docs { // loop 1000
    let mut ctx2 = top_context.clone(); // 5 documents string are cloned!
    ctx2.insert("doc", doc);
    let rendered = tera.render(&template_name, ctx2).expect("Failed to render template");
}
```

### 2. If your document objects have a lot of text, it's going to take time.
1000 documents  `top_context.clone()` take time. 2.8sec.
`tera.render()` and `context.into_json()` did not a take time.

```rust
let mut top_context = Context::new();
top_context.insert("total_posts", &docs.len());
top_context.insert("docs_all", &docs);
for doc in docs { // loop 1000
    let mut ctx2 = top_context.clone(); // 1000 documents string are cloned!
    ctx2.insert("doc", doc);
    let rendered = tera.render(&template_name, ctx2).expect("Failed to render template");
}
```

### 3. into_json() is not a cost. clone is a cost.

I misunderstood that `into_json()`in `tera.render()` is cost, but it is not a cost. clone of documents is a cost.

1000 documents  ` json_patch::merge()` take time. 2.8sec.
`tera.render()` and `context.into_json()` did not a take time.

fork Tera and add a method.

```rust
pub fn render_by_value(&self, template_name: &str, value: serde_json::value::Value) -> Result<String> {
        let template = self.get_template(template_name)?;
        let renderer = Renderer::new(template, self, value);
        renderer.render()
}
```

I create json object directly. use `json-patch`.

https://docs.rs/json-patch/0.2.5/json_patch/

```rust
let mut top_value = json!({
    "total_docs": &docs.len(),
    "docs": &docs
});
for doc in docs { // loop 1000
    let value2 = json!({
        "doc": doc
    });
    json_patch::merge(&mut value2, &value); // value is cloned!
    let rendered = tera.render_by_value(&template_name, value2).expect("Failed to render template");
}
```

### 4. To avoid clone documents

I read https://github.com/Keats/tera/issues/364 and https://maciej.codes/2019-03-03-ramhorns.html is intersting.
I will try to use ramhorns. I expect that this approach is efficient (to avoid clone). 

Thanks for your work. I will think a little more.

**Comment by Keats** [comment]
> render_by_value(&self, template_name: &str, value: serde_json::value::Value)

is equivalent to `render(&tpl_name, Context::from_value(val)`, no need to fork it

> I will try to use Ramhorns. I expect that this approach is efficient (to avoid clone) and it can be ported to Tera.

Yep Ramhorn is more efficient but cannot be used in the same contexts. Also no logic so if you have `if` etc in your code that's not going to work.

**Comment by linca-apricot** [comment]
>is equivalent to render(&tpl_name, Context::from_value(val), no need to fork it
yes. I misunderstood before. I read the code and I understand now. Thank you for the explanation.

>Also no logic
yes. Mustache does not have filter and etc... I want to use Jinja or Liquid as template syntax.

**Comment by Keats** [comment]
If you have Rust available where you render the templates, have a look at https://github.com/djc/askama

**Comment by linca-apricot** [comment]
Thanks for your advice. I did check the askama. https://github.com/djc/askama/issues/247
I need to a dynamic template engine.

https://maciej.codes/2019-03-03-ramhorns.html
>    Static template engines grab the source of the template and produce Rust code for rendering it at compile time. This category includes some great libraries like Askama and its derivatives.
>    Dynamic template engines load the source of the template and process it somehow at runtime. This category includes Mustache, Handlebars and Zola's own Tera.
