### ISSUE TITLE
How do I reuse a piece of template code that produces a variable?

### ISSUE THREAD

**Issue by yacoob** [Keats/tera#418]
I've bumped into this while making a zola template, but it's probably not zola specific. The important bit is that I can't work around this problem outside of the templating language.

I have a piece of template code that populates a variable in the context:

```jinja2
{% set_global all_pages = [] %}
{% for s in config.extra.interesting_sections %}
{% set section = get_section(path=g ~ "/_index.md") %}
{% for ss in sections.subsections %}
{% set_global all_pages = all_pages | concat(with=ss) %}
{% endfor %}
{% endfor %}
```

`all_pages` should have a list of all subsections from `config.extra.interesting_sections`. The code above works. I bump into problems if I want to reuse it though. I'd like to have `all_pages` available on couple of pages. I've tried putting this code in a macro or in an include - in both cases, I don't get to see `all_pages` in the page/section's context. I think for macros it's a deliberate decision (via https://github.com/Keats/tera/issues/336), I'm not sure about includes. One way that did work was to include it in a parent template that all of my templates inherit from. Downside of this approach is that this variable is now present in all of the templates whether I need it or not :D 

Is there any way to avoid c&p of that code?

Thanks!

**Comment by Keats** [comment]
No way to avoid the copy/paste right now other than use inheritance. I would probably put that in a block and override that block in templates that need it, start with a `super` call and then do whatever is needed with those variables.

**Comment by yacoob** [comment]
Allright. Do you want to keep this bug open as a feature request, or should we close it?

**Comment by Keats** [comment]
Let's close it, I don't think there will anything similar implemented.
