### ISSUE TITLE
Add autoescape blocks

### ISSUE THREAD

**Issue by yacoob** [Keats/tera#419]
I wanted to mark whole output from macro as safe to avoid having to `|safe` every single usage of that macro:

```jinja2
{% macro thumb(href) -%}
{%- filter safe -%}
{{ config.extra.imgurl }}/thumb/{{ href }}
{%- endfilter -%}
{%- endmacro thumb %}
```

Using this macro results in:

```
Reason: Failed to render 'grade.html': error while rendering macro `self::thumb`
Reason: Filter 'safe' not found
```

If I `s/safe/upper`, everything works just fine (and the output of macro is all uppercase. Is `safe` filter special? Any other way to mark macro output as safe by default, to avoid having to pipe it through safe after every macro call?

Thanks!

**Comment by Keats** [comment]
So the safe filter doesn't actually exist in practice, hence why it doesn't work :p

Both Jinja2 and Django use an `autoescape` block like http://jinja.pocoo.org/docs/2.10/templates/#autoescape-overrides which would be the way to implement it in Tera and is a valid thing to add imo.

By the way, Tera does have string concatenation so you can do `{{ config.extra.imgurl ~ '/thumb/' ~ href  | safe }}` in the meantime

**Comment by yacoob** [comment]
Thanks for the suggestion. It works fine in this particular case, but it looks like it's having problems with concatenating filtered arguments:

```jinja
{{ '/' ~ entry.path|split(pat="/")|slice(end=2)|join(sep="/") ~ '/#' ~ entry.date }}
```

results in:

```
* Failed to parse "/Users/yacoob/workarea/gcu-zola/templates/macros.html"
 --> 6:63
  |
6 | {{ '/' ~ entry.path|split(pat="/")|slice(end=2)|join(sep="/") ~ '/#' ~ entry.date }}␊
  |                                                               ^---
  |
  = expected `or`, `and`, `<=`, `>=`, `<`, `>`, `==`, `!=`, or a filter
```

It's clearly the filter it's struggling with; the shortest example that trips it up is:

```jinja
{{ entry.path|lower ~ 'bla' }}
```

**Comment by Keats** [comment]
ah yes, filters are at a higher level in the grammar so it doesn't recognise them as part of a string concatenation :/

**Comment by Keats** [comment]
I've changed the title of the issue to reflect it more accurately
