### ISSUE TITLE
'default' filter doesn't work in conditionals

### ISSUE THREAD

**Issue by yacoob** [Keats/tera#422]
I wanted to make part of the rendered page conditional on a value of a bool variable set in a child template. I also wanted to have a default for that variable.

```jinja
<h1>frobnicate: {{ frobnicate|default(value=True) }}!</h1>
{% if frobnicate|default(value=True) %}
  let's go!
{% endif %}
```

This gives me just:
```html
<h1>frobnicate: true!</h1>
```

Should `default` work in a conditional, or is this a bug? It's not a huge problem, as I can just set the default values at the top of the parent template. I'm just curious whether the behavior above is a correct one. It's at least unexpected here :D 

Thanks!

**Comment by Keats** [comment]
Looks like a bug, I will have to take a look
