### ISSUE TITLE
Built-in tester 'defined' problem

### ISSUE THREAD

**Issue by jmrepetti** [Keats/tera#428]
I have a template with a section that should be rendered if a variable is defined. But I can't make it work. I have something like this in my project:

```rust
use serde::Serialize;

#[derive(Default,Serialize)]
struct AStruct {
  parameter: Option<String>
}

// AStruct { parameter: None }
let a_struct_instance = AStruct {..Default::default()};
TEMPLATES.render("template.conf", &a_struct_instance) {...}
```

```
// template.conf example:
//
// {% if parameter is defined %}
//   SOMETHING TO SHOW
// {% endif %}
```

The template is rendered like if parameter is defined, why is that? 

The parameter field is None, but in the build-in tester function, 'value' is Some(Null) and is_some() return true on this. 

https://github.com/Keats/tera/blob/master/src/builtins/testers.rs#L36
```rust
/// Returns true if `value` is defined. Otherwise, returns false.
pub fn defined(value: Option<Value>, params: Vec<Value>) -> Result<bool> {
    number_args_allowed("defined", 0, params.len())?;
    Ok(value.is_some())
}
```

What I'm doing wrong?

**Comment by jmrepetti** [comment]
I added serde::Serialize trait to the example, that's how I have it. It may be something with the serialization, I'm going debug my code and see if it has something to do with that.

**Comment by Keats** [comment]
It might have something to do with how serialize work for a struct, I've just added a test using Context directly (https://github.com/Keats/tera/pull/353/commits/2cb367877e296ff77f4b7bb7ee68a4196f426ecd) and it seems to work. I'll take a deeper look later in the week.

**Comment by jmrepetti** [comment]
I'm still trying to figure out why, but its on my side. I created a simple sample app and works. So I'll close it. 

Thanks!

**Comment by jmrepetti** [comment]
Sorry, I just created a sample project with the a failing example, the previous commet was invalid. I was  testing 'defined' on a wrong field name, which make sense because was undefined. 

Here is a failing example app:

https://github.com/jmrepetti/teratest

I'll keep debugging.

**Comment by jmrepetti** [comment]
> It might have something to do with how serialize work for a struct, I've just added a test using Context directly ([2cb3678](https://github.com/Keats/tera/commit/2cb367877e296ff77f4b7bb7ee68a4196f426ecd)) and it seems to work. I'll take a deeper look later in the week.

I commented on the commit, the test should output an empty result because 'maybe'  is not defined.

If I can come with a solution I'll let you know.

Thanks.

**Comment by jmrepetti** [comment]
So, defined or undefined is on the variable, not the value of the variable.
