### ISSUE TITLE
Support removing whitespace around expressions

### ISSUE THREAD

**Issue by Geemili** [Keats/tera#429]
I had some html like this:

```html
<li><a class="p-category"
  href="{{ tag_url }}">
  {{ tag }}
</a></li>
```
This produces a space that is underlined because the whitespace is included.

![Screen Shot of link with trailing whitespace underlined](https://user-images.githubusercontent.com/2229184/60851527-1a133980-a1b9-11e9-9ffe-4c390952333c.png)

Removing the spaces in the template removes the trailing whitespace.

```html
<li><a class="p-category"
  href="{{ tag_url }}">{{ tag }}</a></li>
```

![Screen Shot of link with trailing whitespace removed](https://user-images.githubusercontent.com/2229184/60851537-25666500-a1b9-11e9-801e-15956d58e0d3.png)

Since whitespace removal for statements is supported using `{%-` and `-%}`, could a similar operator for expressions be added? In my case the whitespace wasn't hard to remove manually, but it seemed like a missing feature.

**Comment by Keats** [comment]
I am not going to work on that myself but if someone wants to, it shouldn't be too hard.

**Comment by pickfire** [comment]
I wonder why whitespace shouldn't be inclusive?
