### ISSUE TITLE
Variable keys with forward slashes

### ISSUE THREAD

**Issue by JeanMertz** [Keats/tera#431]
I've got a hashmap with keys that contain slashes. I can see the context set as expected:

```
&context = Context {
    data: {
        "variables": Object(
            {
                "Test/Variable": String(
                    "test value",
                ),
            },
        ),
    },
}
```

But I can't seem to access the value using either `variables["Test/Variable"]` or `variables['Test/Variable']`. I couldn't find a test that covers this, and it's not explicitly mentioned in the documentation, but I assumed that the bracket-notation could be used specifically for this use case.

The returned error is:

> Variable `variables[\'Test/Variable\']` not found in context while rendering \'tpl\': the evaluated version was `variables.Test/Variable`. Maybe the index is out of bounds?

Looking at the source code, it seems that in the case of a string inside the brackets (so `["var"]`, as opposed to an actual variable with `[var]`), it simply converts it to a regular dot-notation syntax without any special processing:

https://github.com/Keats/tera/blob/2cb367877e296ff77f4b7bb7ee68a4196f426ecd/src/renderer/processor.rs#L61-L67

I feel like this just isn't possible. Should it be? Since it accepts a hashmap, and the context contains the data, it should be able to fetch the data even if the variable contains slashes.

I don't have control of the keys in the context, but I can of course do some pre-processing to convert them into variables that work with the dot-notation, but I was hoping this is (or can be) supported in Tera by default.

**Comment by Keats** [comment]
Looks like a bug!

**Comment by JeanMertz** [comment]
Actually, it must be something on my end. I added tests for this in Tera locally, and they succeed as expected. I'll close this (and push the tests in a PR, since there isn't one yet) and figure out why it's not working for me.

**Comment by JeanMertz** [comment]
I updated the issue, as I didn't create a proper minimum reproducible error. The problem was not with spaces, but slashes. So this works: `a["b c"]`, but this doesn't: `a["b/c"]` (and neither does `a["b c/d"]`).

Should this work, or is this getting into impossible to solve JSON path problems with the forward slash?

**Comment by Keats** [comment]
It should work, all valid JSON should have a valid JSON path. Maybe it's just a matter of escaping it

**Comment by JeanMertz** [comment]
Okay, I found the cause, and it indeed needs escaping, but not with a backward slash.

Here's [the documentation in Serde](https://docs.serde.rs/serde_json/value/enum.Value.html#method.pointer), which points to the [JSON Pointer RFC](https://tools.ietf.org/html/rfc6901#section-3), which specifies:

>   Because the characters '\~' (%x7E) and '/' (%x2F) have special
>   meanings in JSON Pointer, '~' needs to be encoded as '~0' and '/'
>   needs to be encoded as '~1' when these characters appear in a
>   reference token.

I solved it locally by adding a replace call for `/` to `~1` here:

https://github.com/Keats/tera/blob/2cb367877e296ff77f4b7bb7ee68a4196f426ecd/src/renderer/processor.rs#L61-L67

I'll create a PR, but let me know if you know of a better way to solve this (or if this doesn't cover some edge-cases). Also, I didn't add the replacement from `~` to `~0` yet, I could, but that requires more work, as you'd have to make sure not to replace `~0` to `~00`.
