### ISSUE TITLE
Add String to Number Filter

### ISSUE THREAD

**Issue by naftulikay** [Keats/tera#434]
In my [Tera rendering CLI](https://github.com/naftulikay/jinjer), I expose environment variables to the Tera context. Environment variables, of course, are inherently strings, and this makes trying to pass integers/floats not possible:

```jinja
{{ env.ATTEMPT_COUNT + 1 }}
```

`ATTEMPT_COUNT` is set to `"3"` as a string. This template fails to render because adding one to a string doesn't make any sense. I don't see any filters presently for type conversions from strings to number types.

I'd ultimately like to do something like this:

```jinja
{{ (env.ATTEMPT_COUNT | to_u32) + 1 }}
```

I would like to contribute to this feature but my availability is low right now.

**Comment by Keats** [comment]
Yeah there's as_str but not `as_int`, `as_float`. Would be a nice thing to add
