### ISSUE TITLE
newline to break

### ISSUE THREAD

**Issue by haheute** [Keats/tera#435]
Hello, 
I have problems to print content from a MySQL text column with line breaks.
In Adminer the text is shown as this:

```
Animal Alphabets
B is for Bee-Eater
```

I try to render it with this line:
`{{ photo.text | replace( from="\n", to="<br>") }}`

the browser shows this:
`Animal Alphabets B is for Bee-Eater`

when I try this:
`{{ photo.text | replace( from="A", to="<br>") }}`

the browser shows:
```
nimal 
lphabets B is for Bee-Eater
```

It seems as if tera (or diesel?) .. or 'something' .. does not seem to find the `\n`.

Is `\n` the right expression to get the newline / line break character?
How is this usually done with tera?

**Comment by Keats** [comment]
I've added a test with your exact example (https://github.com/Keats/tera/commit/af96fbe3f2f807f603ba9cd896ccb3c532e72282) and it works fine, try adding `| safe` (as in `{{ photo.text | replace( from="\n", to="<br>") | safe}}`.
Which version of Tera are you using? I haven't used anything other than the v1 beta for 6 months so maybe there were some bugs before.

**Comment by haheute** [comment]
I was using version 0.11. 
```
[dependencies]
rocket = "0.4"
rocket_contrib = { version = "0.4", features = ["tera_templates", "diesel_mysql_pool", "helmet"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4", features = ["mysql", "r2d2", "chrono"] }
#tera = "0.11"
tera = "1.0.0-beta.13"
dump = "0.1"
etag = "1.0"
```
Adding `| safe` did not help.
Now trying with 1.0.0-beta.13, which throws errors:
```
error[E0277]: the trait bound `tera::Context: models::_IMPL_SERIALIZE_FOR_Photo::_serde::Serialize` is not satisfied
  --> src/main.rs:41:5
   |
41 |     Template::render("imprint", &Context::new())
   |     ^^^^^^^^^^^^^^^^ the trait `models::_IMPL_SERIALIZE_FOR_Photo::_serde::Serialize` is not implemented for `tera::Context`
   |
   = note: required because of the requirements on the impl of `models::_IMPL_SERIALIZE_FOR_Photo::_serde::Serialize` for `&tera::Context`
   = note: required by `rocket_contrib::templates::Template::render`

```

**Comment by Keats** [comment]
I don't think the rocket_contrib is working for tera v1 yet.

**Comment by haheute** [comment]
ok. I will then wait until tera v1 and rocket function together.

**Comment by dbrgn** [comment]
A custom filter like this works:

```rust
/// Convert line breaks to HTML newlines.
pub fn linebreaksbr(value: Value, _: HashMap<String, Value>) -> tera::Result<Value> {
    let text: String = if let Value::String(s) = value {
        s
    } else {
        return Err("The linebreaksbr filter can only be applied to strings".into());
    };
    Ok(Value::String(text.replace("\r\n", "<br>").replace("\n", "<br>")))
}
```

@Keats would you be interested in a PR that adds this filter to the built-ins? It's probably quite a common use case. Django has a built-in filter called `linebreaksbr` for this.

**Comment by Keats** [comment]
Sounds good, we can add it as `linebreaksbr`

**Comment by dbrgn** [comment]
Will send a PR in a minute!

By the way, the regression test you added (`test_replace_newline`) is _probably_ wrong, because in Rust code the `\n` sequence is a single newline, while in the template it will probably be converted to `\\n`. The root cause in this case would be escape sequences (see #625).
