### ISSUE TITLE
Reload Templates after Lazy Static Init

### ISSUE THREAD

**Issue by Neil-Jubinville** [Keats/tera#439]
Hi,  I have implemented this engine into a server I am building and it is working great!  I am initializing and using the engine as described in the examples using the lazy_static macro.

```
lazy_static! {
    static ref TEMPLATES: Tera = {
        let mut tera = compile_templates!("/app/templates/**/*");       
        tera
    };  
}
```

My issue occurs when trying to execute the full_reload() . In my file change event I am trying to execute:   **TEMPLATES.full_reload();** 
```
cannot borrow data in a `&` reference as mutable
```
   I have a running thread with the notify crate lib that provides me an event where I can run code if a template changes.   This event loop works but obviously when I go to make that function call the compiler does not like that.  The render calls work fine.

Do you have any simple examples where you have reload working with the lazy static init method?

I know in rust public static mutables are the essence of unsafe, so just curious how you guys are going about defining and passing the engine references when you call reload.

**Comment by Neil-Jubinville** [comment]
Ok I figured it out,  I just needed to put it in an Arc Mutex.

```
lazy_static! {
  static ref teraRc:Arc<Mutex<Tera>> = Arc::new(
                    {
                        std::sync::Mutex::new( compile_templates!("/app/templates/**/*"))
                    }     
            );
} 
```

I did notice slow load time when there is a lot of templates I suppose that task could be broken up into something multi-threaded.

**Comment by Keats** [comment]
> I did notice slow load time when there are a lot of templates, I suppose that compile task could be broken up into something multi-threaded to speed things up.

That's weird, it should be near-instantaneous. Do you have thousands of templates?
