### ISSUE TITLE
tera::Error cannot be sent between threads safely

### ISSUE THREAD

**Issue by southerntofu** [Keats/tera#442]
Hi, i'm using error_chain in a program that does tera templating in a rayon loop. Updating from v0.11 to v1.0.0-beta14 produced the following error:

```
error[E0277]: `(dyn std::error::Error + 'static)` cannot be sent between threads safely
  --> src/main.rs:21:1
   |
21 | / error_chain!{
22 | |     foreign_links {
23 | |         Http(reqwest::Error);
24 | |         Json(serde_json::Error);
...  |
27 | |     }
28 | | }
   | |_^ `(dyn std::error::Error + 'static)` cannot be sent between threads safely
   |
   = help: the trait `std::marker::Send` is not implemented for `(dyn std::error::Error + 'static)`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(dyn std::error::Error + 'static)>`
   = note: required because it appears within the type `std::boxed::Box<(dyn std::error::Error + 'static)>`
   = note: required because it appears within the type `std::option::Option<std::boxed::Box<(dyn std::error::Error + 'static)>>`
   = note: required because it appears within the type `tera::errors::Error`
   = note: required because it appears within the type `ErrorKind`
   = note: required because it appears within the type `Error`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```

Full extract from my source file:
```
error_chain!{
    foreign_links {
        Http(reqwest::Error);
        Json(serde_json::Error);
        Io(std::io::Error);
        Templating(tera::Error);
    }
}
```

**Comment by Keats** [comment]
Is it ok to do a blanket Send+Sync impl for errors? That doesn't really seem idiomatic.

**Comment by southerntofu** [comment]
I don't know if it's idiomatic but i saw that in [std::io::Error::Custom](https://doc.rust-lang.org/src/std/io/error.rs.html#73)

**Comment by Keats** [comment]
We can add ` + Send + Sync` to the bounds but I'm not sure how it works with the StdError impl of `source`

**Comment by CAD97** [comment]
What you'd need to do would be to do `source: Option<Box<dyn StdError>>` in your `Error` type. The `Send`/`Sync` bounds are "free" and can be removed when returning the `&dyn StdError + 'static` for `Error::source`. If all error types you chain from internally are `Send+Sync`, it makes sense to do so.

(In practice, I'm not actually certain how to produce a `'static` value that isn't `Send+Sync`...)

**Comment by Keats** [comment]
@CAD97 I'm not sure I follow. It already is `source: Option<Box<dyn StdError>>`, but Sync/Send is not working because of `StdError::source()`:

```
error[E0277]: `(dyn std::error::Error + 'static)` cannot be sent between threads safely
   --> src/errors.rs:174:9
    |
172 |         fn is_send<T: Send>() {}
    |            -------    ---- required by this bound in `errors::tests::errors_are_sync_send::is_send`
173 |         is_sync::<Error>();
174 |         is_send::<Error>();
    |         ^^^^^^^^^^^^^^^^ `(dyn std::error::Error + 'static)` cannot be sent between threads safely
    |
    = help: the trait `std::marker::Send` is not implemented for `(dyn std::error::Error + 'static)`
    = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(dyn std::error::Error + 'static)>`
    = note: required because it appears within the type `std::boxed::Box<(dyn std::error::Error + 'static)>`
    = note: required because it appears within the type `std::option::Option<std::boxed::Box<(dyn std::error::Error + 'static)>>`
    = note: required because it appears within the type `errors::Error`
```
I'm sure it not's something complicated but I just don't see it atm. If you can have it working, I would love a PR

**Comment by CAD97** [comment]
I was mistaken; I honestly thought I had done it just like that before and that `&dyn Trait + LangMarkerTrait` coerced to `&dyn Trait`.

**Comment by AxelMontini** [comment]
I'm looking forward to this change to be able to use the `tera::Error` struct to construct `anyhow::Error`.

To do so it's necessary to do the following:

* add the `+ Send + Sync` bounds to `Error.source` and to `Error::chain`'s parameter `source`.
* add `as &(dyn StdError + 'static)` inside of the implementation of the `std::error::Error::source` method.

So far all tests are passing and I'm finally able to use anyhow::Error, but I'm not sure of how much of a breaking change this is.

**Comment by Keats** [comment]
The v1 has many breaking changes so if all tests on it pass then it's fine

**Comment by AxelMontini** [comment]
Roget that. I've created #458 to address this.

**Comment by Keats** [comment]
Done in v1
