### ISSUE TITLE
How can I embed items

### ISSUE THREAD

**Issue by hajsf** [Keats/tera#449]
How can I embed a pic, or a youtube in the template?

**Comment by Keats** [comment]
For images you can base64 them but you won't be able to embed videos, this is only a template engine.

**Comment by hajsf** [comment]
@Keats, did not get your point, can you provide simple sample code

**Comment by Keats** [comment]
https://stackoverflow.com/questions/8499633/how-to-display-base64-images-in-html for images

For videos it isn't embeddable in a text file afaik.
