### ISSUE TITLE
Use our own serialization

### ISSUE THREAD

**Issue by Keats** [Keats/tera#45]
rather than JSON.
It would give us more types than JSON has, like date and datetimes out of the box.

Would require custom derive to be nice though so waiting for macros 1.1 to land for that to happen.
Or we could piggyback on Serde and write a `serde_tera` implementation

**Comment by Alex-PK** [comment]
I've been working on something like that for a while now, but mostly to experiment with lower-level constructs in Rust. It's very much "in flux" as I learn new things and conduct new experiments:

https://bitbucket.org/Alex_PK/darry/overview

The primary policy is to make it always work on stable without requiring nightly features, and to use as few macros as possible, so I am a bit limited in what I can do, but I kind of like what's coming out. :)

**Comment by Keats** [comment]
Interesting! i think I'd go with a fork of `serde_json` though and add whatever type we want though, as it will be the way to serialize so we should get all the speed with no efforts.

I had a quick look at the code and I'd rename https://bitbucket.org/Alex_PK/darry/src/ad0cc393549be8e558e349790e968ac76ffe2b74/src/value.rs?at=master&fileviewer=file-view-default#value.rs-137 to `is_truthy` or something similar, i'd expect a `to_bool` method to fail on something other than a bool

**Comment by Keats** [comment]
`toml-rs` (http://alexcrichton.com/toml-rs/toml/index.html) switched to something like that.
Would be interesting to try it out on a branch
