### ISSUE TITLE
Enhancement - Create Random Number

### ISSUE THREAD

**Issue by SgtIria** [Keats/tera#462]
Would it be possible to add a feature under math / [expressions ](https://tera.netlify.com/docs/templates/#expressions) to create a random number?

I need (and I suspect others would as well) the ability in a template to pick an item from an array at random. This might be for displaying FAQ of the day, a random image or article or advert etc. 

Ideally something as simple as `random(start=0,end=10)` would return an integer in the range 0-10.

thanks

**Comment by Keats** [comment]
Doable, if anyone wants to implement it make sure the rand crate is behind the `builtins` flag

**Comment by Keats** [comment]
It should be only integers right? No need to generate a random float?

**Comment by SgtIria** [comment]
Yes int is fine.

**Comment by Keats** [comment]
It's in the commit above and will be in the next beta release
