### ISSUE TITLE
Function to get an environment variable

### ISSUE THREAD

**Issue by Keats** [Keats/tera#464]
It should probably look something like `get_env_var(name="", default="")`

I don't think we want to do any type parsing, both the value found and the default should be strings.
I *think* having a default in that case is better than erroring if the env var is not found but nmot 100% sure, any feedback?

**Comment by jsonmaur** [comment]
For cases when you'd want a compilation error if it's missing an important environment variable, I think a default value should be optional (but supported.)

**Comment by Keats** [comment]
Any bikeshedding on the name? I'm uninspired.

**Comment by jsonmaur** [comment]
My vote would be a simple `get_env(name="", default="")`. Seems to be the pattern in most languages and other static generators ([Hugo uses `getenv`](https://gohugo.io/functions/getenv/)). Although with Rust it's `env::var` so maybe we'd want to stay in that arena?
