### ISSUE TITLE
Filter section mishandles whitespace

### ISSUE THREAD

**Issue by nayato** [Keats/tera#475]
Following template (`f` returns the value passed to it):
```jinja
{% if true %}
   {{ "a" }}   b
{% endif %}
{% filter f %}
   {{ "c" }}   d
{% endfilter %}
```
renders as follows:
```

   a   b

cd

```
For filter section any whitespace following `{{ "c" }}` appears to be discarded which is unexpected.

**Comment by nayato** [comment]
It appears to be a parsing issue.
Replacing `!` with `$` here: https://github.com/Keats/tera/blob/master/src/parser/tera.pest#L197 seems to fix the problem.
Now, I don't know whether it's the correct fix as I have 0 knowledge of Pest. If that seems right, I'll make a PR.

**Comment by Keats** [comment]
Thanks for catching that bug!
If all other tests work, it's probably fine, just make sure to add a regression test for it.

**Comment by Keats** [comment]
Not the case on the current release, I've added a renderer test for that though.
