### ISSUE TITLE
Precedence of `or` is higher than that of `and`

### ISSUE THREAD

**Issue by vandenoever** [Keats/tera#479]
In most programming languages, [`and` is evaluated before `or`](https://en.wikipedia.org/wiki/Order_of_operations#Programming_languages). But in Tera it is the other way around.

This can be seen by evaluating the expression `false and true or true`. In Tera, this expression evaluates to `false`. In a language where `and` has higher or equal precedence to `or`, the expression would evaluate to `true`.

Since the Tera documentation does not mention precedence levels, I assume it is not intentional that `or` has a higher precedence.

Conforming the precedence levers of Tera operators to other programming languages is preferable.

**Comment by Keats** [comment]
That's a bug yes

**Comment by ocstl** [comment]
I failed to reproduce this behaviour, either with a new test for the parser or directly using `Tera::one_off(...)` (which yields `true`). Has this been fixed?

**Comment by Keats** [comment]
Looks like it's not the case anymore, closing.
