### ISSUE TITLE
maps | length

### ISSUE THREAD

**Issue by KoltesDigital** [Keats/tera#480]
Have you thought about `length` filter returning a map's length? Right now it only works for arrays and strings.

**Comment by Ten0** [comment]
You could already add it manually thanks to the function import feature.

**Comment by KoltesDigital** [comment]
I'm suggesting to make it built-in, given that both arrays and objects are both iterables using for loops, and that at least I wanted this filter multiple times on multiple Tera instances, I guess I'm not the only one it would benefit. The PR would have been just about adding one line, that's why I asked first if there's a reason. I can make this PR if you'd like.

**Comment by Keats** [comment]
I think it makes sense to add, PR welcome!

**Comment by KoltesDigital** [comment]
Here you go!

**Comment by KoltesDigital** [comment]
BTW, how do you feel about length returning 0 for other types? Shouldn't an error be thrown instead?

**Comment by Keats** [comment]
That would be a breaking change so only for the next major version.

**Comment by Ten0** [comment]
> BTW, how do you feel about length returning 0 for other types? Shouldn't an error be thrown instead?

I agree! ^^
We're having a similar debate at https://github.com/Keats/tera/issues/481.

**Comment by KoltesDigital** [comment]
Haha! At the same time.

I share your view of rust philosophy. Actually I see no use cases where length would be applied to a value not array|object|string, but I can imagine I would invert two variables by mistake. In this case, I'd prefer an error stating that I'm wrong, instead of silently working but not as expected.

**Comment by Keats** [comment]
Actually for the `length` filter it should have been an error from the start for bool/numbers so changing that is a bugfix and is ok to do.

**Comment by Keats** [comment]
It's in 1.0.2
