### ISSUE TITLE
Add default context to all templates

### ISSUE THREAD

**Issue by trolleyman** [Keats/tera#487]
Hi, I was wondering if there was a way to add a default context to all templates that are rendered -- for example a `debug` flag?

I was imagining two functions on the `Tera` struct, something like this:
```rust
fn set_default_context(&mut self, ctx: Context);
fn reset_default_context(&mut self);
```

The default context would be merged with the context set when rendering, with the default's keys being overridden.

**Comment by Keats** [comment]
You can create a default context somewhere, create your specific context and then extend it with the default one: https://docs.rs/tera/1.0.2/tera/struct.Context.html#method.extend

No default context concept otherwise.
