### ISSUE TITLE
[feature] Add an emojify filter

### ISSUE THREAD

**Issue by lukehsiao** [Keats/tera#489]
Hugo includes an `emojify` function to allow users to include emojis in their content. For example, `:smile:` being rendered as :smile:.

https://gohugo.io/functions/emojify/

It would be great to get feature parity with Hugo here by having a built-in filter for this. I'm not sure if this is best implemented in tera, or in zola, but it should essentially just be a look-up table from emoji codes to unicode emojis.

**Comment by Keats** [comment]
IMO it should be part of the markdown renderer (https://github.com/getzola/zola/issues/292) of Zola so you don't have discrepancies in content rather than a filter

**Comment by lukehsiao** [comment]
Makes sense. I will close this issue in favor of the one in zola then.
