### ISSUE TITLE
Range errors when Start > End

### ISSUE THREAD

**Issue by krisradio** [Keats/tera#500]
Line 66 of `function.rs` has this error check for the Range function: 

``` rust
    if start > end {
        return Err(Error::msg(
            "Function `range` was called without a `start` argument greater than the `end` one",
        ));
    }
```

The check should be `if start < end`. The current error condition is in fact the desired condition; start should be greater than end.

**Comment by Keats** [comment]
The message is wrong, but the error is right: it should be "was called with a `start`..` rather than without.

**Comment by krisradio** [comment]
Ok that's fair... Sorry, it was probably too late (or too early in the morning) for me to be writing bug tickets last night. 

Here's the full issue though, maybe you can understand why I'm getting this error? I have this code 

```tera
{% set length = section.subsections | length -%}
{% for col in range(end=config.extra.section_col) -%}
    Len: {{ length }}; Col: {{ col }};
    {% set matched_i = range(end=length, start=col, step_by=config.extra.section_col) -%}
```
The 3rd line is just for debugging purposes. The 4th line throws the error. When I set `start=0` (instead of `start=col`), I get [this output](https://i.imgur.com/PJh5eai.png), which shows length (my end argument) is 6 and col (my start argument) counts 0, 1, 2. 

0, 1, & 2 are all less than 6, so then why am I triggering this error? My full code is [here](https://github.com/krisradio/zola-radio/blob/master/templates/section.html), the error on line 22. It won't build unless `start=col` is changed to `start=0`. 

Thanks for your prompt feedback, again sorry for not thinking straight. My head was just at "start is less than end so this check must be backwards". Now I don't know how I'm running into it at all, since - as you said - the error check _is_ right.

**Comment by Keats** [comment]
That's very odd, I will have a look this weekend.

**Comment by krisradio** [comment]
Thanks @keats! I'll keep hacking away with the workaround.

**Comment by Keats** [comment]
Do you have a repo with content so it's easier to debug?

**Comment by krisradio** [comment]
Absolutely, the [zola branch on my github pages repo](https://github.com/krisradio/krisradio.github.io/tree/zola).

**Comment by Keats** [comment]
Thats a logic bug in the theme: the loop is ran even for sections without subsections.
wrap the for in `{% for col in range(end=config.extra.section_col) -%}` with a `if len > 0` and it will work.

**Comment by krisradio** [comment]
Oh shoot..! I could have figured that out by paying attention to which sections were triggering that error huh? Thanks so much for looking at it!
