### ISSUE TITLE
Filter 'int' not found

### ISSUE THREAD

**Issue by mycognosist** [Keats/tera#503]
When trying to use the built-in `int` filter I receive the following error:

`[2020-04-24T13:57:36Z ERROR rocket_contrib::templates::tera_templates] Filter 'int' not found`

I am using `tera = "1.2"` and am attempting to use the filter as follows:

`{% set uptime_int = uptime | int %}` where `uptime` is of type `Option<String>`.

I am using the built-in `round` filter in the same template without any problems.

Any assistance would be greatly appreciated.

**Comment by Keats** [comment]
Rocket contrib is not using Tera 1: https://crates.io/crates/rocket_contrib even if you set a version in your cargo.toml

**Comment by mycognosist** [comment]
Thanks for the explanation. That makes sense. I see that the dependency has been bumped to `1.0.2` on the `master` branch of Rocket. I believe it's due for inclusion in Rocket `0.5`. Relevant pull-request: [Upgraded dependencies #1201](https://github.com/SergioBenitez/Rocket/pull/1201).
