### ISSUE TITLE
Add Rich Text Support feature for Tera Templates.

### ISSUE THREAD

**Issue by Voodlaz** [Keats/tera#505]
By Rich Text I mean text HTML markdown. Rich Text Support is a feature when you can transform ordinary text with HTML markdown, to HTML markdown in the template. This feature was used by Django TLS.

**Comment by Keats** [comment]
You can easily add a `markdown` filter if that's what you mean? I'm not sure I follow, do you have a link?

**Comment by Voodlaz** [comment]
Oh. There's a markdown. I understand.
