### ISSUE TITLE
Urlencode forward slashes

### ISSUE THREAD

**Issue by piyushrungta25** [Keats/tera#506]
Currently, the `urlencode` filter does not encode `/` ([ref](https://github.com/Keats/tera/blob/5eb32902376821117c4a259e2226d906ebc0aab1/src/builtins/filters/string.rs#L46)). It would be nice to be able to escape slashes, either as a parameter to `urlencode` ot better, as an additional  `urlencode_strict` filter which encodes all non-alphanumeric characters.

A rough implementation would look like
```rust
use percent_encoding::{percent_encode, NON_ALPHANUMERIC};

fn urlencode_strict(value: &Value, _: &HashMap<String, Value>) -> TResult<Value> {
    let s = value.as_str().unwrap();
    let encoded = percent_encode(s.as_bytes(), NON_ALPHANUMERIC).to_string();
    Ok(Value::String(encoded))
}
```

I would be happy to make a PR if this is something you would be interested in including.

**Comment by Keats** [comment]
Sounds ok to me

**Comment by Keats** [comment]
Sounds ok to me
