### ISSUE TITLE
Double for-loop can not be used?

### ISSUE THREAD

**Issue by hhatto** [Keats/tera#51]
main.rs
```rust
extern crate tera;
use std::env;
use std::path::Path;
use tera::{Tera, Context};

fn main() {
    let root_path = env::current_dir().unwrap();
    let template_dir = root_path.join(Path::new("templates/*"));
    let template_engine = Tera::new(template_dir.to_str().unwrap());
    let mut context = Context::new();

    let vectors = vec![vec![0, 3, 6], vec![1, 4, 7]];
    context.add("vectors", &vectors);
    println!("{}", template_engine.render("double-loop.tera", context).unwrap());
}
```

templates/double-loop.tera:
```html
{% for vector in vectors %}
  {% for j in vector %}
    j={{ j }}
  {% endfor %}
{% endfor %}
```

output:
```
j=0
  j=3
  j=6
j=0
  j=3
  j=6
```

P.S.

tera is good library 😄 
I have been using in the [build script](https://github.com/hhatto/woothee-rust/blob/master/build.rs).

Thanks.

**Comment by Keats** [comment]
Thanks for the bug report! I'll have a look later today or this weekend

**Comment by Keats** [comment]
It's fixed in master if you want to try, I'll try to get a release out in a couple of days once we have more filters (https://github.com/Keats/tera/issues/46)

**Comment by hhatto** [comment]
Thanks.
I was able to confirm that it is fixed in the master.

**Comment by hhatto** [comment]
@Keats 
I found another problem.
It does not work correctly, when empty vector in for-loop.

patch this: https://github.com/hhatto/tera/commit/8b4684cbea8daaeeb0b75316d5f5a36739a6db53

**Comment by Keats** [comment]
Thanks, I pushed the fix to master!

**Comment by hhatto** [comment]
Thank you very much 😃
