### ISSUE TITLE
Allow users to skip template loading in Tera::new

### ISSUE THREAD

**Issue by bkloster** [Keats/tera#515]
`Tera::new` expects a glob pattern and errors out if that pattern does not contain at least one asterisk. If a user would like to only add templates with `Tera::add_template_files` or similar, they currently need to use a workaround like this:

    let tera = Tera::new("*.hopefullynobodyeverwillusethisfileextension").unwrap();

I understand changing the signature of `Tera::new` to receive an `Option<&str>` is out of the question due to backwards compatibility, but I would like to suggest one of the following:

* Add a new function `Tera::new_empty()` that does not load any templates
* Allow an empty string as the glob pattern in `Tera::new`, skipping template loading in this case (this does seem a bit *wrong* though when we have `Option`)

**Comment by Keats** [comment]
> Add a new function Tera::new_empty() that does not load any templates

`Tera::default`?

**Comment by bkloster** [comment]
> `Tera::default`?

Oohhh... sorry, I didn't see that Tera implemented the Default trait. Thank you!
