### ISSUE TITLE
Feature request: Default values

### ISSUE THREAD

**Issue by Kixiron** [Keats/tera#519]
I've found myself using this pattern a lot and, assuming there's not a built-in way to do it that I haven't found, something to remedy it would be great

```html
{% if variable %}
    {% set value = "Something" %}
{% else %}
    {% set value = "default" %}
{% endif %}
```

The situation is that there's a variable being levered off of, and if it's true/non-null then the value is set, if not it's set to and empty string or a default. Unfortunately I can't think of a really solution off the top of my head that doesn't require some form of inline conditional expressions (which would be great, for the record)

**Comment by Keats** [comment]
See https://tera.netlify.app/docs#default

**Comment by Kixiron** [comment]
Thanks!
