### ISSUE TITLE
Support non-string keys in iteration

### ISSUE THREAD

**Issue by mre** [Keats/tera#522]
Recently I had a case where I wanted to iterate over a map with keys that were not strings.
Here is a contrived example of what I roughly wrote:

```rust
extern crate tera;

use tera::{Context, Tera};
use std::collections::HashMap;
use serde::Serialize;

static TEMPLATE: &'static str = "
{% for key, _ in table %}
{% endfor %}";

#[derive(Hash, PartialEq, Eq, Serialize)]
struct K;

fn main() {
    let mut table: HashMap<K, _> = HashMap::new();
    table.insert(K {}, ());

    let mut tera = Tera::default();
    tera.add_raw_templates(vec![("table.html", TEMPLATE)]).unwrap();
    let mut ctx = Context::new();
    ctx.insert("table", &table);

    let _ = tera.render("table.html", &ctx).unwrap();
```

(The `table.html` is not strictly necessary, but it explains a bit better what I had in mind.)

The code panics with

```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("key must be a string", line: 0, column: 0)', /Users/mre/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.3.0/src/context.rs:32:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I wonder if we could add support for non-string keys.
This might well be a limitation of serde so if we can't, then we should document that as a limitation somewhere and maybe suggest a workaround.
Also, I think we shouldn't panic here, so maybe we can replace the `unwrap`.

Let me know what you think and I'll try to support if I can. 😊

**Comment by Keats** [comment]
JSON objects keys are always string so that's not doable.

**Comment by mre** [comment]
Alright, thanks for the answer. Think we can close this now.
