### ISSUE TITLE
Escape tera tags

### ISSUE THREAD

**Issue by Arteneko** [Keats/tera#524]
I use Kickstart to bootstrap a PHP project, which uses Twig as template manager.

The issue is that every time my twig templates contain a tera-compatible tag, I have no way to escape them.

Could there be a way to escape tera tags, e.g. `\{{` (which would render as `{{`) ?

**Comment by Keats** [comment]
You can use `raw` or ignore the twig files in the config

**Comment by Arteneko** [comment]
But then, the perfectly valid kickstart templates would be ignored

**Comment by Keats** [comment]
Use `raw` then. Do you have a mix of twig and Tera in the same file?

**Comment by Arteneko** [comment]
Yes.

If raw allows to handle this issue, how should it be used?

**Comment by Keats** [comment]
https://tera.netlify.app/docs/#raw
Wrap your twig code in a raw section and you should be ok

**Comment by Arteneko** [comment]
Thanks, I'm gonna check that
