### ISSUE TITLE
Docs styling has dissapeared

### ISSUE THREAD

**Issue by savente93** [Keats/tera#525]
All of the stylings on https://tera.netlify.com/ seems to have disappeared

**Comment by dvente** [comment]
Sorry to come back to this but the issue seems to be back... Sadly I can't offer more insight on why :sweat:

**Comment by Keats** [comment]
I do see the styling in incognito on my end?

**Comment by dvente** [comment]
I indeed see the styling in incognito mode, but *only* in incognito mode, which seems very strange to me.
