### ISSUE TITLE
Add methods for checking if a value is inside a `Context`

### ISSUE THREAD

**Issue by SirWindfield** [Keats/tera#538]
I have a use-case where my application and context creation is split into multiple modules. I have to check if specific values are already inside the context and only insert if they are not. Currently there is no such method available. I'd propose these ones:

```rust
fn contains<S: Into<String>>(&self, key: S) -> bool;
fn get<S: Into<String>>(&self, key: S) -> Option<&Value>;
```

This can only be done currently by creating a custom type and implementing `From<type> for Context {}`

**Comment by SirWindfield** [comment]
I am open to creating a PR if this gets merged.

**Comment by Keats** [comment]
Any reason to not just take `&str` as parameter? Otherwise ok for a PR

**Comment by SirWindfield** [comment]
@Keats Because that's the signature of the input method. I'd thought you sticked with this for a specific reason.

**Comment by Keats** [comment]
It's not needed when just looking up something in the btreemap, only (maybe) when inserting

**Comment by SirWindfield** [comment]
Sure, I can change it. On that note, maybe the implementation from insert could be re-thought. But this is another issue on its own.
