### ISSUE TITLE
reducing wasm module size when using tera

### ISSUE THREAD

**Issue by samuelcolvin** [Keats/tera#541]
First of all, thank you for tera. It's amazing.

I've been trying to use tera to render templates using webassembly on cloudflare workers. It works, but unfortunately loading "large" wasm modules is currently very slow on cloudflare workers.

See [this long discussion](https://community.cloudflare.com/t/cloudflare-workers-very-slow-with-moderate-sized-webassembly-bindings/184668/12) on their forum and [this simple example](https://github.com/samuelcolvin/cloudflare-worker-speed-test) I build to demonstrate the performance problems.

**Question:** is there anything I can do to reduce the size of wasm modules where tera is being used?

I've already tried `default-features = false` which is a good start.

I've also thought about `no_std`, that might be a potential one day but it doesn't have a massive effect (in relative terms, for a large-ish module) and would require a lot of work.

Is there any other golden bullet I don't know about that could reduce the size of a modules that include tera - tera seems to be (understandably) the single largest contributor to size for the project I was working on.

**Comment by Keats** [comment]
Do you know which part is taking the most space? From your example, regex is over half of the bundle (1160-619=541) and I don't think I can remove it from the default without doing https://github.com/Keats/tera/issues/484 which is a breaking change.

**Comment by samuelcolvin** [comment]
Would tera work using regex without default features?

e.g. in `Cargo.toml`
```toml
regex = { version = "1", optional = true, default-features = false, features = ["std"] }
```

This might reduce size significantly with little or no work.

**Comment by Keats** [comment]
I don't think it would work. Tera depends on globwalk which depends on https://crates.io/crates/ignore which depends on regex so those features will be turned on anyway.
In the next major version, I will make globwalk optional which means regex will not be pulled in at all when disabling the feature.

**Comment by samuelcolvin** [comment]
Okay, thank you.

Closing this as I think the main points are covered.
