### ISSUE TITLE
Getting a list of all variables inside a template

### ISSUE THREAD

**Issue by SirWindfield** [Keats/tera#542]
I have a use-case right now where I'd like to be able to get a list of all variables inside a template file (actually a `one_off`). I'd then like to check if all of those variables are inside the current context and if not, interactively prompt the user for the rest of the needed variables.

Is this somehow possible? Maybe some private APIs that aren't made public yet? Would this be an easy feature to add? I am not sure how extensible the parsing is in `tera` so maybe this isn't in it's current form achievable.

**Comment by Keats** [comment]
There is `__tera_context` that dumps everything in the context

**Comment by SirWindfield** [comment]
Maybe I worded it wrong. Given that I provide a template and pass it to a `tera` instance, is it possible to somehow get all variables that have been defined inside the template?
```text
My name is {{ name }} and I like {{ favorite_food }}.
```

I am looking for a method that allows be to retrieve a vector of variables of the above template string, so `["name", "favorite_food"]` that I can use to compare against my current context and see what is missing. And those missing values are then retrieved by interactively asking the user, but that part has nothing to do with `tera` :)

**Comment by Keats** [comment]
The AST is available but hidden from the docs as it can be changed at any time without any mentions in the changelog.

**Comment by SirWindfield** [comment]
Looks like that is the only solution for now! It works in my case so I'll just stick with it. Thanks!
