### ISSUE TITLE
Look into rewriting the parser

### ISSUE THREAD

**Issue by Keats** [Keats/tera#550]
It seems that `pest` is not maintained anymore and we do have some bugs (unlikely to trigger in practice but still) because of it.

What are the best options right now?
I've seen https://crates.io/crates/combine and https://crates.io/crates/nom but not in depth.

This is not urgent at all and might not even happen but looking around so if it needs ot happen, I know the options.

**Comment by SirWindfield** [comment]
Are you referring to https://github.com/pest-parser/pest/issues/399#issuecomment-678489985?
It feels more of a temporary thing according to that comment. Not sure why some PRs aren't merged though, only publishing can't be done :)

**Comment by Keats** [comment]
The new version has been talked about for almost 2 years but the creator doesn't seem active anymore. Again, not needed to change right now but we do have some bugs in Tera due to issues in pest that are not fixed.

**Comment by SirWindfield** [comment]
Fair enough. Maybe things change down the line in a couple of weeks/months. Who knows :D

**Comment by tomtau** [comment]
> we do have some bugs in Tera due to issues in pest that are not fixed.

@Keats do you have the list of issues? I saw this one: https://github.com/pest-parser/pest/issues/402

**Comment by Keats** [comment]
That's the main one, I can't remember the others sadly.
This issue should be close actually, I've already rewritten the parser like 3 times already for v2.
