### ISSUE TITLE
Support request: how to print chained errors?

### ISSUE THREAD

**Issue by UebelAndre** [Keats/tera#557]
I came across an issue where I had a chained error but was only seeing the top level "Failed to render..." message when I called ".unwrap()". Is there a way to have that print the source errors recursively?

**Comment by Keats** [comment]
See https://github.com/Keats/tera/blob/master/examples/basic/main.rs#L47-L51

**Comment by UebelAndre** [comment]
Perfect! Thank you @Keats 😃
