### ISSUE TITLE
Add support for variable tests

### ISSUE THREAD

**Issue by SergioBenitez** [Keats/tera#56]
Hello!

Great project you have going on here!

One feature that I feel is sorely missing is support for [tests](http://jinja.pocoo.org/docs/dev/templates/#tests). Have you considered implementing this? The case when I most want to use this is to check if a variable has been defined. For example, I'd like to be able to write:

```
{% if some_var is defined %}
  {{ some_var }}
{% endif %}
```

It would also be nice to make this pluggable to allow anyone to implement a test.

**Comment by Keats** [comment]
I've actually never used tests in Jinja2, which ones are you using the most?

Next up for me to implement once filters are mostly in will be macros I think but if tests are something common enough I'd welcome PRs for it

**Comment by SergioBenitez** [comment]
`defined` is the only one I'm sorely missing. This is because without `defined`, every variable needs to have a value every time. This means that the template will fail to render if some variable is in the template but a context with said variable wasn't passed in.

I'll look at the source code.

**Comment by SergioBenitez** [comment]
Implemented in #58.

While I think we should definitely have testers, perhaps it would also make sense to overload `if` on identifiers so that some variable `v` evaluates to false in an if condition if a variable named `v` is not in the current context.

**Comment by Keats** [comment]
Thanks for the great PR!

Looking at http://jinja.pocoo.org/docs/dev/templates/#builtin-tests I only see `defined` that I would use, the rest could be done as filters afaik (`is_odd`, `is_even`) etc. Seems that it's what Ansible does https://docs.ansible.com/ansible/playbooks_tests.html and Django with templatetags like https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#divisibleby

I would start with what you mentioned about overloading `if` for now and see if the needs for tests come again.

**Comment by Keats** [comment]
I just released 0.2.0 which contains your PR
