### ISSUE TITLE
Security issue: escaping is not contextual, potential XSS

### ISSUE THREAD

**Issue by empijei** [Keats/tera#566]
Tera currently escapes only based on file types (html, xml) but within a certain file type it only uses **one** escaping mechanism.

This means that values interpolated in different contexts (html attributes, html text, script, style, urls) are all escaped in the same way, which is known to be a cause for XSS.

**This makes tera inherently unsafe**. You can read more about it [here](https://rawgit.com/mikesamuel/sanitized-jquery-templates/trunk/safetemplate.html#strawman_i__non_contextual_auto_sanitization) (please see "Strawman I: Non-contextual auto-sanitization").

This should either be:
* clearly documented (see the "least surprise" bits of the linked doc) so that devs are reminded to manually apply the extra escaping needed
* fixed by implementing contextual auto escaping (also described in that document)

Contextual auto escaping is implemented in many safe templates like Java Soy, Python Soy, Angular templates, Go standard html/template and safehtml/template or Jinja2 (even though in Jinja2 is disabled by default) and others.

The TL;DR of the mechanism is to parse the HTML sources, understand the context that user data is being interpolated in and pick the appropriate escaping function accordingly.

**Comment by Keats** [comment]
Thanks for the issue. I have updated the docs as parsing HTML is clearly out of scope for Tera.
