### ISSUE TITLE
GlobalFn type declaration is incorrect in documentation on website

### ISSUE THREAD

**Issue by m-decoster** [Keats/tera#569]
In the [functions section](https://tera.netlify.app/docs/#functions) of the documentation on the Tera website, the `GlobalFn` type is defined as `Box<Fn(HashMap<String, Value>) -> Result<Value> + Sync + Send>`. However, Tera expects a `Box<Fn(&HashMap<String, Value>) -> Result<Value> + Sync + Send>`. Note the reference to the `HashMap`.

Also note that in more recent versions of Rust, this should actually be `Box<dyn Fn(&HashMap<String, Value>) -> Result<Value> + Sync + Send>` with the added `dyn`.

**Comment by Keats** [comment]
Thanks!
