### ISSUE TITLE
Not able to pull in tera as dependency

### ISSUE THREAD

**Issue by houqp** [Keats/tera#57]
Hi,

I got the following error from `cargo build --verbose`:

```
 $ cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
failed to parse registry's information for: serde_json

Caused by:
  the given version requirement is invalid
```

I have `tera = "0.1.3"` in my `Cargo.toml`.

**Comment by Keats** [comment]
It sounds like it's a crates.io issue? I can build it fine on my end

**Comment by nabijaczleweli** [comment]
@houqp whole `Cargo.toml` or bust

**Comment by Keats** [comment]
@nabijaczleweli chill, no need to be agressive

**Comment by nabijaczleweli** [comment]
Ain't nobody aggressive here, m8

**Comment by houqp** [comment]
Full Cargo.toml:

```toml
[project]
name = "foo"
version = "0.0.1"

[dependencies]
tera = "*"
```

Also forgot to mention I am using rust 1.10.0 and cargo 0.8.0. I am going to upgrade the cargo to the latest version and try again.

**Comment by Keats** [comment]
Don't use `*` in Cargo.toml.
If you use `tera = "0.1"` it still doesn't work?

**Comment by houqp** [comment]
Yes, I have tried using a specific version. I can confirm that upgrading cargo to 0.11.0 indeed fixes the issue :) Thanks for your help.
