### ISSUE TITLE
Handle the failing serialization

### ISSUE THREAD

**Issue by Boiethios** [Keats/tera#572]
Hi, I have a custom usecase where there can be a serialization failure. Currently, `Context::insert` unwraps instead of returning a `Result`. Is it possible to add a `Context::try_insert` that handles the error? I can write it BTW, just waiting for your feedback.

**Comment by Boiethios** [comment]
Any thoughts about that? Should I create a PR?

**Comment by Keats** [comment]
yep, go for it
