### ISSUE TITLE
Tests aren't distributed to crates.io

### ISSUE THREAD

**Issue by silwol** [Keats/tera#576]
In my attempt to prepare `tera` for packaging on Debian as a dependency for `terender`, I found that the tests are excluded from distribution to crates.io. Packaging on Debian adds so-called autopkgtests which basically run `cargo test`, and are executed automatically after build and repeatedly on Debian CI. We already found several bugs in different crates and upstreamed fixes for those, e.g. when compiling projects for uncommon architectures.

I'd be happy if you could add the tests to the published files, unless you have a good reason not to (e.g. file size of test data might be a reason, but it doesn't appear to me as if that was a problem here).

If you don't intend to publish tests please let me know. In that case, so I can patch out the failing builds, but I'd prefer to have the tests available.

**Comment by Keats** [comment]
I don't mind adding the tests, it was removed by [cargo-diet](https://github.com/the-lean-crate/cargo-diet)
