### ISSUE TITLE
Inspect AST

### ISSUE THREAD

**Issue by tonyhb** [Keats/tera#586]
Is it possible to inspect a compiled template's AST?  Specifically looking to see if I can get all variables defined within a template.

For example, given:

```
<title>{{ title }}</title>
<ul>
{% for user in users %}
  <li><a href="{{ user.url }}">{{ user.username }}</a></li>
{% endfor %}
</ul>
```

It would be great to inspect the AST and find all expressions and statements.  Then, we could generate a list `["title", "users"]` for all variables defined in the template.

**Comment by tonyhb** [comment]
After searching, this is an exact dupe of https://github.com/Keats/tera/issues/542.

Feel free to close - but are there plans to make the AST stable and expose this?

**Comment by Keats** [comment]
The AST is not going to be stable for a while, especially since we keep adding things.
