### ISSUE TITLE
Indexed array/tuple access does not seem to be working

### ISSUE THREAD

**Issue by SergioBenitez** [Keats/tera#59]
If I have a context that includes a tuple or array, I should be able to access tuple or array elements using tuple or array syntax: `tuple.0`, or `tuple[0]`. Unfortunately, while the former is recognized, it does not appear to work. Tera instead issued an error saying that a field named '0' does not exist.

**Comment by Keats** [comment]
Yes right now Tera doesn't support indexing of arrays, didn't think of tuples yet tbh.

I'd be tempted to add the `array[0]` version (even for tuples but you can't index tuple in Rust so not sure how that'd work) but I'm a bit busy atm and will work on macros first when I get some time.

I'll accept a PR that adds the `array[x]` kind of indexing though

**Comment by SergioBenitez** [comment]
You can index tuples and struct tuples in Rust by using the `.i` notation. I think that should be the primary method of indexing tuples in Tera, in addition to the `[i]` syntax.

**Comment by Keats** [comment]
By indexing I meant accessing a tuple value using `tuple[0]`, only `tuple.0` is available in Rust.
This makes it harder to get the value from the context in the renderer, I might be wrong on that (i.e. I want to get index `n` where `n` is a variable of tuple `val`, `val.n` will not work).

If the above is correct - haven't spent time looking at it yet - I guess tuples should be considered/converted to arrays (that probably happens in serde-json?). 
I had another look at the django docs and it seems they use `array.0` kind of notation as well so I'd go with both tuples and arrays using to the `.0` notation only.

**Comment by SergioBenitez** [comment]
Serde-json should already be converting tuples to arrays. The Tera code currently treats any member access as if it was an object lookup. A simple thing could be to treat member access of the for `.int` as array lookups. That would be a simple and effective solution, actually.

I'm not sure I understand your reasoning for only one of `.i` or `[i]`. I'd prefer to have both, and both are used in Rust.

**Comment by Keats** [comment]
Agreed on the first paragraph.

> I'm not sure I understand your reasoning for only one of .i or [i]. I'd prefer to have both, and both are used in Rust.

That's 2 different syntaxes for the same thing (even though in Rust it's a different syntax), not a big fan of that. The `.0` syntax is easier to parse as mentioned in your first paragraph and has  precedent with Django templates.

**Comment by SergioBenitez** [comment]
Django templates uses both .i and [i]

**Comment by Keats** [comment]
Turns out serde-json added a way to get that out of the box, see #61

**Comment by Keats** [comment]
I merged the PR, if the current behaviour is ok for you i'll release 0.2.1 with it

**Comment by SergioBenitez** [comment]
Looks good to me! Nice job!
