### ISSUE TITLE
Support Request: Combine and sort lists in a template

### ISSUE THREAD

**Issue by UebelAndre** [Keats/tera#591]
I have the following template which renders some strings form a set of Vecs (see `deps = [`):
```jinja2
rust_binary(
    name = "cargo_bin_{{ target_name_sanitized }}",
    {% include "templates/partials/common_attrs.template" %}
    # buildifier: leave-alone
    deps = [
        {%- if crate.lib_target_name %}
        # Binaries get an implicit dependency on their crate's lib
        ":{{crate.lib_target_name | replace(from="-", to="_") }}",
        {%- endif %}
        {%- if crate.build_script_target %}
        ":{{ crate_name_sanitized }}_build_script",
        {%- endif %}
        {%- for dependency in crate.default_deps.dependencies %}
        "{{dependency.buildable_target}}",
        {%- endfor %}
        {%- for dependency in crate.raze_settings.additional_deps %}
        "{{dependency}}",
        {%- endfor %}
    ]
    {%- if crate.targeted_deps %} 
    {%- include "templates/partials/targeted_dependencies.template" -%},
    {%- else -%},
    {%- endif %}
)
```

But I want the result of this to be sorted so my hope is that I might be able to generate a new list within the template, sort it, and loop over that before. The thing that I found tricky was that this isn't just a set of vecs, I also need to inject a generated string `":{{crate.lib_target_name | replace(from="-", to="_") }}",` into this list as well. Would someone be able to help me out?

**Comment by Keats** [comment]
You can do it by setting an empty variable at the beginning and then adding stuff to it via `concat` (https://tera.netlify.app/docs/#concat) and then `sort` it and iterate on it to actually output it.

**Comment by UebelAndre** [comment]
Thanks for your reply! Could I get a visual example? 🙏  It'd help me a lot 😅

**Comment by Keats** [comment]
```
{% set deps = [] %}

{%- if crate.lib_target_name %}
  # Binaries get an implicit dependency on their crate's lib
  {% set deps = deps | concat(with=":{{crate.lib_target_name | replace(from="-", to="_") }}") %}
{%- endif %}

{%- if crate.build_script_target %}
  {% set deps = deps | concat(with=":{{ crate_name_sanitized }}_build_script") %}
{%- endif %}
{%- for dependency in crate.default_deps.dependencies %}
  {% set_global deps = deps | concat(with=dependency.buildable_target) %}
{%- endfor %}
{%- for dependency in crate.raze_settings.additional_deps %}
  {% set_global deps = deps | concat(with=dependency) %}
{%- endfor %}

deps = [
 {% for dep in deps | sort %}
    "{{ dep }}",
 {% endfor %}
]
```

Something like that

**Comment by UebelAndre** [comment]
Thanks! This helped a lot, there's two things I noticed though

This doesn't work
```jinja
{%- if crate.build_script_target %}
  {% set deps = deps | concat(with=":{{ crate_name_sanitized }}_build_script") %}
{%- endif %}
```

The workaround for me was 
```jinja
{% set deps = deps | concat(with=":" ~ crate_name_sanitized ~ "_build_script") %}
```

Additionally, there doesn't seem to be a way to control whitespace in a comment
```jinja
{#- A blank line will get rendered here #}
{% set deps = deps | concat(with=":" ~ crate_name_sanitized ~ "_build_script") %}
```

Maybe there's something I'm missing for the two issues I ran into but other than that, your example helped a lot, thank you!

**Comment by Keats** [comment]
Ah yes sorry I forgot about string concatenation!

> there doesn't seem to be a way to control whitespace in a comment

You're right, that's an oversight.

**Comment by UebelAndre** [comment]
I created https://github.com/Keats/tera/issues/594 but I otherwise think I got the help I was looking for. Thanks!
