### ISSUE TITLE
Question: Filter, different to.

### ISSUE THREAD

**Issue by Darkkaiserl** [Keats/tera#598]
Hi, it's only a question, excuse my ignorance...
how can i get this data?.

`{% set r_prods = prods | filter(attribute="amount", value!=0) %}`

![image](https://user-images.githubusercontent.com/30737924/105893987-88fdf080-5ff2-11eb-9451-6814b144495d.png)
Thanks.

**Comment by Keats** [comment]
The `filter` filter doesn't support filtering where the value doesn't match right now.
