### ISSUE TITLE
Render template with Null (empty struct) context

### ISSUE THREAD

**Issue by frustak** [Keats/tera#600]
### Current behavior: 
Trying to render a template with a Null context results in:
`Error { kind: Msg("Creating a Context from a Value/Serialize requires it being a JSON object"), source: None }'`
### Desired behavior:
I would like to be able to render a template with empty context, as there's not always some context to pass (it's basically a normal HTML file with extra features of Tera like inheritance...)
### Example code:
```Rust
use serde::Serialize;
use tera::{Context, Tera};

#[derive(Serialize)]
struct Empty;

fn main() {
    let context = &Context::from_serialize(&Empty).unwrap(); // The Error occurs here
    let tera = Tera::new("templates/*").unwrap();
    tera.render("index.tera", context).unwrap();
}
```

There are some workarounds but I believe it's not necessary to return an error in this case.

**Comment by Keats** [comment]
It should be an error: a context needs to have keys and values otherwise you cannot access anything from the template. If you want to render a template with an empty context, do:

```
tera.render("index.tera", Context::default()).unwrap();
```
