### ISSUE TITLE
Is {% include var %} supposed to work?

### ISSUE THREAD

**Issue by xpe** [Keats/tera#603]
Neither of these two code examples work for me:

```tera
{% include "foo/" ~ name ~ ".html" %}
```

```tera
{% set filename = "foo/" ~ name ~ ".html" %}
{% include filename %}
```

Of course, `name` is defined; e.g. `{% set name = 'bar' %}`

I'm testing these in Zola in a macro definition.

**Comment by Keats** [comment]
No it's not. The idea being that all imports should/can be resolved at template compilation time.

**Comment by xpe** [comment]
What variables are not determined at compilation time?

The variables I want for this usage are defined at compilation time.

**Comment by xpe** [comment]
Here is another example of what I'm trying to do:

```
{% macro foo(title, id) %}
  <div class="foo">
    <div>
      <h2>{{ title }}</h2>
    </div>
    <div class="foo-{{ id }}">
      {% include "{{ id }}.html" %}
    </div>
  </div>
{% endmacro %}
```

**Comment by Keats** [comment]
> What variables are not determined at compilation time?

All of them, since at template compilation you do not have any variables, unless your macro example is hardcoding the ids in the templates.

**Comment by xpe** [comment]
Thanks for your reply. Is there some documentation I can read to get more information?... I think I'm misunderstanding something. Are there multiple phases of processing? Where does *template compilation* fit in?

Perhaps naively, I would have thought that Zola would have the information it needs to convert, say, `{% include "foo/" ~ name ~ ".html" %}` to `{% include "foo/bar.html" %}`. ... I understand, generally, that it depends on the order of processing and evaluation -- but I'm unclear on what these steps are.

**Comment by Keats** [comment]
> Are there multiple phases of processing? Where does template compilation fit in?

**Comment by xpe** [comment]
Thanks. I have to admit I don't have the vocabulary aligned, because static-site generators (SSGs) are a bit different than the usual web server. If I may talk out loud -- let me see if I've got this correct... For a SSG, what you describe as "run-time" is generation time; i.e. `zola serve`. Correct? 

If so, I wonder if there is a strong argument to be made that erroring out when running `zola serve` is better than limiting functionality?

**Comment by Keats** [comment]
> I have to admit I don't have the vocabulary aligned, because static-site generators (SSGs) are a bit different than the usual web server.

Forget about the SSG or web part.
I call the 2 phases compilation and interpretation:

1. compilation: 
    1. read the template files/string and generate an AST for each
    2. in Tera, we check that all the templates are accounted for (inheritance / include)
2. interpretation: the user asks to render a template with some context, and the variables get replaced with their value

The `include` check happens in phase 1.

To go back to `zola serve`, to know that an included file is missing if the check happened in phase2, we would need to load all the templates & the content and try to re-render everything and it would then fail. With it in phase1, it errors as soon as we load the templates basically.

**Comment by dar5hak** [comment]
Would it make sense to include a line or two about this in the documentation? I faced this exact scenario and ended up here, but not everyone might, so.

I can make a PR if needed.

**Comment by Keats** [comment]
Go for it
