### ISSUE TITLE
Naming endblocks : required?

### ISSUE THREAD

**Issue by xpe** [Keats/tera#604]
From https://tera.netlify.app/docs/#base-template :
> The only difference with Jinja2 being that the endblock tags have to be named.

I have not been naming endblocks. So far, I haven't noticed a problem.

Is the documentation incorrect?

**Comment by xpe** [comment]
What are (were?) the technical reasons for requiring the endblock to be named?

```tera
{% block scripts %}
  <script src="/foo/bar"></script>
{% endblock scripts %}
```

```

**Comment by Keats** [comment]
Ah this should be removed, it was before 1.0. `endblock` name are optional now.

> What are (were?) the technical reasons for requiring the endblock to be named?

No technical reasons, it was there to provide good error messages when having mismatched blocks.
