### ISSUE TITLE
Is the "huge loop" benchmark measuring what it intends?

### ISSUE THREAD

**Issue by epage** [Keats/tera#606]
I was taking inspiration from Tera's benchmarks for Liquid but [huge_loop](https://github.com/Keats/tera/blob/master/benches/tera.rs#L189) seems off unless I'm misunderstanding Tera or Handlebars.

```rust
    let rows = RowWrapper { real, dummy };

    let mut tera = Tera::default();
    tera.add_raw_templates(vec![("huge.html", "{% for v in rows %}{{v}}{% endfor %}")]).unwrap();
    let mut context = Context::new();
    context.insert("rows", &rows);
```
Here, it is iterating on the `rows` object which has two elements.

From [another Issue](https://github.com/Keats/tera/issues/298#issuecomment-394988157) it sounds like this is meant to mirror [handlebars](https://github.com/sunng87/handlebars-rust/blob/master/benches/bench.rs#L141)
```
    handlebars
        .register_template_string("test", "BEFORE\n{{#each real}}{{this.v}}{{/each}}AFTER")
        .ok()
        .expect("Invalid template format");

    let real: Vec<DataWrapper> = (1..1000)
        .map(|i| DataWrapper {
            v: format!("n={}", i),
        })
        .collect();
    let dummy: Vec<DataWrapper> = (1..1000)
        .map(|i| DataWrapper {
            v: format!("n={}", i),
        })
        .collect();
    let rows = RowWrapper { real, dummy };

    let ctx = Context::wraps(&rows).unwrap();
    c.bench_function("large_loop_helper", move |b| {
        b.iter(|| handlebars.render_with_context("test", &ctx).ok().unwrap())
    });
```
Here I believe `rows` is the root object in the context so the template variable `real` maps to the Rust variable `rows.real` which is an array of 1000 `DataWrappers`.

**Comment by Keats** [comment]
Yep, it looks like it should do `{% for real in rows.real %}{{real.v}}`
