### ISSUE TITLE
Loading templates at compile-time

### ISSUE THREAD

**Issue by scd31** [Keats/tera#611]
I'm using Tera in a command line utility and it's not ideal that it requires loading the templates at runtime. Is there a way to load them at compile-time, possibly by doing some `build.rs` trickery? I looked through the documentation and couldn't find anything.

**Comment by Keats** [comment]
You can do something like that: https://github.com/getzola/zola/blob/master/components/templates/src/lib.rs#L9-L43

**Comment by scd31** [comment]
That makes sense. Thanks!

**Comment by Keats** [comment]
You're welcome!

**Comment by mfreeborn** [comment]
I just came across this same issue and I think it would be great if there were even a brief statement in the docs to explain how to do this.
