### ISSUE TITLE
Adding tests (not unit test, the tester feature)

### ISSUE THREAD

**Issue by Keats** [Keats/tera#62]
Left to add:

- [x] divisibleby
- [x] iterable (basically tuples and arrays, but in a way strings are iterable too hmm)

All testers are in `src/testers.rs`

**Comment by SergioBenitez** [comment]
Are there any other ones that seem prudent to add?

**Comment by Keats** [comment]
`divisibleby` can probably be added looking at http://jinja.pocoo.org/docs/dev/templates/#builtin-tests. 
`iterable` could be added as well to check if it's an array

**Comment by SergioBenitez** [comment]
It might be better to add a modulo `%` operator instead of `divisibleby`.

`iterable` sounds okay, but then we should add a test for other types, like `integer`, `float`, `null`, etc.

**Comment by SergioBenitez** [comment]
Oh, looks like some of those are in #63 already!
