### ISSUE TITLE
Add `Context::remove`

### ISSUE THREAD

**Issue by yykamei** [Keats/tera#627]
It would be useful to remove a key from an old context.

I'm writing a code to make `Tera` generate a rendered string with an instance of `Context` and store the context to a vector.
This vector value may include a bunch of contexts, so I want to omit unused keys from each context to save data size.

This is an example of my case. `body` of `context` won't be used after rendering, so I want to remove `"body"` from `context`.

```rust
let tera = Tera::new("templates/**/*.html").unwrap();
let mut summaries: Vec<Context> = Vec::new();

for content in contents {
    let mut context = Context::new();
    context.insert("title", content.title);
    context.insert("body", content.body);

    println!("{}", tera.render_str("post.html", &context).unwrap());

    context.remove("body") // <-- I want to exclude huge data.
    summaries.push(context);
}

do_something_with(summaries);
```

Does it make sense? If so, I want to open a PR soon.

Thanks,

**Comment by Keats** [comment]
Yep, makes sense

**Comment by yykamei** [comment]
Thank you! I opened a PR #628.
