### ISSUE TITLE
[Feature Request] Add built-in filter for formatting numbers

### ISSUE THREAD

**Issue by maxdeviant** [Keats/tera#630]
This may be a somewhat niche use case, but it would be nice to be able to format numbers that are generated dynamically. Some background context [here](https://maxdeviant.com/shards/2021/how-hard-is-it-to-format-a-number/).

The way I envision it would be using something like [`num_format`](https://docs.rs/num-format/0.4.0/num_format/) to power a filter that would take an (optional) locale and format the input accordingly:

```mustache
{{ 1000000 | num_format }} <!-- 1,000,000 -->

{{ 1000000 | num_format(locale="fr") }} <!-- 1 000 000 -->
```

Would be happy to open a PR if this is something we want to add.

**Comment by Keats** [comment]
How big would the filter be in terms of code? I'm trying to avoid adding too many filters to Tera itself (especially if they add a dependency) since it's easy to add it to your own project if you need it.

**Comment by maxdeviant** [comment]
> How big would the filter be in terms of code?

I think the filter itself would be fairly small, but we would pull in the `num_format` crate.

> I'm trying to avoid adding too many filters to Tera itself (especially if they add a dependency) since it's easy to add it to your own project if you need it.

In this case I'm using Tera through Zola. Is this the sort of thing that would be better suited as a Zola feature request?

**Comment by maxdeviant** [comment]
Going to close this out in favor of an issue on the Zola repo: https://github.com/getzola/zola/issues/1459.
