### ISSUE TITLE
Add mechanism to get list of all registered templates

### ISSUE THREAD

**Issue by SergioBenitez** [Keats/tera#631]
Rocket needs a way to determine when the user has manually added templates to a Rocket-managed instance of `Tera`. To do this, Tera needs to expose a mechanism to get a list of all template names. For example, `handlebars` exports https://docs.rs/handlebars/3.5.5/handlebars/struct.Handlebars.html#method.get_templates.

At present, I am using the hidden `Tera.templates` field, but a semver-compatible solution would be appreciated. Exposing a method `template_names()`, marking the field `pub` without `#[doc(hidden)]`, or simply promising to keep the field `pub` and of the same type would suffice.

**Comment by Keats** [comment]
Let's do the `get_template_names()` fn

**Comment by SergioBenitez** [comment]
Would you like a PR or will you be handling it?

**Comment by Keats** [comment]
Would be great if you can do a PR

**Comment by SergioBenitez** [comment]
Done!
