### ISSUE TITLE
[Feature request] Add builtin filter shuffle 

### ISSUE THREAD

**Issue by mlcdf** [Keats/tera#634]
Hello,

I think a builtin filter `shuffle` would be both super useful and to easy implement (I need one lol).
What do you think?

Taking cues from the [reserve](https://github.com/Keats/tera/blob/17745fcabbf31c6f8c5a422d417d003405b5df64/src/builtins/filters/common.rs#L32) filter, I think I can submit a PR.

**Comment by Keats** [comment]
Yes
