### ISSUE TITLE
Better compiling & rendering errors

### ISSUE THREAD

**Issue by Keats** [Keats/tera#64]
If we can get errors filename/line it will improve the debugging experience by quite a bit.

Also stop using `panic!` and propagate the errors across everything to make it easy to integrate with other tools so they don't need to use `catch_unwind`

Should be done on the v0.5 branch

**Comment by Keats** [comment]
It would be nice to have the same kind of errors as Rust does (the new errors)

https://blog.rust-lang.org/images/2016-09-Rust-1.12/borrowck-error.png

**Comment by Keats** [comment]
Got a good chunk of it done, two things left:

- [ ] Show line where error occured in parsing (might be implement in pest directly)
- [ ] Give more context on rendering errors, right now it gives the origin file for the error, not the file in which the error actually occurs (with inheritance/macros we load other files)

**Comment by zoumi** [comment]
Last time I used tera to parse templetes, it only throwed an error at a time. So I had to compile seven times to dig out seven errors.

**Comment by Keats** [comment]
Good point, i'll see if i can return all the errors at once instead of one by one in 0.5

**Comment by Keats** [comment]
@zoumi just to be clear, did you have several errors in the same template or several errors in multiple templates? The current parser stops when it encounters an error so we can only get the first one for a file

**Comment by zoumi** [comment]
In multiple templates.

**Comment by Keats** [comment]
Would something like that work?

```
* Failed to parse 'base.html'
-- Invalid Tera syntax at line 5, column 1
* Failed to parse 'users/profile.html'
-- Invalid Tera syntax at line 3, column 10
```

Later on we will show the line/col in the console as well but that will happen once `pest` reaches 1.0

**Comment by zoumi** [comment]
1,I think it will be better to replace relative path to absolute path.Because in future, some editors may have plugins to capture these errors and then auto locate them in files(For vim users,they can run generated binary with :make and the quickfix will be able to capture these error and then locate them in files).

2,Because the error message is short enough, a single line error message will seem compact:
Invalid Tera syntax at: full/path/to/some.html:line:column
(You may not agree with this.)

**Comment by Keats** [comment]
I like the idea of `full/path/to/some.html:line:column` but pest will provide rustc-like errors in 1.0 in a few weeks so not going to change them in tera itself until then. I'll make sure point 1 is ok if i'm the one to implement error reporting in pest.
