### ISSUE TITLE
Extend method should also copy over functions

### ISSUE THREAD

**Issue by Ten0** [Keats/tera#640]
It's not intuitive that the only thing not copied over is functions. This easily causes errors.
I think we should also copy over functions when calling `Tera::extend`.

**Comment by Keats** [comment]
I can't remember why it doesn't tbh. I would take a PR.

**Comment by Ten0** [comment]
> this is a breaking change so for the next major version.

How is this breaking?

**Comment by Keats** [comment]
You're right it's not breaking
