### ISSUE TITLE
spaceless feature from Django

### ISSUE THREAD

**Issue by jsha** [Keats/tera#641]
For rustdoc, [we're adopting tera templates](https://github.com/rust-lang/rust/pull/86157#issuecomment-864659727). We try to generate HTML with as little unneeded whitespace as necessary, to keep page sizes small. Currently we're doing that manually; with tera templates we'll be using `{%- -%}`. But we still have to deal with newlines and indenting whitespace that we use purely to make the templates more readable.

Per the linked issue, we'll be adding an empty comment to the end of each line, with the whitespace control characters: `{#- -#}`. That does the job, but it's somewhat tedious and hurts readability.

Evidently [Django has a `spaceless` directive](https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#spaceless) that is HTML tag aware and knows how to strip all whitespace between tags. If we could use that with tera templates it could considerably improve the readability and writeability of our templates.

There's a similar issue for attributes within a tag, and I don't know if other place in the jinja ecosystem have a good solution. Specifically, given a template like:

```
<link rel="stylesheet" type="text/css"
      href="{{static_root_path | safe}}normalize{{page.resource_suffix}}.css">
```

We'd like that to render with exactly one space character between `css"` and `href=`. The end-of-line-comment trick doesn't work because it would concatenate the attributes. We can use a `{{- " " -}}`, but it would be great if there were something similar to `spaceless` for this case.

**Comment by Keats** [comment]
That means Tera need to parse HTML. I would take a PR for it if whatever dependency it requires is not enabled by default.

**Comment by Urgau** [comment]
Just by curiosity I looked at what Django [does](https://github.com/django/django/blob/ca9872905559026af82000e46cde6f7dedc897b6/django/utils/html.py#L195-L197), and it's really "stupid":
```python
def strip_spaces_between_tags(value):
    """Return the given HTML with spaces between tags removed."""
    return re.sub(r'>\s+<', '><', str(value))
```
It's just a regex that's do a substitution.

**Comment by Keats** [comment]
Oh i'm surprised that works but then it would be easy to make that a filter in Tera
