### ISSUE TITLE
Parsing template with `{- " " -}}` should error

### ISSUE THREAD

**Issue by jsha** [Keats/tera#642]
Steps to reproduce:

Parse template with:

```
<img {- " " -}}
  src="http://example.com/gif.png"
```

Expected: error

Actual: outputs the `{- " " -}}`

(Note: `{- " " -}}` is a typo for `{{- " " -}}`, which I'm using to break up an HTML tag's attributes across multiple lines while keeping exactly one space between attributes)

**Comment by Keats** [comment]
That's a valid template though? There are no reasons it should error. I haven't checked in Django but Jinja2 does output the same thing as Tera.
