### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by Keats** [Keats/tera#66]
Macros are a way to do what most templates engine do as include but with a known context as they look like functions.

See [Jinja2 docs](http://jinja.pocoo.org/docs/dev/templates/#macros) and some [real life examples](https://github.com/pallets/website/tree/master/templates/macros).

A few things to consider when porting them:
- import
- `call` syntax
- args
## Import

Jinja2 has 2 ways to load macros (http://jinja.pocoo.org/docs/dev/templates/#import):

```
{% import "macros.html" as macros %}
{% from "macros.html" import macro_1 , macro_2 %}
```

Since the equivalent of `from x import *` is not great in general, I'd be interested in the second form, that is `{% from "macros.html" import macro_1 , macro_2 %}` which makes it clear what you want to import. 
That means `Template` need to have a `pub macros: HashMap<String, Node>` or something similar in order to resolve the macros easily. 
Since we are namespacing macros by filename, several macros can have the same name which can cause an issue if we are trying to use 2 macros with the same name in the same file.
Jinja2 allows renaming imports `{% from 'forms.html' import input as input_field, textarea %}
` and we could/should support that syntax, waiting for feedback on that point
## Call syntax

I'm not sure `call` is that needed and it makes things a bit hard to understand imo. For example from the Jinja2 docs:

```
{% macro dump_users(users) -%}
    <ul>
    {%- for user in users %}
        <li><p>{{ user.username|e }}</p>{{ caller(user) }}</li>
    {%- endfor %}
    </ul>
{%- endmacro %}

{% call(user) dump_users(list_of_user) %}
    <dl>
        <dl>Realname</dl>
        <dd>{{ user.realname|e }}</dd>
        <dl>Description</dl>
        <dd>{{ user.description }}</dd>
    </dl>
{% endcall %}
```

seems overly complicated to read for what should be simple.
Let's ignore `call` for the first pass of macros.
## Args

To match what the filters are doing in Tera, all args to a macros should be kwargs.
## Motivation for macros

From the creator of Jinja2:

> Another thing i strongly disagree with but I can see the motivation. Macros in Jinja I prefer so much over includes because it becomes clear what values exist. Includes become really messy unless you are very organized. Macros (which are just functions) accept the parameters and it becomes clear what the thing does. Just look at that macro as an example: https://github.com/pallets/website/blob/master/templates/mac...
> It's absolutely clear what it accepts as parameters. If that was a partial include the "caller" needs to set up the variables appropriately and there is no clear documentation on what the template wants et

**Comment by Keats** [comment]
@SergioBenitez @andrelmartins if you are interested.

I'll try to implement that soon since I think it's the last big feature missing but I'm moving continents next week so will be a bit busy for a while.

**Comment by andrelmartins** [comment]
Here's an alternative syntax suggestion.

## Import

An alternative to allowing per macro renames, would be to require namespace naming. I think this aligns better with the per-file namespacing and avoids having to rename a lot of macros, at the expense of a more verbose call site (see below). Of course, it would be an error to have more than one import with the same namespace name in the same template file.

Short form (naming required):
`
{% import "macros.html" as macros %}
`

Long form:
`
{% import "macros.html" as mymacros : macro1, macro2 %}
`

Or, alternatively, using the "from" syntax:
`
{% from "macros.html" as mymacros import * %}
`
`
{% from "macros.html" as mymacros import macro1, macro2 %}
`

## Macro use

At the call site, it would be required to prefix the macro name with the namespace:
`
{{ mymacros::macro1(arg1, arg2) }}
`

## Alternatives

A slight variant would be to allow one to omit the namespace naming and then macros from that import would fall into a "root" namespace and not require the namespace prefix for macro use. That complicates the code a bit more and re-introduces a more limited version of macro name collision. I would lean towards requiring namespace naming.

## Extra features

A more pie in the sky feature would be to allow registering Rust functions as macros. Something like this:

```rust
let mymacros = MacroSet::new();

mymacros.add(args1, func1);
mymacros.add(args2, func2);

tera.import_macros(mymacros);
```

where "args1" would be a list of context names and the add function would be something like:
```rust
pub fn add<F>(&mut self, args: Vec<String>, usermacro: F)
    where F: Send + Sync + 'static + Fn(&Context) -> TeraResult<String>
```

**Comment by Keats** [comment]
I like the short form, not so much the others (if i import something by name, I don't want to have to prefix it). Only having the short form should solve most (all?) of the naming collisions.

I'm curious if @mitsuhiko has some insight on that or some things he would like to change from Jinja2
