### ISSUE TITLE
How are enums represented?

### ISSUE THREAD

**Issue by UebelAndre** [Keats/tera#669]
I did a `ctrl+f` for `enum` in the docs and didn't find anything. Is it possible to take
```rust
pub enum Numbers {
    One,
    Two,
    Three,
}
```
and use the enum variant in a template? Here I use some pseudo `enum` function just to demonstrate the example.
```jinja2
{% if enum(number) == "Numbers::One" %}
One
{% elif enum(number) == "Numbers::Two" %}
Two
{% elif enum(number) == "Numbers::Three" %}
Three
{% endif %}
```

**Comment by Keats** [comment]
There is a magical variable to see how things are serialized: `__tera_context`. Do `{{ __tera_context }}`.
Essentially Tera serializes everything via `serde_json` so it follow whatever setup you put on your `#[serde]` macros for the enums.

**Comment by UebelAndre** [comment]
I've found that in some cases `for` loops work:
```jinja
{%- for variant, members in enum %}
variant = {{ variant }}
members = {{ members | json_encode | safe }}
{%- endfor %}
```

Hopefully that helps someone. Since it's what I used to solve for my issues, I'll close the ticket. Thanks Keats!
