### ISSUE TITLE
Regression between version 0.2 and 0.3

### ISSUE THREAD

**Issue by andrelmartins** [Keats/tera#67]
Nested 'if' in 'for' results in "internal error: entered unreachable code" at render.rs:105. The following code is a minimal example to reproduce the issue.

```rust
extern crate tera;
use tera::Tera;
use tera::Context;

fn main() {
    let mut tera = Tera::default();
    tera.add_template("nested", "{% for val in seq %} {% if val == sel %} on {% else %} off {% endif %} {% endfor %}");

    let mut context = Context::new();
    context.add("sel", &2u32);
    context.add("seq", &vec![1,2,3]);

    let page = tera.render("nested", context).unwrap();
    println!("{}", page);
}
```

I went back through the commits and the problem is introduced in commit 2154c3e8092ab28fdde2d868ab003251682bf22c  "Add tests and remove using AST in tests fn".

**Comment by Keats** [comment]
Thanks! I published 0.3.1 that fixes that and yanked 0.3.0
