### ISSUE TITLE
如何循环一个数字?

### ISSUE THREAD

**Issue by 1148118271** [Keats/tera#685]
问题为: 
![image](https://user-images.githubusercontent.com/56823989/138275930-36f33dff-e2ea-480d-90e7-e1bde6e8fb7f.png)

![image](https://user-images.githubusercontent.com/56823989/138275354-e26366a0-2dde-4839-b101-737e2b04f5e2.png)

或者是 后台返回过来的一个number类型的变量
```
let len: u32 = 15;

{%  for in  len %}
xxxx
{% endfor %}
```

**Comment by sunkaifei** [comment]
Hello: May I ask if it has been resolved? I also encountered this problem

**Comment by Keats** [comment]
You need to use {% for i in range(end=5) %
