### ISSUE TITLE
(Rant) 1.14.0 changes signature of `Context`, breaks grcov

### ISSUE THREAD

**Issue by Minoru** [Keats/tera#689]
Hello,

Tera 1.14.0 adds a generic parameter to `Context`, which breaks anyone who mentioned this type in their code. One such program is grcov, which is used by many to calculate test coverage. I see [the warning in the README](https://github.com/Keats/tera#semver), but isn't `Context` public?

I already submitted a PR to fix grcov, and I don't expect you to do anything about this. Just please, be more considering the next time you change a public type ;)

Thanks!

**Comment by Keats** [comment]
Ah shit I forgot about that :(
The new version was needed because 1.13 made `Context` not sync+send by accident and that was a way to fix it.

Are you holding the context in a struct somewhere? Most use cases of `Context` should not change?

**Comment by Elrendio** [comment]
Holla,

This is a breaking change, we'll fix our code but it kinda broke unexpectedly our CI 😬😬😬

Have a nice day!

**Comment by Keats** [comment]
sorry :(

**Comment by Minoru** [comment]
@Keats 

> Are you holding the context in a struct somewhere? Most use cases of Context should not change?

No, grcov was simply unlucky to *mention* the type at all: https://github.com/mozilla/grcov/pull/697/files#diff-4670146df578274a2be5b97fc67deab17145720f0deeada6fc8d2fa50901d65fL211 Easily fixed, as you can see.

<hr/>

For anyone coming to this issue because of grcov: you can fix you CI by forcing Cargo to use Cargo.lock by running `cargo install --locked grcov`.

**Comment by Keats** [comment]
sorry again :(
For what it's worth this is probably the last release for a long time so it shouldn't happen again. I'll be more careful in the future, the last 2 releases have been messy

**Comment by Manishearth** [comment]
Perhaps you could yank the 1.14.0 release (and rerelease it as 2.0?)

Either way I'm working on fixing this in grcov

**Comment by Keats** [comment]
I'm thinking of yanking 1.14 and removing the thread local context from v1 (a breaking change still but affecting fewer people) and keep that feature for v2 but I see a few PRs already mentioning that issue.

What do you think?

**Comment by dureuill** [comment]
Hello!

I'm just reporting that [mdbook-tera](https://github.com/avitex/mdbook-tera/issues/7) is also affected by this issue. I think a yank and republish as 2.0.0 would be good so as to spare downstream users from modifying their code. 

Thank you for making tera BTW, I've been using it in a mdbook (for creating macros that insert [bulma.io](https://bulma.io) elements in page without having to write HTML everywhere) and it's been really useful :+1:!

**Comment by marco-c** [comment]
I've merged @Manishearth's PR in grcov and released a new version with it.

**Comment by Minoru** [comment]
@Keats I think yanking 1.14 is a good idea. At least you won't have to deal with constant torrent of users who upgraded to 1.14 and found it broke their code :) People who already upgraded are probably the more active ones, and they can just roll back their changes (and yank any releases they made). Still a bit of a mess, but at least it won't spread further.

**Comment by Keats** [comment]
I've just yanked it and will publish a 1.15 with the non breaking changes from 1.13, sorry again about that.

I'll add context level functions to the feature list of v2 and will probably _not_ release the current code as I don't want a v2 to just be a small feature like that.

**Comment by Keats** [comment]
PR: https://github.com/Keats/tera/pull/690

**Comment by Manishearth** [comment]
@marco-c thanks! note: if https://github.com/Keats/tera/pull/690 lands, you might have to yank the grcov update, but that seems easy

**Comment by marco-c** [comment]
@Manishearth I've released 0.8.4 after reverting your PR (to go back to tera 1.12)

**Comment by marco-c** [comment]
And I've yanked 0.8.3, which had tera 1.14.

**Comment by Manishearth** [comment]
Thanks!

**Comment by Manishearth** [comment]
@marco-c wait, #690 hasn't landed yet, so this will be broken till it lands. which is fine i guess.

**Comment by Keats** [comment]
1.15 is published

**Comment by Minoru** [comment]
Thanks! `cargo install grcov` succeeds now (building against tera 1.15), so the issue is resolved.
