### ISSUE TITLE
Support for 'env_logger'

### ISSUE THREAD

**Issue by stephanbuys** [Keats/tera#7]
Would it be feasible to include env_logger into the dependencies? That way the library can be peppered with debug and trace statements, which could help a lot when debugging issues.

**Comment by Keats** [comment]
At which level do you want logs? lexer,parser and/or render ?

Lexer/parser will be panics (with more info and nicer formatting later on) so I guess the render?

**Comment by stephanbuys** [comment]
well, env_logger is very powerful, so just having it available will allow RUST_LOG=debug anytime it is appropriate, I would say render for sure, but once its in the crate other places may make sense too.

**Comment by Keats** [comment]
Closing that, i don't think that's super relevant to Tera, might add some logging later on in the rendering if needed
