### ISSUE TITLE
Automatically escape rendered HTML.

### ISSUE THREAD

**Issue by SergioBenitez** [Keats/tera#70]
At present, Tera emits passed-in text directly in templates. This means that unless the user escapes the text being rendered, he/she is open to XSS attacks. Other template engines, like Handlebars, automatically escape text, precluding this attack vector, unless the user explicitly asks for unescaped text. I propose that Tera do the same.

Specifically, text rendered with `{{ }}` should automatically escape the input text, while text rendered with `{{{ }}}` should emit the raw text.

**Comment by Keats** [comment]
I had #15 for that but I actually forgot to do the HTML escaping in it.
I suggest `{{ }}` escapes by default (with an option in Tera to disable automatic escaping) and `{{ variable | safe }}` to un-escape rather than the `{{{ }}}`

**Comment by SergioBenitez** [comment]
How would `variable | safe` work? I imagine that there's nothing a filter can do to prevent escaping as escaping happens at a lower level. Correct me if I'm wrong.

Also, `{{{ }}}` should already be familiar from other languages, can be syntax highlighted easily, and is easier to type.

Is there a good escaping library for Rust or would we need to write our own? Happy to do so if the latter.

**Comment by Keats** [comment]
For escaping HTML: https://github.com/Keats/tera/blob/master/src/filters/string.rs#L172-L181 is taken from django (https://github.com/django/django/blob/master/django/utils/html.py#L38-L74). We can extract the function in another module to be used in the rendering as well.

The way Jinja2 and Django do is having a SafeString or similar that extends the basic object in python. The idea in Tera would be the renderer checks if a `safe` filter is used and only escapes if autoescape is on and a safe filter is not used. 
I'd go with familiarity with Django/Jinja2 over Handlebars etc if possible

To turn on/off autoescaping, we can use something similar to the way Jinja2 does:
- have a list of extensions on which to use autoescape (ie ["html", "htm", "xml"])
- add a fn `tera::autoescape_on(extensions: Vec<String>)` for the user to customise the extensions

**Comment by SergioBenitez** [comment]
That function will be very, very slow, and allocate way more memory than is required. Here's a _much_ faster implementation that also escapes the ` (grave accent) symbol for IE:

```rust
fn escape(input: &str) -> String {
    let mut output = String::with_capacity(input.len() * 2);
    for c in input.as_bytes() {
        match *c as char {
            '<' => output.push_str("&lt;"),
            '>' => output.push_str("&gt;"),
            '&' => output.push_str("&amp;"),
            '"' => output.push_str("&quot;"),
            '\'' => output.push_str("&#39;"),
            '`' => output.push_str("&#96;"),
            _ => output.push(*c as char)
        }
    }

    output
}
```

I don't particularly like the idea of having a filter than changes the behavior of an operator. It seems wrong; filters and operators (`{{ }}` here) are different categories of things. It seems very strange to special case one filter that changes how an operator works.

The turning on/off for different extensions sounds fine though.

**Comment by SergioBenitez** [comment]
Ping! @Keats

**Comment by Keats** [comment]
I like your version of `escape` better, if you can do a PR or i'll push later

Still unsure about the `{{{ }}}` vs `| safe` in terms of familiarity.
In short it's between Jinja/DJango vs Mustache/Handlebars template families

**Comment by Keats** [comment]
Started #71 for escape related things, I'll start with implementing the on/off for extensions and then we can decide the syntax to mark things safe

**Comment by Keats** [comment]
It's now in master, we can open another issue to discuss the syntax if wanted
