### ISSUE TITLE
Interpret string variable as Tera?

### ISSUE THREAD

**Issue by DesmondWillowbrook** [Keats/tera#700]
Something like the `eval()` function in Python,
```tera
{# s = {{ now() | date(format="%Y") }} #}

{{ tera(s) }}

{# or #}

{{ s | tera | safe}}
```

I am rather new to the language, so please let me know if I'm making sense.

**Comment by Keats** [comment]
When would you need that?

`{% set s = now() | date(format="%Y") %}` should work

**Comment by DesmondWillowbrook** [comment]
I would like to interpret a configuration variable; for example, custom copyright text that includes the year without using JS. I imagine that it would be the easiest solution, considering that I would write a Tera expression for it if I did have to write it in a template (I'm using Zola). 

(Like so: `config = "{{ now() | date(format="%Y") }}"`)

While I could write various options to enable or disable this behaviour and get prefix and suffix strings the idea is more to provide complete customizability so one could load in an image as their footer for example. I _could_ just point people to the template file in case they want to edit it, but I still think it's a cool idea and the most elegant way of doing things.

Just like we can apply "safe" as a filter to not escape HTML may be similarly we could apply a Tera filter to interpret strings as Tera code.

I understand if this sounds a bit too gnarly or convoluted to add into the language, though I would be excited to try implementing it if you think that this will fits in with what Tera is meant to do.

**Comment by Keats** [comment]
I'm not sure it makes sense for something like that to be in Tera itself
