### ISSUE TITLE
Support new Tera without a dir?

### ISSUE THREAD

**Issue by jmjoy** [Keats/tera#708]
In some case, the template content is written in rust code, and use `tera::add_raw_template` to add the template, so that it can be built to a single binary without template files.
Now I use `Tera::new("/tmp/not-exists/*")` to avoid the error of new, is it a good choice to make a new method of Tera to new Tera without a dir?

**Comment by Keats** [comment]
`Tera::default`()?

**Comment by jmjoy** [comment]
> `Tera::default()`?

Sorry, I don't find this method before. :sweat_smile:
