### ISSUE TITLE
Why does `autescape_on` require `&'static str`?

### ISSUE THREAD

**Issue by tobx** [Keats/tera#709]
> Why is this a `Vec<String>` and not just a `Vec<&'static str>`? In fact, does it need to be a `Vec` at all? Why not a `[&'static str; 3]`? You'd need a `Vec` if you want to allow users to add their own extensions.

_Originally posted by @SergioBenitez in https://github.com/Keats/tera/pull/71#discussion_r88540789_

I would like users to generate their own templates for a static content generator that uses Tera internally. The users should be able to choose the file extension and if their templates use escaping or not.

The only way I see is to leak memory `Box::leak` to make `autoescape_on` dynamically customizable. Why did the above pull request change it to `&'static str`?

It would be easier though if a function could be added to enable or disable escaping for all file extensions like `Tera::enable_escaping_globally(&self, bool)`

**Comment by tobx** [comment]
I have updated the initial issue description.

**Comment by Keats** [comment]
It's because for 99.9% of the users they hardcode it in their codebase once or use the default one, there was no real need to have non `&'static str` so far

**Comment by tobx** [comment]
Ok, so the reason is that the other users do not have to type `.into()` I guess. Fair enough, but enabling or disabling escaping globally could mean even less typing for many users. Anyway, if this is not worth the effort just for me, I can live with my `Box::leak`, feel free to close this in order to keep the issue count down.

**Comment by Keats** [comment]
Disabling globally is just calling `tera.autoescape_on(vec![]);`

**Comment by Keats** [comment]
You can probably fake it with `tera.autoescape_on(vec![""]);`

**Comment by tobx** [comment]
Oh wow, that does work, very clever, thank you!
