### ISSUE TITLE
Creating a new Tera instance causes app to freeze in Docker

### ISSUE THREAD

**Issue by 66OJ66** [Keats/tera#719]
Hi,

I'm using Tera in an Axum server and I've encountered an issue when starting the server in a Docker container.

Essentially, during the server start-up a Tera instance is created via the below:
```rust
match Tera::new("templates/**/*.tera") {
    Ok(tera) => {
        println!("Templating engine initialised");
        // Then run other startup tasks
    }

    Err(e) => eprintln!("Error initialising templating engine: {}", e.to_string())
}
```

When I start my server outside a Docker container it works fine.

When I run the server inside a container, it gets to `match Tera::new("templates/**/*.tera")` and just freezes
- The match block is never evaluated as neither "Templating engine initialised" or "Error initialising templating engine: ..." is outputted
  - Calling .unwrap() doesn't do anything either
- The code never progresses even if left for some time (e.g. I waited for 15 minutes and nothing happened)
- The fans on my computer audibly ramp up when starting the container, then immediately ramp down when I forcibly stop the container so it definitely feels like something is happening when the code is frozen - I'm just not sure what
- If I comment Tera out of the code, the server starts in a container without issue

Do you have an idea what could be causing this?

Is there a way to create a Tera instance without providing a glob? That way I could manually add the templates myself via Tera::add_raw_templates and see if the code still freezes.

**Comment by 66OJ66** [comment]
Just to follow-up, I added this into my code to check that the templates were actually accessible when the server is run inside a container:

```rust
let mut templates: Vec<(String, String)> = Vec::new();

for file in WalkDir::new("./templates").into_iter().filter_map(|e| e.ok()) {
    if file.metadata().unwrap().is_file() {
        let template_name: String = file.path().file_name().unwrap().to_str().unwrap().to_string();
        match fs::read_to_string(file.path()) {
            Ok(template_raw) => {
                templates.push((template_name, template_raw));
            }
            Err(_) => {}
        };
    }
}

for (name, raw) in templates{
    println!("{}", name);
    println!("{}", raw);
}
```

The filename and contents of every template were printed, so it's not a case of the server being unable to access the files in the /templates directory

**Comment by Keats** [comment]
There are some issues in some templates compilation due to a bug in the parser library (https://github.com/pest-parser/pest/issues/402). Can you try commenting out the content of the templates one by one to see if a specific template is problematic?

> Is there a way to create a Tera instance without providing a glob? That way I could manually add the templates myself via Tera::add_raw_templates and see if the code still freezes.

`Tera::default()`

**Comment by 66OJ66** [comment]
> Tera::default()

Ah sorry - this seems obvious in retrospect!

So I took my code and replaced ```Tera::new(...)``` with
```rust
let mut tera: Tera = Tera::default();

match tera.add_raw_templates(templates) {
    Ok(_) => {...}
    Err(e) => {...}
```

I tested this in a container and the server starts without issue now. All the templates render as expected too.

Not sure why ```Tera::default(...)``` is fine but ```Tera::new(...)``` causes an issue, but I'm happy to use this workaround for now.

**Comment by Keats** [comment]
Hmm that doesn't make much sense though :(
Could that be a bug in the glob library?

**Comment by 66OJ66** [comment]
I've uploaded some sample code to test that here (https://github.com/66OJ66/glob_testing)
In short, the code:
- Creates a glob_builder and iterates through files in a directory
- Prints "All files searched" to output
- Creates a Tera instance using the same glob
- Prints "Finished" to output before terminating the process

I'm able to see "All files searched" in the container but not "Finished" which suggests that there isn't an issue with the glob_builder.

Are you able to replicate this on your end?

**Comment by Keats** [comment]
It works on my machine, without going through Docker though.

**Comment by 66OJ66** [comment]
Yeah the issue only occurs in Docker containers which I'm not sure how to explain - but given ```Tera::default()``` works I'll use that going forwards and just close this.

Thanks for your help!

**Comment by bartoszpijet** [comment]
In my case that was an issue of paths, absolute paths did work, i guess there is something wrong with relational one in my specific docker setup
