### ISSUE TITLE
Unable to load Macro with `Tera::one_off()`: `Template '__tera_one_off' loads macros from 'macros_tables.html' which isn't present in Tera`

### ISSUE THREAD

**Issue by DK26** [Keats/tera#748]
Hello,

I am working a small utility project which supposed to help me design templates of different engines:
(https://github.com/DK26/rendit)
(https://github.com/DK26/rendit/releases)

It is supposed to pick up on the type of template that is given, choose and render with the appropriate supported engine.

However, the moment I introduce a macro in Tera, I get the following error message:
`Template '__tera_one_off' loads macros from 'macros.html' which isn't present in Tera`.

I've found a similar issues which was closed but did not address a resolution for this problem: #490 
I searched the documentations and so far found nothing that could help me out.

---

## File Tree

📦templates
 ┣ 📂tera
 ┃ ┣ 📜index_template.ctx.json
 ┃ ┣ 📜index_template.html
 ┃ ┣ 📜macros_tables.html

## Template File

**📜index_template.html**
```html
<!--TEMPLATE tera-->
{% import "macros_tables.html as tables %}
<!DOCTYPE html>
...
</HTML>
```

**SIDE NOTE:** Moving `{% import "macros_tables.html as tables %}` to the top, doesn't seem to have any affect.

## Macros File

**📜macros_tables.html** 

```html
{% macro type(id) %}
   Hello {{ id }}
{% endmacro type %}
```

## Rust Source Code
Is there anything that I am missing?  My Rust code for rendering looks like this:

```rust
match template {
        Template::Tera(contents) => {
            let context = tera::Context::from_value(context_data.context)
                .context("Tera rejected Context object.")?;

            Tera::one_off(&contents, &context, true)
                .context("Tera is unable to render the template.")?
        },
```

Much thanks for any help!

**Comment by Keats** [comment]
`Tera::one_off` renders a single template with a new Tera instance. Your example contains 2 templates so that can't work. You can use https://docs.rs/tera/latest/tera/struct.Tera.html#method.add_raw_templates instead and then render it after

**Comment by DK26** [comment]
Does it mean that I have to dynamically scan the template for any outside references and treat each as a different template?

Is there a way to inline them?

**Comment by Keats** [comment]
No way to inline macros or include, as they refer to filenames to know where to load them

**Comment by DK26** [comment]
Would it be appropriate to ask for a a feature request for the `Tera::one_off()` use case, that in its usage, it should automatically add any references templates to the Tera instance, as long as they are within a predefined directory? (default could be the current working directory)

**Comment by Keats** [comment]
> it should automatically add any references to templates to its own Tera instance, as long as they are within a predefined directory? 

That's just `Tera::new` unless I misunderstand it

**Comment by DK26** [comment]
In my use-case, I need to read a raw String before I decide which engine should render it, as I scan for a special `<!--TEMPLATE <ENGINE NAME>` comment. Once I have that, I remove the special comment and pass the rest for rendering with the appropriate engine.

If I understand correctly, using `Tera::new` requires you to assign it template file(s) directly. In this case, a work-around could be to write down to a file the processed data, load it back, and then create a new Tera instance with it. I'd like to avoid that, which is why I use `Tera::one_off()`. 

I'd like to note that my input data could come from STDIN as well and output to STDOUT or STDERR.

**Comment by DK26** [comment]
This is how I handled it eventually:

* Custom function `find_template_references()` checks for `include`, `import` & `extends` 
 by scanning for the next regex pattern `\{%\s+?(?:import|include|extend)\s+?"(?P<template>[a-zA-Z0-9.\-/\\_]+?)"\s.*?%\}`

```rust
let mut tera = Tera::default();

let template_references: Vec<(PathBuf, Option<String>)> =
       find_template_references(&contents, template_path)
         .into_iter()
         .map(|p| {
              let file_name = p.file_name().map(|fp| fp.to_string_lossy().to_string());
                  (p, file_name)
               })
          .collect();

tera.add_template_files(template_references)
        .context("Tera failed loading partial template files")?;

// Adds a virtual in-memory file for the main template. We need the `.html` extension to enforce HTML escaping.
tera.add_raw_template("__in_memory__.html", &contents)
         .context("Tera is unable to add the main template as raw template.")?;

tera.render("__in_memory__.html", &context)
          .context("Tera is unable to render the template.")?
```
