### ISSUE TITLE
Iterate trough json object failed

### ISSUE THREAD

**Issue by nydevel** [Keats/tera#751]
Hey, guys.

The problem is: 
I send json object into Context, its looks like:
```json
{
  variables: {
    "testvariables" :{
        "SOMEITEM": "2",
        "SOMEITEM2": "2",
        "NAME": "test",
        "SOMEELSE": "1"
      }
    }
}
```

Command below shows structure well:
```
{{ value | json_encode(pretty=true) | safe }}
```
Iterable parameter shows true

But, when i try to iterate like this:
```
{% for somitem in variables.testvariables %}
  {{somitem}}
{% endfor %}
```
It's dropped with error:
```
Some(Error { kind: Msg("Tried to iterate using key value on variable ` variables.testvariables`, but it is missing a key"), source: None }) }
```

**Comment by Keats** [comment]
From the data example, it should iterate on `testvariables`? Where is `variables` coming from?

**Comment by nydevel** [comment]
> 

sorry, forgot one level in structure, updated text

**Comment by nydevel** [comment]
I don't know why, but:
```
      {% for key, value in variables.testvariables %}
        - {{key}}={{value}}
      {% endfor %}
```

is working now (didn't work 5 mins before update to 1.17.0)
