### ISSUE TITLE
replace filter results in panic

### ISSUE THREAD

**Issue by alanstockwell** [Keats/tera#76]
The use of a template consisting only of
`{{ message|replace(from="\n", to="<br>") }}`

results in
`thread '<unnamed>' panicked at 'no pattern matched in _fn_arg_value; failed at [string, fn_arg, simple_ident, ...]', /home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.3.1/src/parser.rs:51
stack backtrace:
   1:     0x560f8723a45f - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:     0x560f8723fc2d - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:     0x560f8723ea12 - std::panicking::default_hook::h852b4223c1c00c59
   4:     0x560f8723f008 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:     0x560f8723eea2 - std::panicking::begin_panic::hf6c488cee66e7f17
   6:     0x560f8723ede0 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   7:     0x560f86b00339 - <tera::parser::Rdp<T>>::_fn_arg_value::h08850c1ed22ae8f7
                        at /home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.3.1/src/parser.rs:51
   8:     0x560f86b0135a - <tera::parser::Rdp<T>>::_fn_args::h5c0372594d2ddc62
                        at /home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.3.1/src/parser.rs:51
   9:     0x560f86b02f7a - <tera::parser::Rdp<T>>::_fn::h991da15aed3dddf7
                        at /home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.3.1/src/parser.rs:51
  10:     0x560f86b03e0d - <tera::parser::Rdp<T>>::_filters::he78ab38dd7a92213
                        at /home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.3.1/src/parser.rs:51
  11:     0x560f86b0d9a9 - <tera::parser::Rdp<T>>::_expression::hee58ca5339661318
                        at /home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.3.1/src/parser.rs:51
  12:     0x560f86af0a83 - <tera::parser::Rdp<T>>::_content::h42ee329bcedd9f9e
                        at /home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.3.1/src/parser.rs:51
  13:     0x560f86aee706 - <tera::parser::Rdp<T>>::_template::h5a92ce7d184c6b59
                        at /home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.3.1/src/parser.rs:51
  14:     0x560f86aee73b - <tera::parser::Rdp<T>>::_template::h5a92ce7d184c6b59
                        at /home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.3.1/src/parser.rs:51
  15:     0x560f86aee73b - <tera::parser::Rdp<T>>::_template::h5a92ce7d184c6b59
                        at /home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.3.1/src/parser.rs:51
  16:     0x560f86aee73b - <tera::parser::Rdp<T>>::_template::h5a92ce7d184c6b59
                        at /home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.3.1/src/parser.rs:51
  17:     0x560f86aee73b - <tera::parser::Rdp<T>>::_template::h5a92ce7d184c6b59
                        at /home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.3.1/src/parser.rs:51
  18:     0x560f86aecffd - <tera::parser::Rdp<T>>::main::h5fc000eb0502395c
                        at /home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.3.1/src/parser.rs:51
  19:     0x560f86abf3ff - tera::parser::parse::h5f7bb412bdbeaa4e
                        at /home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.3.1/src/parser.rs:551
  20:     0x560f86accdff - tera::template::Template::new::h6dd82516036273aa
                        at /home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.3.1/src/template.rs:17
  21:     0x560f86ace05f - tera::tera::Tera::new::h8ab17d08d28cbf49
                        at /home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.3.1/src/tera.rs:47`

There is no issue with
`{{message}}`

Sorry if this is something I am doing but I am at a loose end

**Comment by Keats** [comment]
This looks like a bug in Tera, I'll have a look

**Comment by Keats** [comment]
Which version are you using? It's working in master and I think I remember fixing that bug, odd I didn't publish a new version though.
I won't push a new version now though as I'll release 0.4 very soon (tomorrow or thursday most likely).
You can depending on the git `master` branch in your `Cargo.toml` to see if it works in the meantime

**Comment by alanstockwell** [comment]
I was using v0.3.1 as per crates.io but when I do as you suggested and depended on the master branch here I no longer get the panic.

Thanks for you time looking into this

**Comment by Keats** [comment]
I just pushed 0.4.0 to crates.io, it should work now!
