### ISSUE TITLE
How to chose a valur from a dropdown menù and having it back in rust

### ISSUE THREAD

**Issue by ErtyDess** [Keats/tera#778]
How to chose a valur from a dropdown menù and having it back in rust, using tera templaltes and rocket framework

![1](https://user-images.githubusercontent.com/118749390/203085821-0c0083a9-bd54-452a-b1a9-5adc782c4fdc.PNG)

dropdown code:

    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs- 
         toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Dropdown button
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="#">Red</a>
            <a class="dropdown-item" href="#">Purple</a>
            <a class="dropdown-item" href="#">White</a>
        </div>
    </div>

and for example if i pick "Red" i would like to have a color variable that will be of value "Red".

but i can't imagine how to do this, somone can help me?

    let color = ""; //if i pick Red i would like to have "Red" in here, or if i pick white this has to be "White"

**Comment by Keats** [comment]
Well you have to use either a form or JS.
