### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Keats** [Keats/tera#78]
Don't put everything in the README.md but have a static site (way later done with Tera?)

**Comment by zoumi** [comment]
https://docs.rs/tera/
You don't need a site, just write docs in code is enough.

**Comment by Keats** [comment]
I'm not a big fan of rustdoc other than documenting exported functions (which will be done properly in 0.5).
I don't really want hundreds of lines of docs in the crate itself

**Comment by Keats** [comment]
Static site will be for 0.6, I've documented the exported functions/macros/structs with examples on the 0.5 branch
