### ISSUE TITLE
missing a key on iterator

### ISSUE THREAD

**Issue by mothsART** [Keats/tera#786]
Hi,

I tried to use a generator like this :

```rust
#[derive(Serialize, Deserialize, Debug)]
pub struct Accounts {
    pub key: u32,
}

impl Accounts {
    fn new() -> Accounts {
        Accounts {
            key: 0
        }
    }
}

pub struct Account {
    pub name: String
}

impl Iterator for Accounts {
    type Item = Account;

    fn next(&mut self) -> Option<Self::Item> {
        self.key += 1;

        if self.key > 3 {
            return None;
        }

        Some(Account {
            name: format!("generate value : {}", self.key)
        })
    }
}
let accounts = Accounts::new();
context.insert("accounts", &accounts);
```

but Tera response with :

```
Err(Error { kind: Msg("Failed to render '__tera_one_off'"), source: Some(Error { kind: Msg("Tried to iterate using key value on variable `accounts`, but it is missing a key"), source: None }) })
```

Is it possible to use a generator and if so, how?

**Comment by Keats** [comment]
Tera works on serialized JSON data (that's what happens when you insert in a `Context`). In this case, the context just contains `accounts = {key: 0}` roughly.

**Comment by mothsART** [comment]
Ok, it's now clear.

I suppose, if I wish only evaluate data who's really called on a template, I must determine this before ?

**Comment by Keats** [comment]
Yep. You can use Tera functions (see docs) if you need to get some additional data but even in that case it's going to get serialized

**Comment by mothsART** [comment]
works with Askama. Thanks
