### ISSUE TITLE
Is it possible to pass a JSON-like structure to a macro in a template?

### ISSUE THREAD

**Issue by swquinn** [Keats/tera#791]
If I wanted to pass a JSON-like structure in a template to a macro, e.g. 

```
{% import "macros.tera" as macros %}
{{ macros::do_something(data={
  "foo": "bar",
  "baz": "quux"
}) }}
```

Is that possible? It does not seem to be as I receive the following error on the start of the JSON-like object `{` when attempting to do so:

```
        |
    199 |   {
        |   ^---
        |
        = expected a value that can be negated
```

Is there another way to pass in a map or dictionary of data defined within a template to a macro?

**Comment by Keats** [comment]
Map literals are not supported in Tera v1. Maybe in Tera v2 but not entirely clear. You can pass them as individual arguments.

**Comment by swquinn** [comment]
Sorry to re-open, I'm less familiar with Rust than I am with other languages. Can you provide an example of what you mean by "pass them as individual arguments"? Do you mean something like:

```
{% import "macros.tera" as macros %}
{{ macros::do_something(foo="bar", baz="quux") }}
```

If so, that's fine. But what about for slightly more complex data, like the equivalent of a list of map literals, e.g.

```json
[
  {
    "foo": "bar",
    "baz": "quux"
  },
  {
    "foo": "piyo",
    "baz": "puyo"
  },
  ...
]
```

Is there a way to pass similar data today from a template to a macro? I'm guessing the answer is no?

I'm less familiar with Rust (coming at Tera from mdBook and coming from a Python-background). Does Rust support tuples of data and could I pass an array of tuples? Any advice or examples would be appreciated, or if you can point me in a direction to get my bearings, I'd be grateful for that as well.

Thanks again, and sorry for re-opening the question.
