### ISSUE TITLE
How to pass the root context to a macro?

### ISSUE THREAD

**Issue by josecm** [Keats/tera#796]
In one file I define a macro:

```
// macro.txt

{% macro foo(bar) -%} 
bar.x
{%- endmacro foo %}
```

From another file I want to call the macro passing it the "root" context. But I don't know if this is possible and, if so, how to refer to it. Looking through Tera's documentation I don't find an answer. Also tried ChatGPT. It tells me to use a dot. However, this not seem to work:

```
{% import "macro.txt" as macros %}
macros::foo(bar=.)
```

When calling render, an Error with the message "expected a value that can be negated or an array of values" is returned.

**Comment by Keats** [comment]
You can't pass the full context to a macro, only individual variables.
If you want the full context, just use `include`

**Comment by josecm** [comment]
Clarified. Thanks!
