### ISSUE TITLE
Handle globs

### ISSUE THREAD

**Issue by Keats** [Keats/tera#8]
so you can import from say `/app/**/*.html`

The tricky point is how to name the templates, ie if we have 

```
app
|_ contacts
    |_ contact.html
|_ index.html
```
I guess `contact.html` would be called `contacts/contact.html` ? Ie name starts from the globbing `**` if there is one or `*` if there isn't

**Comment by stephanbuys** [comment]
Yeah, it will be the full path, you'd need to use `std::path::Path` if you want to be more specific. If your code says: `/app/**/*.html` then you'll get `/app/contacts/contact.html` and `/app/index.html`

**Comment by Keats** [comment]
Added in master
