### ISSUE TITLE
Number formatting (ordinals)

### ISSUE THREAD

**Issue by phisch** [Keats/tera#813]
I've been looking for an easy way to append ordinals to numbers:

```
1 -> 1st
2 -> 2nd
3 -> 3rd
4 -> 4th
...
```
As an example, the twig template engine has a number formatting filter that supports different styles, including ordinal: https://twig.symfony.com/doc/3.x/filters/format_number.html
So you can do something like `'203'|format_number(style='ordinal')` which returns `203rd`.

Other number formats could also be interesting for other people, which is why I think using a general formatting filter would be a good way to go about this.

**Comment by Keats** [comment]
It will require a dependency to make it useful (i18n) so it won't be built-in

**Comment by phisch** [comment]
Could this be more interesting to add through zola?

**Comment by Keats** [comment]
What's the usecase in Zola where you need that?

**Comment by phisch** [comment]
In my case, just for a date. It's not super important, but just a nice little detail `May 21st, 2021`.

**Comment by phisch** [comment]
For anyone finding this, you can obviously also just write a macro that does this:

```jinja2
{% macro ordinal(num) %}
    {% if num % 100 in [11,12,13] %}
        {{ num }}th
    {% else %}
        {% if num % 10 == 1 %}
            {{ num }}st
        {% elif num % 10 == 2 %}
            {{ num }}nd
        {% elif num % 10 == 3 %}
            {{ num }}rd
        {% else %}
            {{ num }}th
        {% endif %}
    {% endif %}
{% endmacro %}
```

**Comment by Keats** [comment]
Ok let's close this then.
