### ISSUE TITLE
Docs site appears to be down

### ISSUE THREAD

**Issue by chriskrycho** [Keats/tera#815]
- <https://tera.netlify.app/> is having what appear to be TLS issues
- but Netlify is not reporting any status issues

Maybe reach out to Netlify? Or maybe this will resolve itself on its own.

**Comment by Keats** [comment]
It works for me now? Maybe they had some downtime

**Comment by chriskrycho** [comment]
Hmm, still having problems here (across Safari, FF, and a Chromium). Could be a cache issue plus HSTS fun. I’ll keep poking at it and see if it resolves.

**Comment by Keats** [comment]
https://downforeveryoneorjustme.com/tera.netlify.app?proto=https says it's up as well
