### ISSUE TITLE
Render html inside the template from a tera variable

### ISSUE THREAD

**Issue by ErtyDess** [Keats/tera#823]
Hello, i pass to the template a variable that contains html, I would like to render it but instead i only see html text.
is that possible?

here i pass the variable d2 that contains html

```
  ctx.insert("landing", &d2);
  let rendered = data.tmpl.render("index.html", &ctx).unwrap();

```

this is the index.html

```
  {% extends "base.html" %}
  
  {% block content %}
  {{landing}}
  {% endblock content %}

```
i see it like this instead of the rendered html

![htmlnotremder](https://user-images.githubusercontent.com/118749390/230120035-a41b8d3b-1a3f-4b96-b4c7-11439da12954.PNG)

**Comment by Keats** [comment]
You need to do `{{ landing | safe }}` if you're sure the HTML is safe

**Comment by ErtyDess** [comment]
> 

Thank you it works!

**Comment by Keats** [comment]
No it's not possible
