### ISSUE TITLE
Cannot compile `throw`

### ISSUE THREAD

**Issue by KoltesDigital** [Keats/tera#836]
Hi. I can't get the right syntax to compile. Can you?

```
{% throw(message="Error") %}
```

Result:

```
Error { kind: Msg("Failed to parse '__tera_one_off'"), source: Some(Error { kind: Msg(" --> 1:1\n  |\n1 | {% throw(message=\"Error\") %}␍␊\n  | ^---\n  |\n  = expected a template"), source: None }) }
```

**Comment by Keats** [comment]
Try `{{ throw(message="Error") }}`

**Comment by KoltesDigital** [comment]
Ah nevermind, that was the good one. Wrapped in `{% if 0 %}` `{% endif %}` it doesn't fail anymore, so that's the expectyed result. Thanks!
