### ISSUE TITLE
Would we have a descending order?

### ISSUE THREAD

**Issue by Candlest** [Keats/tera#846]
I use Tera in my blog. Now I need to order my posts by time, but the lastest post will at the bottom of the list.
I try to use `reverse = True` like Jinja2, but it does not work.
It seem that we can only sort an array into ascending order......
Must I implement it with javascript?

**Comment by Keats** [comment]
There is a `reverse` filter, is that not what you need?

**Comment by Candlest** [comment]
> There is a `reverse` filter, is that not what you need?

Thanks
I have tried `Reverse` but never tried `reverse` !!!
My Bad  🤧
