### ISSUE TITLE
Serve CSS over HTTPS

### ISSUE THREAD

**Issue by Jengamon** [Keats/tera#853]
Just saw that the commit (a5387bd) was just merged 3 days ago, but when I was checking out the site today, it was unstyled. Opened up the dev tools and saw:

`Mixed Content: The page at 'https://tera.netlify.app/' was loaded over HTTPS, but requested an insecure stylesheet 'http://keats.github.io/tera/app.css'. This request has been blocked; the content must be served over HTTPS.`

**Comment by Keats** [comment]
The URL is not the netlify one anymore, it's http://keats.github.io/tera
