### ISSUE TITLE
Removing space between HTML tags

### ISSUE THREAD

**Issue by xpe** [Keats/tera#912]
[As is well known][1], space between inline HTML elements can affect rendering. 

Below is one way to use [Tera comments](https://keats.github.io/tera/docs/#comments) to manage this:

```html
<nav>
    <ul>
        <li><a href="/">Home</a></li>{#
        #}<li><a href="/blog">Blog</a></li>{#
        #}<li><a href="/about">About</a></li>{#
        #}<li><a href="/contact">Contact</a></li>{#
    </ul>
</nav>
```

Does Tera provide any other mechanisms to help?

[1]: https://css-tricks.com/fighting-the-space-between-inline-block-elements/

**Comment by Keats** [comment]
Nothing in particular as Tera is not HTML specific, you can use the same tricks as the article.
