### ISSUE TITLE
Strongly recommend adding asynchronous call functionality.

### ISSUE THREAD

**Issue by sunkaifei** [Keats/tera#924]
Currently, register_function cannot use asynchronous functions. I hope the author can add this feature. If this functionality can be used, it will greatly facilitate template development. The controller page would not need to call data; instead, it would just set the template, and everything would be called using tags. This would significantly speed up development and make writing templates much more convenient.

**Comment by Keats** [comment]
It's not planned at all to have anything async in the template engine.
