### ISSUE TITLE
Is this really the shortest attribute safe get/fetch one-liner

### ISSUE THREAD

**Issue by knzai** [Keats/tera#927]
I know nulls and rust, etc.

But in a templating language with all the extra limitations, some things get cumbersome, like wrapping all gets of Option(al) attributes in {%if% } etc.  Am I missed a better one-liner?

[link] | map(attribute="rel") | first

Or is it more of a Zola concern cause of the extra limitations through that context (can't just roll a custom function or filter)

Sorry, and thank you?

**Comment by Keats** [comment]
You're missing the one liner? It usually depends on what's the data structure but you can use the `default` filter

**Comment by knzai** [comment]
No, what I was missing was the *get* filter. I tried to guess at it, but didn't see it had key named param, which is of course the most obvious name possible.

I thought maybe it was a documentation issue, but no, this is just user error. Sorry and thanks!
