### ISSUE TITLE
Compiling Tera templates hangs when the Rust app in is a container

### ISSUE THREAD

**Issue by noblehelm** [Keats/tera#935]
As the title said, compiling Tera templates does hang when the same Rust app is running in a container versus running in the host machine. I tried enabling debug logs, but I could not figure it out why it hangs, only that it has a small change during glob resolution, for some reason that I cannot understand.
![image](https://github.com/user-attachments/assets/7f356115-3736-47a6-af4f-e1b9706fa8be)
As the image above did show, it is stuck in the compiling phase of Tera templates. COmpare this with the image of it running in the host machine:
![image](https://github.com/user-attachments/assets/51542948-3a74-4135-9136-33ffd93a725f)

The app was tested on both an `alpine:3.20` image and `ubuntu:noble` image and it didn't work. The only difference I noticed is, for some reason, the 'host' app didn't have the `template` folder during glob resolution, while in the container version it did.

Does this somehow have something to do with it hanging?

**Comment by Keats** [comment]
See https://github.com/Keats/tera/issues/719 and https://github.com/Keats/tera/issues/740

**Comment by noblehelm** [comment]
Welp, should've researched better..

Seems weird though, because my app is not on the root directory, it is inside /etc, so it shouldn't have dealt with this bug - at least in theory.

Will try the `Tera::default()` route to see if it works.

Thanks!
