### ISSUE TITLE
Get a group of items that misses an attribute

### ISSUE THREAD

**Issue by akarmes** [Keats/tera#944]
Is there a simple and concise way of getting a group of items with a missing attribute? Both `group_by` and `filter` discard those items. And I'd like to render those as a separate group.

**Comment by azemlya** [comment]
I think the ternary operator for the "for" construction can help, but it is not implemented in tera2 (and in tera1 too). It would be nice to implement this (as in Jinja2):
```
{% for commit in commits if commit.scope is not defined or ... %}
...
{% endfor -%}
```
