### ISSUE TITLE
Add `Tera` constructor from in-memory buffer

### ISSUE THREAD

**Issue by gyscos** [Keats/tera#98]
It is sometimes desirable not to load files at runtime, but to include them in the binary (with `include_bytes!` or `include_str1`).
Tera currently doesn't allow loading a template from such a buffer.

A potential constructor could take a map of strings (filenames) to `&str` or `&[u8]`.

**Comment by Keats** [comment]
Isn't it the `add_template` and `add_templates` method (https://docs.rs/tera/0.5.0/tera/struct.Tera.html#method.add_template)?

Just realised I forgot to document them in the README though

**Comment by gyscos** [comment]
Oh, so should `Tera` be built using `Tera::new("")`?

**Comment by Keats** [comment]
Updated the README: https://github.com/Keats/tera/commit/8d553f66d2c73c6f37f8f2c14e63adcd80b45a02

Hopefully that makes sense

**Comment by gyscos** [comment]
Indeed, thanks!

**Comment by gyscos** [comment]
I see `add_template` was removed for some reason. Is this use-case no longer supported?

**Comment by Keats** [comment]
It's called `add_raw_template` and `add_raw_templates` now. I marked them as hidden in the docs by mistake, they will be back in the docs next release (sometimes this week)
